-- +goose Up
-- An identity provider connection is revisioned: every edit appends a revision,
-- so a caller can pin one and keep reading it. This table carries identity
-- only, and no column records which revision is newest (ADR 063 section 7).
CREATE TABLE zitadel_nextgen.idp_connections (
    project_id TEXT COLLATE "C" NOT NULL
        REFERENCES zitadel_nextgen.projects (id) ON DELETE CASCADE
    , id TEXT COLLATE "C" NOT NULL CHECK (id <> '')
    , slug TEXT COLLATE "C" NOT NULL CHECK (slug <> '')
    -- No updated_at: a read serves the newest revision's created_at, and a
    -- column here could only disagree with it.
    , created_at TIMESTAMPTZ NOT NULL DEFAULT now()

    , PRIMARY KEY (project_id, id)
);

-- Spanner reports empty constraint names, so a create must have only one
-- constraint it can trip: this one. The id is generated by the dialect, so the
-- primary key cannot collide.
CREATE UNIQUE INDEX uq_idp_connections_project_slug
    ON zitadel_nextgen.idp_connections (project_id, slug);

-- Connections list oldest-first by keyset; id breaks created_at ties.
CREATE INDEX idx_idp_connections_project_created_at
    ON zitadel_nextgen.idp_connections (project_id, created_at, id);

-- One revision of one connection. Rows are never updated, because a caller can
-- pin a revision and expects it to stay as it was.
CREATE TABLE zitadel_nextgen.idp_connection_revisions (
    project_id TEXT COLLATE "C" NOT NULL
    , id TEXT COLLATE "C" NOT NULL CHECK (id <> '')
    , connection_id TEXT COLLATE "C" NOT NULL
    -- The configuration document is opaque to storage: the API contract owns
    -- its shape, and nothing here filters or orders on a field inside it.
    , document JSONB NOT NULL CHECK (jsonb_typeof(document) = 'object')
    , created_at TIMESTAMPTZ NOT NULL DEFAULT now()

    , PRIMARY KEY (project_id, id)
    -- No direct project FK: the cascade reaches revisions through the parent
    -- connection.
    , CONSTRAINT fk_idp_connection_revisions_connection
        FOREIGN KEY (project_id, connection_id)
        REFERENCES zitadel_nextgen.idp_connections (project_id, id)
        ON DELETE CASCADE
);

-- Two revisions of one connection stamped at the same instant have no newest,
-- so uniqueness rules that out (ADR 063 section 7): the second write fails
-- instead of one of the two being picked at random. The same index serves the
-- newest-revision lookup and the newest-first history page, because a btree
-- also scans backward.
CREATE UNIQUE INDEX uq_idp_connection_revisions_connection_created_at
    ON zitadel_nextgen.idp_connection_revisions (project_id, connection_id, created_at);

-- +goose Down
DROP INDEX IF EXISTS zitadel_nextgen.uq_idp_connection_revisions_connection_created_at;
DROP TABLE IF EXISTS zitadel_nextgen.idp_connection_revisions;
DROP INDEX IF EXISTS zitadel_nextgen.idx_idp_connections_project_created_at;
DROP INDEX IF EXISTS zitadel_nextgen.uq_idp_connections_project_slug;
DROP TABLE IF EXISTS zitadel_nextgen.idp_connections;
