-- +goose Up
-- An identity link pins one provider subject on one connection to one user.
-- It keys on the revision-stable connection id, never the revision (ADR 063).
-- Links go with the user: they are provisioning metadata attached to the
-- local user (ADR 024, "External systems are modeled as provisioning
-- authorities"), not a lifecycle-managed resource, so the user FK cascades.
-- The connection FK is RESTRICT: connection deletion is #1013's decision.
-- No project FK: the project reaches a link through its connection and its
-- user, and both cascade from the project.
CREATE TABLE zitadel_nextgen.idp_identity_links (
    project_id TEXT COLLATE "C" NOT NULL
    , id TEXT COLLATE "C" NOT NULL CHECK (id <> '')
    , connection_id TEXT COLLATE "C" NOT NULL
    , subject TEXT COLLATE "C" NOT NULL CHECK (subject <> '')
    , user_id TEXT COLLATE "C" NOT NULL
    -- No updated_at: rows are never updated.
    , created_at TIMESTAMPTZ NOT NULL DEFAULT now()

    , PRIMARY KEY (project_id, id)
    , CONSTRAINT fk_idp_identity_links_connection
        FOREIGN KEY (project_id, connection_id)
        REFERENCES zitadel_nextgen.idp_connections (project_id, id)
        ON DELETE RESTRICT
    , CONSTRAINT fk_idp_identity_links_user
        FOREIGN KEY (project_id, user_id)
        REFERENCES zitadel_nextgen.users (project_id, id)
        ON DELETE CASCADE
);

-- One user per (connection, subject). The id is generated by the dialect, so
-- the primary key cannot collide, leaving this the only constraint a create can
-- trip. Spanner reports empty constraint names, so that matters there.
CREATE UNIQUE INDEX uq_idp_identity_links_connection_subject
    ON zitadel_nextgen.idp_identity_links (project_id, connection_id, subject);

-- Drives the user-delete cascade, which would otherwise scan the table
-- (precedent: idx_sessions_user, 000019).
CREATE INDEX idx_idp_identity_links_project_user
    ON zitadel_nextgen.idp_identity_links (project_id, user_id);

-- +goose Down
DROP INDEX IF EXISTS zitadel_nextgen.idx_idp_identity_links_project_user;
DROP INDEX IF EXISTS zitadel_nextgen.uq_idp_identity_links_connection_subject;
DROP TABLE IF EXISTS zitadel_nextgen.idp_identity_links;
