/**
 * Minimal English locale dictionary.
 *
 * The `| t` filter looks up `text_key` strings here. Missing keys fall through
 * to the raw key (matches the spec in
 * `docs/design/flowengine/flow-engine-guide.md`).
 *
 * Text keys are auto-generated by the server from the flow definition:
 *   - Step titles:       `<step>.title`
 *   - Step descriptions: `<step>.description`
 *   - Field labels:      `<step>.field.<field>`
 *   - Action labels:     `<step>.action.<action>`
 *
 * Copy aligned to Figma screens file `xkvBjkOJ8ENuHdTGZHXezK` (May 2026).
 * MVP only — multi-locale support is deferred.
 */
export const en: Record<string, string> = {
  // ═══════════════════════════════════════════════════════════════════════════
  // Step: identifier (email entry — first screen)
  // Figma 2xl `6593:141983`, card `6593:141985`, stack `6593:141989`
  // ═══════════════════════════════════════════════════════════════════════════
  "identifier.title": "Sign in",
  "identifier.description": "Enter your email to continue",
  "identifier.field.email": "Email",
  "identifier.field.email.placeholder": "you@example.com",
  "identifier.field.password": "Password",
  "identifier.action.submit": "Sign in",
  "identifier.action.continue": "Continue",
  "identifier.action.passkey": "Sign in with a passkey",
  "identifier.action.register.lead": "Don't have an account? ",
  "identifier.action.register.link": "Sign up",

  // ═══════════════════════════════════════════════════════════════════════════
  // Step: authenticate (password entry — sign-in flow)
  // ═══════════════════════════════════════════════════════════════════════════
  "authenticate.title": "Sign in",
  "authenticate.description": "Enter your password",
  "authenticate.field.password": "Password",
  "authenticate.action.submit": "Sign in",

  // ═══════════════════════════════════════════════════════════════════════════
  // Step: choose-register (registration path selection — no fields)
  // ═══════════════════════════════════════════════════════════════════════════
  "choose-register.title": "Create your account",
  "choose-register.description": "Choose how you'd like to sign up",
  "choose-register.action.register-with-password": "Sign up with password",
  "choose-register.action.register-with-passkey": "Sign up with passkey",

  // ═══════════════════════════════════════════════════════════════════════════
  // Step: collect-credentials (email + password — password registration)
  // ═══════════════════════════════════════════════════════════════════════════
  "collect-credentials.title": "Create your account",
  "collect-credentials.description": "Set up your email and password",
  "collect-credentials.field.email": "Email",
  "collect-credentials.field.email.placeholder": "you@example.com",
  "collect-credentials.field.password": "Password",
  // No static password rule hint: the only enforced rule is the schema's
  // minLength, and "symbol + number" was never enforced. The client will build
  // this hint dynamically from the API's per-field validation rules (#251).
  "collect-credentials.action.submit": "Sign up",

  // ═══════════════════════════════════════════════════════════════════════════
  // Step: register-password (password entry — registration path)
  // Default login flow: register → register-password → passkey-upsell → done
  // ═══════════════════════════════════════════════════════════════════════════
  "register-password.title": "Create your password",
  "register-password.description": "Choose a secure password for your account",
  "register-password.field.password": "Password",
  "register-password.action.submit": "Sign up",
  "register-password.action.back": "Back",

  // ═══════════════════════════════════════════════════════════════════════════
  // Step: passkey-upsell (passkey enrollment offer — after registration)
  // Figma `6594:630`, heading `6594:89142`, body `6594:12796`
  // ═══════════════════════════════════════════════════════════════════════════
  "passkey-upsell.title": "Sign in faster next time",
  "passkey-upsell.description": "No password needed ever again.",
  "passkey-upsell.description.line1": "No password needed ever again.",
  "passkey-upsell.description.line2": "Sign in with Face ID, Touch ID, or PIN.",
  "passkey-upsell.action.passkey_register": "Set up passkey",
  "passkey-upsell.action.skip": "Skip for now",
  // Figma `6594:630` setup-passkey annotations — kept for backward compat.
  "passkey-upsell.action.setup": "Set up passkey",

  // ═══════════════════════════════════════════════════════════════════════════
  // Step: collect-passkey-email (email only — passkey-only registration)
  // ═══════════════════════════════════════════════════════════════════════════
  "collect-passkey-email.title": "Create your account",
  "collect-passkey-email.description": "Enter your email to set up a passkey",
  "collect-passkey-email.field.email": "Email",
  "collect-passkey-email.field.email.placeholder": "you@example.com",
  "collect-passkey-email.action.submit": "Continue",

  // ═══════════════════════════════════════════════════════════════════════════
  // Step: passkey-enroll (mandatory passkey ceremony — passkey-only path)
  // ═══════════════════════════════════════════════════════════════════════════
  "passkey-enroll.title": "Set up your passkey",
  "passkey-enroll.description": "Use Face ID, Touch ID, or your device PIN to create a passkey.",
  "passkey-enroll.action.passkey_register": "Set up passkey",

  // ═══════════════════════════════════════════════════════════════════════════
  // Step: done (terminal — signed-in confirmation)
  // Figma `6596:132846`
  // ═══════════════════════════════════════════════════════════════════════════
  "done.title": "You're signed in as",
  "done.description": "",

  // --- Step-name aliases used by the default login flow ---
  "password.title": "Sign in",
  "password.description": "Enter your password",
  "password.field.password": "Password",
  "password.action.signin": "Sign in",
  "password.action.passkey": "Sign in with a passkey",
  "password.action.back": "Back",
  "password.action.register.lead": "Don't have an account? ",
  "password.action.register.link": "Sign up",

  "register.title": "Create your account",
  // Empty by design — the sign-up card has no subheadline (Figma 6593:141743).
  "register.description": "",
  "register.field.email": "Email",
  "register.field.email.placeholder": "you@example.com",
  "register.field.password": "Password",
  "register.field.givenName": "Given name",
  "register.field.familyName": "Family name",
  "register.field.companyName": "Company name",
  // Native <input type="date"> localizes its own display format to the user's
  // locale and submits ISO YYYY-MM-DD — no placeholder/help format hint needed.
  "register.field.dateOfBirth": "Date of birth",
  "register.field.country": "Country",
  "register.field.country.placeholder": "Select your country",
  "register.field.terms": "I agree to the terms of service",
  "register.action.password": "Continue with password",
  "register.action.passkey": "Continue with a passkey",
  "register.action.submit": "Sign up",
  "register.action.back": "Back",
  "register.action.sign_in.lead": "Already have an account? ",
  "register.action.sign_in.link": "Sign in",

  "complete.title": "You're signed in as",
  "signed-in.continue": "Continue",
  "signed-in.logout": "Sign out",

  // --- Passkey login ---
  "passkey-login.title": "Sign in with your passkey",

  // --- Step: passkey-first (entry step of the passkey-first preset) ---
  "passkey-first.title": "Sign in",
  "passkey-first.description": "Use your passkey to continue",
  "passkey-first.action.passkey": "Continue with passkey",
  "passkey-first.action.email_fallback": "Use email instead",

  // --- Password recovery ---
  "recover.title": "Check your email",
  "recover.description": "We sent a password reset link to your email address.",
  "recover.action.back": "Back to sign in",

  // --- Shared actions ---
  "submit.continue": "Continue",
  "submit.signin": "Sign in",
  "action.forgot_password": "Forgot password?",
  "action.cancel": "Cancel",
  // Generic fallback for the engine-injected `<step>.action.back` key on
  // custom step names (see INJECTED_KEY_FALLBACKS in liquid.ts).
  "action.back": "Back",

  // --- SSO ---
  "sso.redirect.title": "Redirecting to your provider…",

  // --- Passkey ceremony ---
  "passkey.pending.status": "Waiting for your passkey…",

  // --- Passkey errors ---
  // Covers both user dismissal and any close the browser reports as
  // NotAllowedError — it fires for login and registration ceremonies alike.
  "error.passkey_cancelled": "The passkey prompt was closed before completing.",
  "error.passkey_timeout": "The passkey request timed out. Please try again.",
  "error.passkey_not_registered":
    "This passkey is not registered. Please sign in with your email and password.",
  "error.passkey_setup_failed": "Passkey registration did not complete. Please try again.",
  "error.passkey_unsupported": "This device does not support passkeys",
  "error.passkey_failed": "Something went wrong. Please try again.",
  "error.passkey_invalid": "This passkey could not be verified. Please try again.",
  "error.passkey_registration_invalid":
    "The new passkey could not be verified. Please try registering it again.",

  // --- Field / form errors (Figma field annotations) ---
  "error.email_required": "Please enter an email address",
  "error.email_invalid": "Please enter a valid email",
  "error.password_required": "Please enter a password",
  "error.password_incorrect": "Wrong email or password.",
  "error.email_exists": "An account with this email already exists.",
  /** Figma sign-in error `6602:180268` — inline on password field. */
  "error.invalid_credentials": "Wrong email or password.",
  "error.required": "This field is required.",

  // --- Generic field-rule fallbacks ({0} = field label) ---
  // Used by `localiseFlowErrorKeys` (liquid.ts) when no field-specific
  // entry exists for a server-emitted `error.<field>_<rule>` key.
  "error.field_required": "{0} is required.",
  "error.field_format": "Please enter a valid {0}.",
  "error.field_min_length": "{0} is too short.",
  "error.field_max_length": "{0} is too long.",
  "error.field_invalid": "Please check {0}.",

  // --- Sign-in form-level alert (Figma `6594:125237`, alert `6596:132779`) ---
  "error.sign_in_server.title": "We couldn't complete your sign in.",
  "error.sign_in_server.body": "Please try again in a few minutes",
};

export type Locale = Record<string, string>;
