// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/nextgen/internal/domain (interfaces: SchemaResolver,FlowFieldResolver,FlowPasskeyRegistrationService,FlowOnSuccessHandler,FlowPasskeyUserCreater,JSONSchemaStore,FlowAuthAttemptService)
//
// Generated by this command:
//
//	mockgen -typed -package domainmock -destination ./domain.mock.go github.com/zitadel/nextgen/internal/domain SchemaResolver,FlowFieldResolver,FlowPasskeyRegistrationService,FlowOnSuccessHandler,FlowPasskeyUserCreater,JSONSchemaStore,FlowAuthAttemptService
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	jsonschema "github.com/ianlancetaylor/jsonschema"
	domain "github.com/zitadel/nextgen/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSchemaResolver is a mock of SchemaResolver interface.
type MockSchemaResolver struct {
	ctrl     *gomock.Controller
	recorder *MockSchemaResolverMockRecorder
	isgomock struct{}
}

// MockSchemaResolverMockRecorder is the mock recorder for MockSchemaResolver.
type MockSchemaResolverMockRecorder struct {
	mock *MockSchemaResolver
}

// NewMockSchemaResolver creates a new mock instance.
func NewMockSchemaResolver(ctrl *gomock.Controller) *MockSchemaResolver {
	mock := &MockSchemaResolver{ctrl: ctrl}
	mock.recorder = &MockSchemaResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchemaResolver) EXPECT() *MockSchemaResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockSchemaResolver) Resolve(ctx context.Context, store domain.JSONSchemaStore, projectID, schemaURL string, rootSchema []byte) (*jsonschema.Schema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, store, projectID, schemaURL, rootSchema)
	ret0, _ := ret[0].(*jsonschema.Schema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockSchemaResolverMockRecorder) Resolve(ctx, store, projectID, schemaURL, rootSchema any) *MockSchemaResolverResolveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockSchemaResolver)(nil).Resolve), ctx, store, projectID, schemaURL, rootSchema)
	return &MockSchemaResolverResolveCall{Call: call}
}

// MockSchemaResolverResolveCall wrap *gomock.Call
type MockSchemaResolverResolveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSchemaResolverResolveCall) Return(arg0 *jsonschema.Schema, arg1 error) *MockSchemaResolverResolveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSchemaResolverResolveCall) Do(f func(context.Context, domain.JSONSchemaStore, string, string, []byte) (*jsonschema.Schema, error)) *MockSchemaResolverResolveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSchemaResolverResolveCall) DoAndReturn(f func(context.Context, domain.JSONSchemaStore, string, string, []byte) (*jsonschema.Schema, error)) *MockSchemaResolverResolveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockFlowFieldResolver is a mock of FlowFieldResolver interface.
type MockFlowFieldResolver struct {
	ctrl     *gomock.Controller
	recorder *MockFlowFieldResolverMockRecorder
	isgomock struct{}
}

// MockFlowFieldResolverMockRecorder is the mock recorder for MockFlowFieldResolver.
type MockFlowFieldResolverMockRecorder struct {
	mock *MockFlowFieldResolver
}

// NewMockFlowFieldResolver creates a new mock instance.
func NewMockFlowFieldResolver(ctrl *gomock.Controller) *MockFlowFieldResolver {
	mock := &MockFlowFieldResolver{ctrl: ctrl}
	mock.recorder = &MockFlowFieldResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowFieldResolver) EXPECT() *MockFlowFieldResolverMockRecorder {
	return m.recorder
}

// MissingRequired mocks base method.
func (m *MockFlowFieldResolver) MissingRequired(fields domain.FlowResolvedFields, values map[string]any) domain.FlowFieldValidationErrors {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MissingRequired", fields, values)
	ret0, _ := ret[0].(domain.FlowFieldValidationErrors)
	return ret0
}

// MissingRequired indicates an expected call of MissingRequired.
func (mr *MockFlowFieldResolverMockRecorder) MissingRequired(fields, values any) *MockFlowFieldResolverMissingRequiredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MissingRequired", reflect.TypeOf((*MockFlowFieldResolver)(nil).MissingRequired), fields, values)
	return &MockFlowFieldResolverMissingRequiredCall{Call: call}
}

// MockFlowFieldResolverMissingRequiredCall wrap *gomock.Call
type MockFlowFieldResolverMissingRequiredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowFieldResolverMissingRequiredCall) Return(arg0 domain.FlowFieldValidationErrors) *MockFlowFieldResolverMissingRequiredCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowFieldResolverMissingRequiredCall) Do(f func(domain.FlowResolvedFields, map[string]any) domain.FlowFieldValidationErrors) *MockFlowFieldResolverMissingRequiredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowFieldResolverMissingRequiredCall) DoAndReturn(f func(domain.FlowResolvedFields, map[string]any) domain.FlowFieldValidationErrors) *MockFlowFieldResolverMissingRequiredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Resolve mocks base method.
func (m *MockFlowFieldResolver) Resolve(schema *jsonschema.Schema, stepName string, fields []domain.Field) (domain.FlowResolvedFields, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", schema, stepName, fields)
	ret0, _ := ret[0].(domain.FlowResolvedFields)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockFlowFieldResolverMockRecorder) Resolve(schema, stepName, fields any) *MockFlowFieldResolverResolveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockFlowFieldResolver)(nil).Resolve), schema, stepName, fields)
	return &MockFlowFieldResolverResolveCall{Call: call}
}

// MockFlowFieldResolverResolveCall wrap *gomock.Call
type MockFlowFieldResolverResolveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowFieldResolverResolveCall) Return(arg0 domain.FlowResolvedFields, arg1 error) *MockFlowFieldResolverResolveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowFieldResolverResolveCall) Do(f func(*jsonschema.Schema, string, []domain.Field) (domain.FlowResolvedFields, error)) *MockFlowFieldResolverResolveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowFieldResolverResolveCall) DoAndReturn(f func(*jsonschema.Schema, string, []domain.Field) (domain.FlowResolvedFields, error)) *MockFlowFieldResolverResolveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Validate mocks base method.
func (m *MockFlowFieldResolver) Validate(fields domain.FlowResolvedFields, values map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", fields, values)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockFlowFieldResolverMockRecorder) Validate(fields, values any) *MockFlowFieldResolverValidateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockFlowFieldResolver)(nil).Validate), fields, values)
	return &MockFlowFieldResolverValidateCall{Call: call}
}

// MockFlowFieldResolverValidateCall wrap *gomock.Call
type MockFlowFieldResolverValidateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowFieldResolverValidateCall) Return(arg0 error) *MockFlowFieldResolverValidateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowFieldResolverValidateCall) Do(f func(domain.FlowResolvedFields, map[string]any) error) *MockFlowFieldResolverValidateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowFieldResolverValidateCall) DoAndReturn(f func(domain.FlowResolvedFields, map[string]any) error) *MockFlowFieldResolverValidateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockFlowPasskeyRegistrationService is a mock of FlowPasskeyRegistrationService interface.
type MockFlowPasskeyRegistrationService struct {
	ctrl     *gomock.Controller
	recorder *MockFlowPasskeyRegistrationServiceMockRecorder
	isgomock struct{}
}

// MockFlowPasskeyRegistrationServiceMockRecorder is the mock recorder for MockFlowPasskeyRegistrationService.
type MockFlowPasskeyRegistrationServiceMockRecorder struct {
	mock *MockFlowPasskeyRegistrationService
}

// NewMockFlowPasskeyRegistrationService creates a new mock instance.
func NewMockFlowPasskeyRegistrationService(ctrl *gomock.Controller) *MockFlowPasskeyRegistrationService {
	mock := &MockFlowPasskeyRegistrationService{ctrl: ctrl}
	mock.recorder = &MockFlowPasskeyRegistrationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowPasskeyRegistrationService) EXPECT() *MockFlowPasskeyRegistrationServiceMockRecorder {
	return m.recorder
}

// IssuePasskeyRegistrationChallenge mocks base method.
func (m *MockFlowPasskeyRegistrationService) IssuePasskeyRegistrationChallenge(ctx context.Context, in domain.FlowIssuePasskeyRegistrationChallengeInput) (domain.FlowPasskeyRegistrationChallengeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssuePasskeyRegistrationChallenge", ctx, in)
	ret0, _ := ret[0].(domain.FlowPasskeyRegistrationChallengeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssuePasskeyRegistrationChallenge indicates an expected call of IssuePasskeyRegistrationChallenge.
func (mr *MockFlowPasskeyRegistrationServiceMockRecorder) IssuePasskeyRegistrationChallenge(ctx, in any) *MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssuePasskeyRegistrationChallenge", reflect.TypeOf((*MockFlowPasskeyRegistrationService)(nil).IssuePasskeyRegistrationChallenge), ctx, in)
	return &MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall{Call: call}
}

// MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall wrap *gomock.Call
type MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall) Return(arg0 domain.FlowPasskeyRegistrationChallengeOutput, arg1 error) *MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall) Do(f func(context.Context, domain.FlowIssuePasskeyRegistrationChallengeInput) (domain.FlowPasskeyRegistrationChallengeOutput, error)) *MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall) DoAndReturn(f func(context.Context, domain.FlowIssuePasskeyRegistrationChallengeInput) (domain.FlowPasskeyRegistrationChallengeOutput, error)) *MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubmitPasskeyRegistration mocks base method.
func (m *MockFlowPasskeyRegistrationService) SubmitPasskeyRegistration(ctx context.Context, in domain.FlowSubmitPasskeyRegistrationInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitPasskeyRegistration", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitPasskeyRegistration indicates an expected call of SubmitPasskeyRegistration.
func (mr *MockFlowPasskeyRegistrationServiceMockRecorder) SubmitPasskeyRegistration(ctx, in any) *MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitPasskeyRegistration", reflect.TypeOf((*MockFlowPasskeyRegistrationService)(nil).SubmitPasskeyRegistration), ctx, in)
	return &MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall{Call: call}
}

// MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall wrap *gomock.Call
type MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall) Return(arg0 error) *MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall) Do(f func(context.Context, domain.FlowSubmitPasskeyRegistrationInput) error) *MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall) DoAndReturn(f func(context.Context, domain.FlowSubmitPasskeyRegistrationInput) error) *MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockFlowOnSuccessHandler is a mock of FlowOnSuccessHandler interface.
type MockFlowOnSuccessHandler struct {
	ctrl     *gomock.Controller
	recorder *MockFlowOnSuccessHandlerMockRecorder
	isgomock struct{}
}

// MockFlowOnSuccessHandlerMockRecorder is the mock recorder for MockFlowOnSuccessHandler.
type MockFlowOnSuccessHandlerMockRecorder struct {
	mock *MockFlowOnSuccessHandler
}

// NewMockFlowOnSuccessHandler creates a new mock instance.
func NewMockFlowOnSuccessHandler(ctrl *gomock.Controller) *MockFlowOnSuccessHandler {
	mock := &MockFlowOnSuccessHandler{ctrl: ctrl}
	mock.recorder = &MockFlowOnSuccessHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowOnSuccessHandler) EXPECT() *MockFlowOnSuccessHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockFlowOnSuccessHandler) Handle(ctx context.Context, in domain.FlowOnSuccessInput) (domain.FlowOnSuccessResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, in)
	ret0, _ := ret[0].(domain.FlowOnSuccessResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockFlowOnSuccessHandlerMockRecorder) Handle(ctx, in any) *MockFlowOnSuccessHandlerHandleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockFlowOnSuccessHandler)(nil).Handle), ctx, in)
	return &MockFlowOnSuccessHandlerHandleCall{Call: call}
}

// MockFlowOnSuccessHandlerHandleCall wrap *gomock.Call
type MockFlowOnSuccessHandlerHandleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowOnSuccessHandlerHandleCall) Return(arg0 domain.FlowOnSuccessResult, arg1 error) *MockFlowOnSuccessHandlerHandleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowOnSuccessHandlerHandleCall) Do(f func(context.Context, domain.FlowOnSuccessInput) (domain.FlowOnSuccessResult, error)) *MockFlowOnSuccessHandlerHandleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowOnSuccessHandlerHandleCall) DoAndReturn(f func(context.Context, domain.FlowOnSuccessInput) (domain.FlowOnSuccessResult, error)) *MockFlowOnSuccessHandlerHandleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockFlowPasskeyUserCreater is a mock of FlowPasskeyUserCreater interface.
type MockFlowPasskeyUserCreater struct {
	ctrl     *gomock.Controller
	recorder *MockFlowPasskeyUserCreaterMockRecorder
	isgomock struct{}
}

// MockFlowPasskeyUserCreaterMockRecorder is the mock recorder for MockFlowPasskeyUserCreater.
type MockFlowPasskeyUserCreaterMockRecorder struct {
	mock *MockFlowPasskeyUserCreater
}

// NewMockFlowPasskeyUserCreater creates a new mock instance.
func NewMockFlowPasskeyUserCreater(ctrl *gomock.Controller) *MockFlowPasskeyUserCreater {
	mock := &MockFlowPasskeyUserCreater{ctrl: ctrl}
	mock.recorder = &MockFlowPasskeyUserCreaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowPasskeyUserCreater) EXPECT() *MockFlowPasskeyUserCreaterMockRecorder {
	return m.recorder
}

// CreateProvisionalUser mocks base method.
func (m *MockFlowPasskeyUserCreater) CreateProvisionalUser(ctx context.Context, userID string, state *domain.FlowState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProvisionalUser", ctx, userID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProvisionalUser indicates an expected call of CreateProvisionalUser.
func (mr *MockFlowPasskeyUserCreaterMockRecorder) CreateProvisionalUser(ctx, userID, state any) *MockFlowPasskeyUserCreaterCreateProvisionalUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProvisionalUser", reflect.TypeOf((*MockFlowPasskeyUserCreater)(nil).CreateProvisionalUser), ctx, userID, state)
	return &MockFlowPasskeyUserCreaterCreateProvisionalUserCall{Call: call}
}

// MockFlowPasskeyUserCreaterCreateProvisionalUserCall wrap *gomock.Call
type MockFlowPasskeyUserCreaterCreateProvisionalUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowPasskeyUserCreaterCreateProvisionalUserCall) Return(arg0 error) *MockFlowPasskeyUserCreaterCreateProvisionalUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowPasskeyUserCreaterCreateProvisionalUserCall) Do(f func(context.Context, string, *domain.FlowState) error) *MockFlowPasskeyUserCreaterCreateProvisionalUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowPasskeyUserCreaterCreateProvisionalUserCall) DoAndReturn(f func(context.Context, string, *domain.FlowState) error) *MockFlowPasskeyUserCreaterCreateProvisionalUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockJSONSchemaStore is a mock of JSONSchemaStore interface.
type MockJSONSchemaStore struct {
	ctrl     *gomock.Controller
	recorder *MockJSONSchemaStoreMockRecorder
	isgomock struct{}
}

// MockJSONSchemaStoreMockRecorder is the mock recorder for MockJSONSchemaStore.
type MockJSONSchemaStoreMockRecorder struct {
	mock *MockJSONSchemaStore
}

// NewMockJSONSchemaStore creates a new mock instance.
func NewMockJSONSchemaStore(ctrl *gomock.Controller) *MockJSONSchemaStore {
	mock := &MockJSONSchemaStore{ctrl: ctrl}
	mock.recorder = &MockJSONSchemaStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJSONSchemaStore) EXPECT() *MockJSONSchemaStoreMockRecorder {
	return m.recorder
}

// CreateJSONSchema mocks base method.
func (m *MockJSONSchemaStore) CreateJSONSchema(ctx context.Context, schema *domain.JSONSchema) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJSONSchema", ctx, schema)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateJSONSchema indicates an expected call of CreateJSONSchema.
func (mr *MockJSONSchemaStoreMockRecorder) CreateJSONSchema(ctx, schema any) *MockJSONSchemaStoreCreateJSONSchemaCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJSONSchema", reflect.TypeOf((*MockJSONSchemaStore)(nil).CreateJSONSchema), ctx, schema)
	return &MockJSONSchemaStoreCreateJSONSchemaCall{Call: call}
}

// MockJSONSchemaStoreCreateJSONSchemaCall wrap *gomock.Call
type MockJSONSchemaStoreCreateJSONSchemaCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaStoreCreateJSONSchemaCall) Return(arg0 error) *MockJSONSchemaStoreCreateJSONSchemaCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaStoreCreateJSONSchemaCall) Do(f func(context.Context, *domain.JSONSchema) error) *MockJSONSchemaStoreCreateJSONSchemaCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaStoreCreateJSONSchemaCall) DoAndReturn(f func(context.Context, *domain.JSONSchema) error) *MockJSONSchemaStoreCreateJSONSchemaCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetJSONSchemaByID mocks base method.
func (m *MockJSONSchemaStore) GetJSONSchemaByID(ctx context.Context, projectID, schemaID string) (*domain.JSONSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSONSchemaByID", ctx, projectID, schemaID)
	ret0, _ := ret[0].(*domain.JSONSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJSONSchemaByID indicates an expected call of GetJSONSchemaByID.
func (mr *MockJSONSchemaStoreMockRecorder) GetJSONSchemaByID(ctx, projectID, schemaID any) *MockJSONSchemaStoreGetJSONSchemaByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSONSchemaByID", reflect.TypeOf((*MockJSONSchemaStore)(nil).GetJSONSchemaByID), ctx, projectID, schemaID)
	return &MockJSONSchemaStoreGetJSONSchemaByIDCall{Call: call}
}

// MockJSONSchemaStoreGetJSONSchemaByIDCall wrap *gomock.Call
type MockJSONSchemaStoreGetJSONSchemaByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaStoreGetJSONSchemaByIDCall) Return(arg0 *domain.JSONSchema, arg1 error) *MockJSONSchemaStoreGetJSONSchemaByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaStoreGetJSONSchemaByIDCall) Do(f func(context.Context, string, string) (*domain.JSONSchema, error)) *MockJSONSchemaStoreGetJSONSchemaByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaStoreGetJSONSchemaByIDCall) DoAndReturn(f func(context.Context, string, string) (*domain.JSONSchema, error)) *MockJSONSchemaStoreGetJSONSchemaByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockFlowAuthAttemptService is a mock of FlowAuthAttemptService interface.
type MockFlowAuthAttemptService struct {
	ctrl     *gomock.Controller
	recorder *MockFlowAuthAttemptServiceMockRecorder
	isgomock struct{}
}

// MockFlowAuthAttemptServiceMockRecorder is the mock recorder for MockFlowAuthAttemptService.
type MockFlowAuthAttemptServiceMockRecorder struct {
	mock *MockFlowAuthAttemptService
}

// NewMockFlowAuthAttemptService creates a new mock instance.
func NewMockFlowAuthAttemptService(ctrl *gomock.Controller) *MockFlowAuthAttemptService {
	mock := &MockFlowAuthAttemptService{ctrl: ctrl}
	mock.recorder = &MockFlowAuthAttemptServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowAuthAttemptService) EXPECT() *MockFlowAuthAttemptServiceMockRecorder {
	return m.recorder
}

// Handoff mocks base method.
func (m *MockFlowAuthAttemptService) Handoff(ctx context.Context, in domain.FlowHandoffInput) (domain.FlowHandoffOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handoff", ctx, in)
	ret0, _ := ret[0].(domain.FlowHandoffOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handoff indicates an expected call of Handoff.
func (mr *MockFlowAuthAttemptServiceMockRecorder) Handoff(ctx, in any) *MockFlowAuthAttemptServiceHandoffCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handoff", reflect.TypeOf((*MockFlowAuthAttemptService)(nil).Handoff), ctx, in)
	return &MockFlowAuthAttemptServiceHandoffCall{Call: call}
}

// MockFlowAuthAttemptServiceHandoffCall wrap *gomock.Call
type MockFlowAuthAttemptServiceHandoffCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowAuthAttemptServiceHandoffCall) Return(arg0 domain.FlowHandoffOutput, arg1 error) *MockFlowAuthAttemptServiceHandoffCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowAuthAttemptServiceHandoffCall) Do(f func(context.Context, domain.FlowHandoffInput) (domain.FlowHandoffOutput, error)) *MockFlowAuthAttemptServiceHandoffCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowAuthAttemptServiceHandoffCall) DoAndReturn(f func(context.Context, domain.FlowHandoffInput) (domain.FlowHandoffOutput, error)) *MockFlowAuthAttemptServiceHandoffCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IssuePasskeyChallenge mocks base method.
func (m *MockFlowAuthAttemptService) IssuePasskeyChallenge(ctx context.Context, in domain.FlowIssuePasskeyChallengeInput) (domain.FlowPasskeyChallengeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssuePasskeyChallenge", ctx, in)
	ret0, _ := ret[0].(domain.FlowPasskeyChallengeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssuePasskeyChallenge indicates an expected call of IssuePasskeyChallenge.
func (mr *MockFlowAuthAttemptServiceMockRecorder) IssuePasskeyChallenge(ctx, in any) *MockFlowAuthAttemptServiceIssuePasskeyChallengeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssuePasskeyChallenge", reflect.TypeOf((*MockFlowAuthAttemptService)(nil).IssuePasskeyChallenge), ctx, in)
	return &MockFlowAuthAttemptServiceIssuePasskeyChallengeCall{Call: call}
}

// MockFlowAuthAttemptServiceIssuePasskeyChallengeCall wrap *gomock.Call
type MockFlowAuthAttemptServiceIssuePasskeyChallengeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowAuthAttemptServiceIssuePasskeyChallengeCall) Return(arg0 domain.FlowPasskeyChallengeOutput, arg1 error) *MockFlowAuthAttemptServiceIssuePasskeyChallengeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowAuthAttemptServiceIssuePasskeyChallengeCall) Do(f func(context.Context, domain.FlowIssuePasskeyChallengeInput) (domain.FlowPasskeyChallengeOutput, error)) *MockFlowAuthAttemptServiceIssuePasskeyChallengeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowAuthAttemptServiceIssuePasskeyChallengeCall) DoAndReturn(f func(context.Context, domain.FlowIssuePasskeyChallengeInput) (domain.FlowPasskeyChallengeOutput, error)) *MockFlowAuthAttemptServiceIssuePasskeyChallengeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RegisterCreatedUser mocks base method.
func (m *MockFlowAuthAttemptService) RegisterCreatedUser(ctx context.Context, in domain.FlowRegisterCreatedUserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterCreatedUser", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterCreatedUser indicates an expected call of RegisterCreatedUser.
func (mr *MockFlowAuthAttemptServiceMockRecorder) RegisterCreatedUser(ctx, in any) *MockFlowAuthAttemptServiceRegisterCreatedUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCreatedUser", reflect.TypeOf((*MockFlowAuthAttemptService)(nil).RegisterCreatedUser), ctx, in)
	return &MockFlowAuthAttemptServiceRegisterCreatedUserCall{Call: call}
}

// MockFlowAuthAttemptServiceRegisterCreatedUserCall wrap *gomock.Call
type MockFlowAuthAttemptServiceRegisterCreatedUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowAuthAttemptServiceRegisterCreatedUserCall) Return(arg0 error) *MockFlowAuthAttemptServiceRegisterCreatedUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowAuthAttemptServiceRegisterCreatedUserCall) Do(f func(context.Context, domain.FlowRegisterCreatedUserInput) error) *MockFlowAuthAttemptServiceRegisterCreatedUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowAuthAttemptServiceRegisterCreatedUserCall) DoAndReturn(f func(context.Context, domain.FlowRegisterCreatedUserInput) error) *MockFlowAuthAttemptServiceRegisterCreatedUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Start mocks base method.
func (m *MockFlowAuthAttemptService) Start(ctx context.Context, in domain.FlowCreateAttemptInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, in)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockFlowAuthAttemptServiceMockRecorder) Start(ctx, in any) *MockFlowAuthAttemptServiceStartCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockFlowAuthAttemptService)(nil).Start), ctx, in)
	return &MockFlowAuthAttemptServiceStartCall{Call: call}
}

// MockFlowAuthAttemptServiceStartCall wrap *gomock.Call
type MockFlowAuthAttemptServiceStartCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowAuthAttemptServiceStartCall) Return(attemptID string, err error) *MockFlowAuthAttemptServiceStartCall {
	c.Call = c.Call.Return(attemptID, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowAuthAttemptServiceStartCall) Do(f func(context.Context, domain.FlowCreateAttemptInput) (string, error)) *MockFlowAuthAttemptServiceStartCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowAuthAttemptServiceStartCall) DoAndReturn(f func(context.Context, domain.FlowCreateAttemptInput) (string, error)) *MockFlowAuthAttemptServiceStartCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubmitIdentifier mocks base method.
func (m *MockFlowAuthAttemptService) SubmitIdentifier(ctx context.Context, in domain.FlowSubmitIdentifierInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitIdentifier", ctx, in)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitIdentifier indicates an expected call of SubmitIdentifier.
func (mr *MockFlowAuthAttemptServiceMockRecorder) SubmitIdentifier(ctx, in any) *MockFlowAuthAttemptServiceSubmitIdentifierCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitIdentifier", reflect.TypeOf((*MockFlowAuthAttemptService)(nil).SubmitIdentifier), ctx, in)
	return &MockFlowAuthAttemptServiceSubmitIdentifierCall{Call: call}
}

// MockFlowAuthAttemptServiceSubmitIdentifierCall wrap *gomock.Call
type MockFlowAuthAttemptServiceSubmitIdentifierCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowAuthAttemptServiceSubmitIdentifierCall) Return(userID string, err error) *MockFlowAuthAttemptServiceSubmitIdentifierCall {
	c.Call = c.Call.Return(userID, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowAuthAttemptServiceSubmitIdentifierCall) Do(f func(context.Context, domain.FlowSubmitIdentifierInput) (string, error)) *MockFlowAuthAttemptServiceSubmitIdentifierCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowAuthAttemptServiceSubmitIdentifierCall) DoAndReturn(f func(context.Context, domain.FlowSubmitIdentifierInput) (string, error)) *MockFlowAuthAttemptServiceSubmitIdentifierCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubmitPasskey mocks base method.
func (m *MockFlowAuthAttemptService) SubmitPasskey(ctx context.Context, in domain.FlowSubmitPasskeyInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitPasskey", ctx, in)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitPasskey indicates an expected call of SubmitPasskey.
func (mr *MockFlowAuthAttemptServiceMockRecorder) SubmitPasskey(ctx, in any) *MockFlowAuthAttemptServiceSubmitPasskeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitPasskey", reflect.TypeOf((*MockFlowAuthAttemptService)(nil).SubmitPasskey), ctx, in)
	return &MockFlowAuthAttemptServiceSubmitPasskeyCall{Call: call}
}

// MockFlowAuthAttemptServiceSubmitPasskeyCall wrap *gomock.Call
type MockFlowAuthAttemptServiceSubmitPasskeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowAuthAttemptServiceSubmitPasskeyCall) Return(userID string, err error) *MockFlowAuthAttemptServiceSubmitPasskeyCall {
	c.Call = c.Call.Return(userID, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowAuthAttemptServiceSubmitPasskeyCall) Do(f func(context.Context, domain.FlowSubmitPasskeyInput) (string, error)) *MockFlowAuthAttemptServiceSubmitPasskeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowAuthAttemptServiceSubmitPasskeyCall) DoAndReturn(f func(context.Context, domain.FlowSubmitPasskeyInput) (string, error)) *MockFlowAuthAttemptServiceSubmitPasskeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubmitPassword mocks base method.
func (m *MockFlowAuthAttemptService) SubmitPassword(ctx context.Context, in domain.FlowSubmitPasswordInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitPassword", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitPassword indicates an expected call of SubmitPassword.
func (mr *MockFlowAuthAttemptServiceMockRecorder) SubmitPassword(ctx, in any) *MockFlowAuthAttemptServiceSubmitPasswordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitPassword", reflect.TypeOf((*MockFlowAuthAttemptService)(nil).SubmitPassword), ctx, in)
	return &MockFlowAuthAttemptServiceSubmitPasswordCall{Call: call}
}

// MockFlowAuthAttemptServiceSubmitPasswordCall wrap *gomock.Call
type MockFlowAuthAttemptServiceSubmitPasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowAuthAttemptServiceSubmitPasswordCall) Return(arg0 error) *MockFlowAuthAttemptServiceSubmitPasswordCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowAuthAttemptServiceSubmitPasswordCall) Do(f func(context.Context, domain.FlowSubmitPasswordInput) error) *MockFlowAuthAttemptServiceSubmitPasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowAuthAttemptServiceSubmitPasswordCall) DoAndReturn(f func(context.Context, domain.FlowSubmitPasswordInput) error) *MockFlowAuthAttemptServiceSubmitPasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
