// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/nextgen/internal/domain (interfaces: FlowFieldResolver)
//
// Generated by this command:
//
//	mockgen -typed -package domainmock -destination ./mock/flow_field_resolver.mock.go . FlowFieldResolver
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	reflect "reflect"

	jsonschema "github.com/ianlancetaylor/jsonschema"
	domain "github.com/zitadel/nextgen/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFlowFieldResolver is a mock of FlowFieldResolver interface.
type MockFlowFieldResolver struct {
	ctrl     *gomock.Controller
	recorder *MockFlowFieldResolverMockRecorder
	isgomock struct{}
}

// MockFlowFieldResolverMockRecorder is the mock recorder for MockFlowFieldResolver.
type MockFlowFieldResolverMockRecorder struct {
	mock *MockFlowFieldResolver
}

// NewMockFlowFieldResolver creates a new mock instance.
func NewMockFlowFieldResolver(ctrl *gomock.Controller) *MockFlowFieldResolver {
	mock := &MockFlowFieldResolver{ctrl: ctrl}
	mock.recorder = &MockFlowFieldResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowFieldResolver) EXPECT() *MockFlowFieldResolverMockRecorder {
	return m.recorder
}

// MissingRequired mocks base method.
func (m *MockFlowFieldResolver) MissingRequired(fields domain.FlowResolvedFields, values map[string]any) domain.FlowFieldValidationErrors {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MissingRequired", fields, values)
	ret0, _ := ret[0].(domain.FlowFieldValidationErrors)
	return ret0
}

// MissingRequired indicates an expected call of MissingRequired.
func (mr *MockFlowFieldResolverMockRecorder) MissingRequired(fields, values any) *MockFlowFieldResolverMissingRequiredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MissingRequired", reflect.TypeOf((*MockFlowFieldResolver)(nil).MissingRequired), fields, values)
	return &MockFlowFieldResolverMissingRequiredCall{Call: call}
}

// MockFlowFieldResolverMissingRequiredCall wrap *gomock.Call
type MockFlowFieldResolverMissingRequiredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowFieldResolverMissingRequiredCall) Return(arg0 domain.FlowFieldValidationErrors) *MockFlowFieldResolverMissingRequiredCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowFieldResolverMissingRequiredCall) Do(f func(domain.FlowResolvedFields, map[string]any) domain.FlowFieldValidationErrors) *MockFlowFieldResolverMissingRequiredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowFieldResolverMissingRequiredCall) DoAndReturn(f func(domain.FlowResolvedFields, map[string]any) domain.FlowFieldValidationErrors) *MockFlowFieldResolverMissingRequiredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Resolve mocks base method.
func (m *MockFlowFieldResolver) Resolve(schema *jsonschema.Schema, stepName string, fields []domain.Field) (domain.FlowResolvedFields, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", schema, stepName, fields)
	ret0, _ := ret[0].(domain.FlowResolvedFields)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockFlowFieldResolverMockRecorder) Resolve(schema, stepName, fields any) *MockFlowFieldResolverResolveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockFlowFieldResolver)(nil).Resolve), schema, stepName, fields)
	return &MockFlowFieldResolverResolveCall{Call: call}
}

// MockFlowFieldResolverResolveCall wrap *gomock.Call
type MockFlowFieldResolverResolveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowFieldResolverResolveCall) Return(arg0 domain.FlowResolvedFields, arg1 error) *MockFlowFieldResolverResolveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowFieldResolverResolveCall) Do(f func(*jsonschema.Schema, string, []domain.Field) (domain.FlowResolvedFields, error)) *MockFlowFieldResolverResolveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowFieldResolverResolveCall) DoAndReturn(f func(*jsonschema.Schema, string, []domain.Field) (domain.FlowResolvedFields, error)) *MockFlowFieldResolverResolveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Validate mocks base method.
func (m *MockFlowFieldResolver) Validate(fields domain.FlowResolvedFields, values map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", fields, values)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockFlowFieldResolverMockRecorder) Validate(fields, values any) *MockFlowFieldResolverValidateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockFlowFieldResolver)(nil).Validate), fields, values)
	return &MockFlowFieldResolverValidateCall{Call: call}
}

// MockFlowFieldResolverValidateCall wrap *gomock.Call
type MockFlowFieldResolverValidateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowFieldResolverValidateCall) Return(arg0 error) *MockFlowFieldResolverValidateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowFieldResolverValidateCall) Do(f func(domain.FlowResolvedFields, map[string]any) error) *MockFlowFieldResolverValidateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowFieldResolverValidateCall) DoAndReturn(f func(domain.FlowResolvedFields, map[string]any) error) *MockFlowFieldResolverValidateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
