// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/nextgen/internal/domain (interfaces: SchemaResolver)
//
// Generated by this command:
//
//	mockgen -typed -package domainmock -destination ./mock/flow_field_resolver.schema.mock.go . SchemaResolver
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	jsonschema "github.com/ianlancetaylor/jsonschema"
	domain "github.com/zitadel/nextgen/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSchemaResolver is a mock of SchemaResolver interface.
type MockSchemaResolver struct {
	ctrl     *gomock.Controller
	recorder *MockSchemaResolverMockRecorder
	isgomock struct{}
}

// MockSchemaResolverMockRecorder is the mock recorder for MockSchemaResolver.
type MockSchemaResolverMockRecorder struct {
	mock *MockSchemaResolver
}

// NewMockSchemaResolver creates a new mock instance.
func NewMockSchemaResolver(ctrl *gomock.Controller) *MockSchemaResolver {
	mock := &MockSchemaResolver{ctrl: ctrl}
	mock.recorder = &MockSchemaResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchemaResolver) EXPECT() *MockSchemaResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockSchemaResolver) Resolve(ctx context.Context, store domain.JSONSchemaStore, projectID, schemaURL string, rootSchema []byte) (*jsonschema.Schema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, store, projectID, schemaURL, rootSchema)
	ret0, _ := ret[0].(*jsonschema.Schema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockSchemaResolverMockRecorder) Resolve(ctx, store, projectID, schemaURL, rootSchema any) *MockSchemaResolverResolveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockSchemaResolver)(nil).Resolve), ctx, store, projectID, schemaURL, rootSchema)
	return &MockSchemaResolverResolveCall{Call: call}
}

// MockSchemaResolverResolveCall wrap *gomock.Call
type MockSchemaResolverResolveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSchemaResolverResolveCall) Return(arg0 *jsonschema.Schema, arg1 error) *MockSchemaResolverResolveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSchemaResolverResolveCall) Do(f func(context.Context, domain.JSONSchemaStore, string, string, []byte) (*jsonschema.Schema, error)) *MockSchemaResolverResolveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSchemaResolverResolveCall) DoAndReturn(f func(context.Context, domain.JSONSchemaStore, string, string, []byte) (*jsonschema.Schema, error)) *MockSchemaResolverResolveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
