// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/nextgen/internal/domain (interfaces: FlowPasskeyRegistrationService)
//
// Generated by this command:
//
//	mockgen -typed -package domainmock -destination ./mock/flow_passkey_registration.mock.go . FlowPasskeyRegistrationService
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/zitadel/nextgen/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFlowPasskeyRegistrationService is a mock of FlowPasskeyRegistrationService interface.
type MockFlowPasskeyRegistrationService struct {
	ctrl     *gomock.Controller
	recorder *MockFlowPasskeyRegistrationServiceMockRecorder
	isgomock struct{}
}

// MockFlowPasskeyRegistrationServiceMockRecorder is the mock recorder for MockFlowPasskeyRegistrationService.
type MockFlowPasskeyRegistrationServiceMockRecorder struct {
	mock *MockFlowPasskeyRegistrationService
}

// NewMockFlowPasskeyRegistrationService creates a new mock instance.
func NewMockFlowPasskeyRegistrationService(ctrl *gomock.Controller) *MockFlowPasskeyRegistrationService {
	mock := &MockFlowPasskeyRegistrationService{ctrl: ctrl}
	mock.recorder = &MockFlowPasskeyRegistrationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowPasskeyRegistrationService) EXPECT() *MockFlowPasskeyRegistrationServiceMockRecorder {
	return m.recorder
}

// IssuePasskeyRegistrationChallenge mocks base method.
func (m *MockFlowPasskeyRegistrationService) IssuePasskeyRegistrationChallenge(ctx context.Context, in domain.FlowIssuePasskeyRegistrationChallengeInput) (domain.FlowPasskeyRegistrationChallengeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssuePasskeyRegistrationChallenge", ctx, in)
	ret0, _ := ret[0].(domain.FlowPasskeyRegistrationChallengeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssuePasskeyRegistrationChallenge indicates an expected call of IssuePasskeyRegistrationChallenge.
func (mr *MockFlowPasskeyRegistrationServiceMockRecorder) IssuePasskeyRegistrationChallenge(ctx, in any) *MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssuePasskeyRegistrationChallenge", reflect.TypeOf((*MockFlowPasskeyRegistrationService)(nil).IssuePasskeyRegistrationChallenge), ctx, in)
	return &MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall{Call: call}
}

// MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall wrap *gomock.Call
type MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall) Return(arg0 domain.FlowPasskeyRegistrationChallengeOutput, arg1 error) *MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall) Do(f func(context.Context, domain.FlowIssuePasskeyRegistrationChallengeInput) (domain.FlowPasskeyRegistrationChallengeOutput, error)) *MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall) DoAndReturn(f func(context.Context, domain.FlowIssuePasskeyRegistrationChallengeInput) (domain.FlowPasskeyRegistrationChallengeOutput, error)) *MockFlowPasskeyRegistrationServiceIssuePasskeyRegistrationChallengeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SubmitPasskeyRegistration mocks base method.
func (m *MockFlowPasskeyRegistrationService) SubmitPasskeyRegistration(ctx context.Context, in domain.FlowSubmitPasskeyRegistrationInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitPasskeyRegistration", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitPasskeyRegistration indicates an expected call of SubmitPasskeyRegistration.
func (mr *MockFlowPasskeyRegistrationServiceMockRecorder) SubmitPasskeyRegistration(ctx, in any) *MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitPasskeyRegistration", reflect.TypeOf((*MockFlowPasskeyRegistrationService)(nil).SubmitPasskeyRegistration), ctx, in)
	return &MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall{Call: call}
}

// MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall wrap *gomock.Call
type MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall) Return(arg0 error) *MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall) Do(f func(context.Context, domain.FlowSubmitPasskeyRegistrationInput) error) *MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall) DoAndReturn(f func(context.Context, domain.FlowSubmitPasskeyRegistrationInput) error) *MockFlowPasskeyRegistrationServiceSubmitPasskeyRegistrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
