// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/nextgen/internal/domain (interfaces: FlowOnSuccessHandler)
//
// Generated by this command:
//
//	mockgen -typed -package domainmock -destination ./mock/flow_on_success.mock.go . FlowOnSuccessHandler
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/zitadel/nextgen/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFlowOnSuccessHandler is a mock of FlowOnSuccessHandler interface.
type MockFlowOnSuccessHandler struct {
	ctrl     *gomock.Controller
	recorder *MockFlowOnSuccessHandlerMockRecorder
	isgomock struct{}
}

// MockFlowOnSuccessHandlerMockRecorder is the mock recorder for MockFlowOnSuccessHandler.
type MockFlowOnSuccessHandlerMockRecorder struct {
	mock *MockFlowOnSuccessHandler
}

// NewMockFlowOnSuccessHandler creates a new mock instance.
func NewMockFlowOnSuccessHandler(ctrl *gomock.Controller) *MockFlowOnSuccessHandler {
	mock := &MockFlowOnSuccessHandler{ctrl: ctrl}
	mock.recorder = &MockFlowOnSuccessHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowOnSuccessHandler) EXPECT() *MockFlowOnSuccessHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockFlowOnSuccessHandler) Handle(ctx context.Context, in domain.FlowOnSuccessInput) (domain.FlowOnSuccessResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, in)
	ret0, _ := ret[0].(domain.FlowOnSuccessResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockFlowOnSuccessHandlerMockRecorder) Handle(ctx, in any) *MockFlowOnSuccessHandlerHandleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockFlowOnSuccessHandler)(nil).Handle), ctx, in)
	return &MockFlowOnSuccessHandlerHandleCall{Call: call}
}

// MockFlowOnSuccessHandlerHandleCall wrap *gomock.Call
type MockFlowOnSuccessHandlerHandleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowOnSuccessHandlerHandleCall) Return(arg0 domain.FlowOnSuccessResult, arg1 error) *MockFlowOnSuccessHandlerHandleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowOnSuccessHandlerHandleCall) Do(f func(context.Context, domain.FlowOnSuccessInput) (domain.FlowOnSuccessResult, error)) *MockFlowOnSuccessHandlerHandleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowOnSuccessHandlerHandleCall) DoAndReturn(f func(context.Context, domain.FlowOnSuccessInput) (domain.FlowOnSuccessResult, error)) *MockFlowOnSuccessHandlerHandleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
