// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/nextgen/internal/domain (interfaces: JSONSchemaRepository)
//
// Generated by this command:
//
//	mockgen -typed -package domainmock -destination ./mock/json_schema.mock.go . JSONSchemaRepository
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"

	domain "github.com/zitadel/nextgen/internal/domain"
	database "github.com/zitadel/nextgen/internal/storage/database"
	gomock "go.uber.org/mock/gomock"
)

// MockJSONSchemaRepository is a mock of JSONSchemaRepository interface.
type MockJSONSchemaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJSONSchemaRepositoryMockRecorder
	isgomock struct{}
}

// MockJSONSchemaRepositoryMockRecorder is the mock recorder for MockJSONSchemaRepository.
type MockJSONSchemaRepositoryMockRecorder struct {
	mock *MockJSONSchemaRepository
}

// NewMockJSONSchemaRepository creates a new mock instance.
func NewMockJSONSchemaRepository(ctrl *gomock.Controller) *MockJSONSchemaRepository {
	mock := &MockJSONSchemaRepository{ctrl: ctrl}
	mock.recorder = &MockJSONSchemaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJSONSchemaRepository) EXPECT() *MockJSONSchemaRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockJSONSchemaRepository) Create(ctx context.Context, client database.QueryExecutor, schema *domain.JSONSchema) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, client, schema)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockJSONSchemaRepositoryMockRecorder) Create(ctx, client, schema any) *MockJSONSchemaRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJSONSchemaRepository)(nil).Create), ctx, client, schema)
	return &MockJSONSchemaRepositoryCreateCall{Call: call}
}

// MockJSONSchemaRepositoryCreateCall wrap *gomock.Call
type MockJSONSchemaRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaRepositoryCreateCall) Return(arg0 error) *MockJSONSchemaRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaRepositoryCreateCall) Do(f func(context.Context, database.QueryExecutor, *domain.JSONSchema) error) *MockJSONSchemaRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaRepositoryCreateCall) DoAndReturn(f func(context.Context, database.QueryExecutor, *domain.JSONSchema) error) *MockJSONSchemaRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreatedAt mocks base method.
func (m *MockJSONSchemaRepository) CreatedAt() database.Column {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatedAt")
	ret0, _ := ret[0].(database.Column)
	return ret0
}

// CreatedAt indicates an expected call of CreatedAt.
func (mr *MockJSONSchemaRepositoryMockRecorder) CreatedAt() *MockJSONSchemaRepositoryCreatedAtCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatedAt", reflect.TypeOf((*MockJSONSchemaRepository)(nil).CreatedAt))
	return &MockJSONSchemaRepositoryCreatedAtCall{Call: call}
}

// MockJSONSchemaRepositoryCreatedAtCall wrap *gomock.Call
type MockJSONSchemaRepositoryCreatedAtCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaRepositoryCreatedAtCall) Return(arg0 database.Column) *MockJSONSchemaRepositoryCreatedAtCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaRepositoryCreatedAtCall) Do(f func() database.Column) *MockJSONSchemaRepositoryCreatedAtCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaRepositoryCreatedAtCall) DoAndReturn(f func() database.Column) *MockJSONSchemaRepositoryCreatedAtCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockJSONSchemaRepository) Delete(ctx context.Context, client database.QueryExecutor, condition database.Condition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, client, condition)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockJSONSchemaRepositoryMockRecorder) Delete(ctx, client, condition any) *MockJSONSchemaRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockJSONSchemaRepository)(nil).Delete), ctx, client, condition)
	return &MockJSONSchemaRepositoryDeleteCall{Call: call}
}

// MockJSONSchemaRepositoryDeleteCall wrap *gomock.Call
type MockJSONSchemaRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaRepositoryDeleteCall) Return(arg0 error) *MockJSONSchemaRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaRepositoryDeleteCall) Do(f func(context.Context, database.QueryExecutor, database.Condition) error) *MockJSONSchemaRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaRepositoryDeleteCall) DoAndReturn(f func(context.Context, database.QueryExecutor, database.Condition) error) *MockJSONSchemaRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockJSONSchemaRepository) Get(ctx context.Context, client database.QueryExecutor, opts ...database.QueryOption) (*domain.JSONSchema, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, client}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*domain.JSONSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockJSONSchemaRepositoryMockRecorder) Get(ctx, client any, opts ...any) *MockJSONSchemaRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, client}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockJSONSchemaRepository)(nil).Get), varargs...)
	return &MockJSONSchemaRepositoryGetCall{Call: call}
}

// MockJSONSchemaRepositoryGetCall wrap *gomock.Call
type MockJSONSchemaRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaRepositoryGetCall) Return(arg0 *domain.JSONSchema, arg1 error) *MockJSONSchemaRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaRepositoryGetCall) Do(f func(context.Context, database.QueryExecutor, ...database.QueryOption) (*domain.JSONSchema, error)) *MockJSONSchemaRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaRepositoryGetCall) DoAndReturn(f func(context.Context, database.QueryExecutor, ...database.QueryOption) (*domain.JSONSchema, error)) *MockJSONSchemaRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockJSONSchemaRepository) GetByID(ctx context.Context, client database.QueryExecutor, projectID, schemaID string) (*domain.JSONSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, client, projectID, schemaID)
	ret0, _ := ret[0].(*domain.JSONSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockJSONSchemaRepositoryMockRecorder) GetByID(ctx, client, projectID, schemaID any) *MockJSONSchemaRepositoryGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockJSONSchemaRepository)(nil).GetByID), ctx, client, projectID, schemaID)
	return &MockJSONSchemaRepositoryGetByIDCall{Call: call}
}

// MockJSONSchemaRepositoryGetByIDCall wrap *gomock.Call
type MockJSONSchemaRepositoryGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaRepositoryGetByIDCall) Return(arg0 *domain.JSONSchema, arg1 error) *MockJSONSchemaRepositoryGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaRepositoryGetByIDCall) Do(f func(context.Context, database.QueryExecutor, string, string) (*domain.JSONSchema, error)) *MockJSONSchemaRepositoryGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaRepositoryGetByIDCall) DoAndReturn(f func(context.Context, database.QueryExecutor, string, string) (*domain.JSONSchema, error)) *MockJSONSchemaRepositoryGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockJSONSchemaRepository) List(ctx context.Context, client database.QueryExecutor, opts ...database.QueryOption) ([]*domain.JSONSchema, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, client}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*domain.JSONSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockJSONSchemaRepositoryMockRecorder) List(ctx, client any, opts ...any) *MockJSONSchemaRepositoryListCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, client}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockJSONSchemaRepository)(nil).List), varargs...)
	return &MockJSONSchemaRepositoryListCall{Call: call}
}

// MockJSONSchemaRepositoryListCall wrap *gomock.Call
type MockJSONSchemaRepositoryListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaRepositoryListCall) Return(arg0 []*domain.JSONSchema, arg1 error) *MockJSONSchemaRepositoryListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaRepositoryListCall) Do(f func(context.Context, database.QueryExecutor, ...database.QueryOption) ([]*domain.JSONSchema, error)) *MockJSONSchemaRepositoryListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaRepositoryListCall) DoAndReturn(f func(context.Context, database.QueryExecutor, ...database.QueryOption) ([]*domain.JSONSchema, error)) *MockJSONSchemaRepositoryListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Payload mocks base method.
func (m *MockJSONSchemaRepository) Payload() database.Column {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Payload")
	ret0, _ := ret[0].(database.Column)
	return ret0
}

// Payload indicates an expected call of Payload.
func (mr *MockJSONSchemaRepositoryMockRecorder) Payload() *MockJSONSchemaRepositoryPayloadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Payload", reflect.TypeOf((*MockJSONSchemaRepository)(nil).Payload))
	return &MockJSONSchemaRepositoryPayloadCall{Call: call}
}

// MockJSONSchemaRepositoryPayloadCall wrap *gomock.Call
type MockJSONSchemaRepositoryPayloadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaRepositoryPayloadCall) Return(arg0 database.Column) *MockJSONSchemaRepositoryPayloadCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaRepositoryPayloadCall) Do(f func() database.Column) *MockJSONSchemaRepositoryPayloadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaRepositoryPayloadCall) DoAndReturn(f func() database.Column) *MockJSONSchemaRepositoryPayloadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PayloadTextCondition mocks base method.
func (m *MockJSONSchemaRepository) PayloadTextCondition(op database.TextOperation, value string, path ...string) database.Condition {
	m.ctrl.T.Helper()
	varargs := []any{op, value}
	for _, a := range path {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PayloadTextCondition", varargs...)
	ret0, _ := ret[0].(database.Condition)
	return ret0
}

// PayloadTextCondition indicates an expected call of PayloadTextCondition.
func (mr *MockJSONSchemaRepositoryMockRecorder) PayloadTextCondition(op, value any, path ...any) *MockJSONSchemaRepositoryPayloadTextConditionCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{op, value}, path...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PayloadTextCondition", reflect.TypeOf((*MockJSONSchemaRepository)(nil).PayloadTextCondition), varargs...)
	return &MockJSONSchemaRepositoryPayloadTextConditionCall{Call: call}
}

// MockJSONSchemaRepositoryPayloadTextConditionCall wrap *gomock.Call
type MockJSONSchemaRepositoryPayloadTextConditionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaRepositoryPayloadTextConditionCall) Return(arg0 database.Condition) *MockJSONSchemaRepositoryPayloadTextConditionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaRepositoryPayloadTextConditionCall) Do(f func(database.TextOperation, string, ...string) database.Condition) *MockJSONSchemaRepositoryPayloadTextConditionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaRepositoryPayloadTextConditionCall) DoAndReturn(f func(database.TextOperation, string, ...string) database.Condition) *MockJSONSchemaRepositoryPayloadTextConditionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PrimaryKeyColumns mocks base method.
func (m *MockJSONSchemaRepository) PrimaryKeyColumns() []database.Column {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrimaryKeyColumns")
	ret0, _ := ret[0].([]database.Column)
	return ret0
}

// PrimaryKeyColumns indicates an expected call of PrimaryKeyColumns.
func (mr *MockJSONSchemaRepositoryMockRecorder) PrimaryKeyColumns() *MockJSONSchemaRepositoryPrimaryKeyColumnsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrimaryKeyColumns", reflect.TypeOf((*MockJSONSchemaRepository)(nil).PrimaryKeyColumns))
	return &MockJSONSchemaRepositoryPrimaryKeyColumnsCall{Call: call}
}

// MockJSONSchemaRepositoryPrimaryKeyColumnsCall wrap *gomock.Call
type MockJSONSchemaRepositoryPrimaryKeyColumnsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaRepositoryPrimaryKeyColumnsCall) Return(arg0 []database.Column) *MockJSONSchemaRepositoryPrimaryKeyColumnsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaRepositoryPrimaryKeyColumnsCall) Do(f func() []database.Column) *MockJSONSchemaRepositoryPrimaryKeyColumnsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaRepositoryPrimaryKeyColumnsCall) DoAndReturn(f func() []database.Column) *MockJSONSchemaRepositoryPrimaryKeyColumnsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PrimaryKeyCondition mocks base method.
func (m *MockJSONSchemaRepository) PrimaryKeyCondition(projectID, url string) database.Condition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrimaryKeyCondition", projectID, url)
	ret0, _ := ret[0].(database.Condition)
	return ret0
}

// PrimaryKeyCondition indicates an expected call of PrimaryKeyCondition.
func (mr *MockJSONSchemaRepositoryMockRecorder) PrimaryKeyCondition(projectID, url any) *MockJSONSchemaRepositoryPrimaryKeyConditionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrimaryKeyCondition", reflect.TypeOf((*MockJSONSchemaRepository)(nil).PrimaryKeyCondition), projectID, url)
	return &MockJSONSchemaRepositoryPrimaryKeyConditionCall{Call: call}
}

// MockJSONSchemaRepositoryPrimaryKeyConditionCall wrap *gomock.Call
type MockJSONSchemaRepositoryPrimaryKeyConditionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaRepositoryPrimaryKeyConditionCall) Return(arg0 database.Condition) *MockJSONSchemaRepositoryPrimaryKeyConditionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaRepositoryPrimaryKeyConditionCall) Do(f func(string, string) database.Condition) *MockJSONSchemaRepositoryPrimaryKeyConditionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaRepositoryPrimaryKeyConditionCall) DoAndReturn(f func(string, string) database.Condition) *MockJSONSchemaRepositoryPrimaryKeyConditionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProjectID mocks base method.
func (m *MockJSONSchemaRepository) ProjectID() database.Column {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectID")
	ret0, _ := ret[0].(database.Column)
	return ret0
}

// ProjectID indicates an expected call of ProjectID.
func (mr *MockJSONSchemaRepositoryMockRecorder) ProjectID() *MockJSONSchemaRepositoryProjectIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectID", reflect.TypeOf((*MockJSONSchemaRepository)(nil).ProjectID))
	return &MockJSONSchemaRepositoryProjectIDCall{Call: call}
}

// MockJSONSchemaRepositoryProjectIDCall wrap *gomock.Call
type MockJSONSchemaRepositoryProjectIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaRepositoryProjectIDCall) Return(arg0 database.Column) *MockJSONSchemaRepositoryProjectIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaRepositoryProjectIDCall) Do(f func() database.Column) *MockJSONSchemaRepositoryProjectIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaRepositoryProjectIDCall) DoAndReturn(f func() database.Column) *MockJSONSchemaRepositoryProjectIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProjectIDCondition mocks base method.
func (m *MockJSONSchemaRepository) ProjectIDCondition(projectID string) database.Condition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectIDCondition", projectID)
	ret0, _ := ret[0].(database.Condition)
	return ret0
}

// ProjectIDCondition indicates an expected call of ProjectIDCondition.
func (mr *MockJSONSchemaRepositoryMockRecorder) ProjectIDCondition(projectID any) *MockJSONSchemaRepositoryProjectIDConditionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectIDCondition", reflect.TypeOf((*MockJSONSchemaRepository)(nil).ProjectIDCondition), projectID)
	return &MockJSONSchemaRepositoryProjectIDConditionCall{Call: call}
}

// MockJSONSchemaRepositoryProjectIDConditionCall wrap *gomock.Call
type MockJSONSchemaRepositoryProjectIDConditionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaRepositoryProjectIDConditionCall) Return(arg0 database.Condition) *MockJSONSchemaRepositoryProjectIDConditionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaRepositoryProjectIDConditionCall) Do(f func(string) database.Condition) *MockJSONSchemaRepositoryProjectIDConditionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaRepositoryProjectIDConditionCall) DoAndReturn(f func(string) database.Condition) *MockJSONSchemaRepositoryProjectIDConditionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// URL mocks base method.
func (m *MockJSONSchemaRepository) URL() database.Column {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URL")
	ret0, _ := ret[0].(database.Column)
	return ret0
}

// URL indicates an expected call of URL.
func (mr *MockJSONSchemaRepositoryMockRecorder) URL() *MockJSONSchemaRepositoryURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URL", reflect.TypeOf((*MockJSONSchemaRepository)(nil).URL))
	return &MockJSONSchemaRepositoryURLCall{Call: call}
}

// MockJSONSchemaRepositoryURLCall wrap *gomock.Call
type MockJSONSchemaRepositoryURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaRepositoryURLCall) Return(arg0 database.Column) *MockJSONSchemaRepositoryURLCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaRepositoryURLCall) Do(f func() database.Column) *MockJSONSchemaRepositoryURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaRepositoryURLCall) DoAndReturn(f func() database.Column) *MockJSONSchemaRepositoryURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// URLCondition mocks base method.
func (m *MockJSONSchemaRepository) URLCondition(url string) database.Condition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URLCondition", url)
	ret0, _ := ret[0].(database.Condition)
	return ret0
}

// URLCondition indicates an expected call of URLCondition.
func (mr *MockJSONSchemaRepositoryMockRecorder) URLCondition(url any) *MockJSONSchemaRepositoryURLConditionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URLCondition", reflect.TypeOf((*MockJSONSchemaRepository)(nil).URLCondition), url)
	return &MockJSONSchemaRepositoryURLConditionCall{Call: call}
}

// MockJSONSchemaRepositoryURLConditionCall wrap *gomock.Call
type MockJSONSchemaRepositoryURLConditionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaRepositoryURLConditionCall) Return(arg0 database.Condition) *MockJSONSchemaRepositoryURLConditionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaRepositoryURLConditionCall) Do(f func(string) database.Condition) *MockJSONSchemaRepositoryURLConditionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaRepositoryURLConditionCall) DoAndReturn(f func(string) database.Condition) *MockJSONSchemaRepositoryURLConditionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
