// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/nextgen/internal/domain (interfaces: UserPasswordRepository)
//
// Generated by this command:
//
//	mockgen -typed -package domainmock -destination ./mock/user_password.mock.go . UserPasswordRepository
//

// Package domainmock is a generated GoMock package.
package domainmock

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/zitadel/nextgen/internal/domain"
	database "github.com/zitadel/nextgen/internal/storage/database"
	gomock "go.uber.org/mock/gomock"
)

// MockUserPasswordRepository is a mock of UserPasswordRepository interface.
type MockUserPasswordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserPasswordRepositoryMockRecorder
	isgomock struct{}
}

// MockUserPasswordRepositoryMockRecorder is the mock recorder for MockUserPasswordRepository.
type MockUserPasswordRepositoryMockRecorder struct {
	mock *MockUserPasswordRepository
}

// NewMockUserPasswordRepository creates a new mock instance.
func NewMockUserPasswordRepository(ctrl *gomock.Controller) *MockUserPasswordRepository {
	mock := &MockUserPasswordRepository{ctrl: ctrl}
	mock.recorder = &MockUserPasswordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPasswordRepository) EXPECT() *MockUserPasswordRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserPasswordRepository) Create(ctx context.Context, client database.QueryExecutor, user *domain.CreateUserPassword) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, client, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserPasswordRepositoryMockRecorder) Create(ctx, client, user any) *MockUserPasswordRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserPasswordRepository)(nil).Create), ctx, client, user)
	return &MockUserPasswordRepositoryCreateCall{Call: call}
}

// MockUserPasswordRepositoryCreateCall wrap *gomock.Call
type MockUserPasswordRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositoryCreateCall) Return(arg0 error) *MockUserPasswordRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositoryCreateCall) Do(f func(context.Context, database.QueryExecutor, *domain.CreateUserPassword) error) *MockUserPasswordRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositoryCreateCall) DoAndReturn(f func(context.Context, database.QueryExecutor, *domain.CreateUserPassword) error) *MockUserPasswordRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockUserPasswordRepository) Delete(ctx context.Context, client database.QueryExecutor, condition database.Condition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, client, condition)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserPasswordRepositoryMockRecorder) Delete(ctx, client, condition any) *MockUserPasswordRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserPasswordRepository)(nil).Delete), ctx, client, condition)
	return &MockUserPasswordRepositoryDeleteCall{Call: call}
}

// MockUserPasswordRepositoryDeleteCall wrap *gomock.Call
type MockUserPasswordRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositoryDeleteCall) Return(arg0 error) *MockUserPasswordRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositoryDeleteCall) Do(f func(context.Context, database.QueryExecutor, database.Condition) error) *MockUserPasswordRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositoryDeleteCall) DoAndReturn(f func(context.Context, database.QueryExecutor, database.Condition) error) *MockUserPasswordRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteByUserID mocks base method.
func (m *MockUserPasswordRepository) DeleteByUserID(ctx context.Context, client database.QueryExecutor, projectID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, client, projectID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockUserPasswordRepositoryMockRecorder) DeleteByUserID(ctx, client, projectID, userID any) *MockUserPasswordRepositoryDeleteByUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockUserPasswordRepository)(nil).DeleteByUserID), ctx, client, projectID, userID)
	return &MockUserPasswordRepositoryDeleteByUserIDCall{Call: call}
}

// MockUserPasswordRepositoryDeleteByUserIDCall wrap *gomock.Call
type MockUserPasswordRepositoryDeleteByUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositoryDeleteByUserIDCall) Return(arg0 error) *MockUserPasswordRepositoryDeleteByUserIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositoryDeleteByUserIDCall) Do(f func(context.Context, database.QueryExecutor, string, string) error) *MockUserPasswordRepositoryDeleteByUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositoryDeleteByUserIDCall) DoAndReturn(f func(context.Context, database.QueryExecutor, string, string) error) *MockUserPasswordRepositoryDeleteByUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockUserPasswordRepository) Get(ctx context.Context, client database.QueryExecutor, opts ...database.QueryOption) (*domain.UserPassword, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, client}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*domain.UserPassword)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserPasswordRepositoryMockRecorder) Get(ctx, client any, opts ...any) *MockUserPasswordRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, client}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserPasswordRepository)(nil).Get), varargs...)
	return &MockUserPasswordRepositoryGetCall{Call: call}
}

// MockUserPasswordRepositoryGetCall wrap *gomock.Call
type MockUserPasswordRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositoryGetCall) Return(arg0 *domain.UserPassword, arg1 error) *MockUserPasswordRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositoryGetCall) Do(f func(context.Context, database.QueryExecutor, ...database.QueryOption) (*domain.UserPassword, error)) *MockUserPasswordRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositoryGetCall) DoAndReturn(f func(context.Context, database.QueryExecutor, ...database.QueryOption) (*domain.UserPassword, error)) *MockUserPasswordRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByUserID mocks base method.
func (m *MockUserPasswordRepository) GetByUserID(ctx context.Context, client database.QueryExecutor, projectID, userID string) (*domain.UserPassword, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, client, projectID, userID)
	ret0, _ := ret[0].(*domain.UserPassword)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserPasswordRepositoryMockRecorder) GetByUserID(ctx, client, projectID, userID any) *MockUserPasswordRepositoryGetByUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserPasswordRepository)(nil).GetByUserID), ctx, client, projectID, userID)
	return &MockUserPasswordRepositoryGetByUserIDCall{Call: call}
}

// MockUserPasswordRepositoryGetByUserIDCall wrap *gomock.Call
type MockUserPasswordRepositoryGetByUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositoryGetByUserIDCall) Return(arg0 *domain.UserPassword, arg1 error) *MockUserPasswordRepositoryGetByUserIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositoryGetByUserIDCall) Do(f func(context.Context, database.QueryExecutor, string, string) (*domain.UserPassword, error)) *MockUserPasswordRepositoryGetByUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositoryGetByUserIDCall) DoAndReturn(f func(context.Context, database.QueryExecutor, string, string) (*domain.UserPassword, error)) *MockUserPasswordRepositoryGetByUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IncrementFailedAttempts mocks base method.
func (m *MockUserPasswordRepository) IncrementFailedAttempts() database.Change {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementFailedAttempts")
	ret0, _ := ret[0].(database.Change)
	return ret0
}

// IncrementFailedAttempts indicates an expected call of IncrementFailedAttempts.
func (mr *MockUserPasswordRepositoryMockRecorder) IncrementFailedAttempts() *MockUserPasswordRepositoryIncrementFailedAttemptsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementFailedAttempts", reflect.TypeOf((*MockUserPasswordRepository)(nil).IncrementFailedAttempts))
	return &MockUserPasswordRepositoryIncrementFailedAttemptsCall{Call: call}
}

// MockUserPasswordRepositoryIncrementFailedAttemptsCall wrap *gomock.Call
type MockUserPasswordRepositoryIncrementFailedAttemptsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositoryIncrementFailedAttemptsCall) Return(arg0 database.Change) *MockUserPasswordRepositoryIncrementFailedAttemptsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositoryIncrementFailedAttemptsCall) Do(f func() database.Change) *MockUserPasswordRepositoryIncrementFailedAttemptsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositoryIncrementFailedAttemptsCall) DoAndReturn(f func() database.Change) *MockUserPasswordRepositoryIncrementFailedAttemptsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockUserPasswordRepository) List(ctx context.Context, client database.QueryExecutor, opts ...database.QueryOption) ([]*domain.UserPassword, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, client}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*domain.UserPassword)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserPasswordRepositoryMockRecorder) List(ctx, client any, opts ...any) *MockUserPasswordRepositoryListCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, client}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserPasswordRepository)(nil).List), varargs...)
	return &MockUserPasswordRepositoryListCall{Call: call}
}

// MockUserPasswordRepositoryListCall wrap *gomock.Call
type MockUserPasswordRepositoryListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositoryListCall) Return(arg0 []*domain.UserPassword, arg1 error) *MockUserPasswordRepositoryListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositoryListCall) Do(f func(context.Context, database.QueryExecutor, ...database.QueryOption) ([]*domain.UserPassword, error)) *MockUserPasswordRepositoryListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositoryListCall) DoAndReturn(f func(context.Context, database.QueryExecutor, ...database.QueryOption) ([]*domain.UserPassword, error)) *MockUserPasswordRepositoryListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PrimaryKeyColumns mocks base method.
func (m *MockUserPasswordRepository) PrimaryKeyColumns() []database.Column {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrimaryKeyColumns")
	ret0, _ := ret[0].([]database.Column)
	return ret0
}

// PrimaryKeyColumns indicates an expected call of PrimaryKeyColumns.
func (mr *MockUserPasswordRepositoryMockRecorder) PrimaryKeyColumns() *MockUserPasswordRepositoryPrimaryKeyColumnsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrimaryKeyColumns", reflect.TypeOf((*MockUserPasswordRepository)(nil).PrimaryKeyColumns))
	return &MockUserPasswordRepositoryPrimaryKeyColumnsCall{Call: call}
}

// MockUserPasswordRepositoryPrimaryKeyColumnsCall wrap *gomock.Call
type MockUserPasswordRepositoryPrimaryKeyColumnsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositoryPrimaryKeyColumnsCall) Return(arg0 []database.Column) *MockUserPasswordRepositoryPrimaryKeyColumnsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositoryPrimaryKeyColumnsCall) Do(f func() []database.Column) *MockUserPasswordRepositoryPrimaryKeyColumnsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositoryPrimaryKeyColumnsCall) DoAndReturn(f func() []database.Column) *MockUserPasswordRepositoryPrimaryKeyColumnsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PrimaryKeyCondition mocks base method.
func (m *MockUserPasswordRepository) PrimaryKeyCondition(id int64) database.Condition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrimaryKeyCondition", id)
	ret0, _ := ret[0].(database.Condition)
	return ret0
}

// PrimaryKeyCondition indicates an expected call of PrimaryKeyCondition.
func (mr *MockUserPasswordRepositoryMockRecorder) PrimaryKeyCondition(id any) *MockUserPasswordRepositoryPrimaryKeyConditionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrimaryKeyCondition", reflect.TypeOf((*MockUserPasswordRepository)(nil).PrimaryKeyCondition), id)
	return &MockUserPasswordRepositoryPrimaryKeyConditionCall{Call: call}
}

// MockUserPasswordRepositoryPrimaryKeyConditionCall wrap *gomock.Call
type MockUserPasswordRepositoryPrimaryKeyConditionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositoryPrimaryKeyConditionCall) Return(arg0 database.Condition) *MockUserPasswordRepositoryPrimaryKeyConditionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositoryPrimaryKeyConditionCall) Do(f func(int64) database.Condition) *MockUserPasswordRepositoryPrimaryKeyConditionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositoryPrimaryKeyConditionCall) DoAndReturn(f func(int64) database.Condition) *MockUserPasswordRepositoryPrimaryKeyConditionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProjectIDCondition mocks base method.
func (m *MockUserPasswordRepository) ProjectIDCondition(projectID string) database.Condition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectIDCondition", projectID)
	ret0, _ := ret[0].(database.Condition)
	return ret0
}

// ProjectIDCondition indicates an expected call of ProjectIDCondition.
func (mr *MockUserPasswordRepositoryMockRecorder) ProjectIDCondition(projectID any) *MockUserPasswordRepositoryProjectIDConditionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectIDCondition", reflect.TypeOf((*MockUserPasswordRepository)(nil).ProjectIDCondition), projectID)
	return &MockUserPasswordRepositoryProjectIDConditionCall{Call: call}
}

// MockUserPasswordRepositoryProjectIDConditionCall wrap *gomock.Call
type MockUserPasswordRepositoryProjectIDConditionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositoryProjectIDConditionCall) Return(arg0 database.Condition) *MockUserPasswordRepositoryProjectIDConditionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositoryProjectIDConditionCall) Do(f func(string) database.Condition) *MockUserPasswordRepositoryProjectIDConditionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositoryProjectIDConditionCall) DoAndReturn(f func(string) database.Condition) *MockUserPasswordRepositoryProjectIDConditionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResetFailedAttempts mocks base method.
func (m *MockUserPasswordRepository) ResetFailedAttempts() database.Change {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetFailedAttempts")
	ret0, _ := ret[0].(database.Change)
	return ret0
}

// ResetFailedAttempts indicates an expected call of ResetFailedAttempts.
func (mr *MockUserPasswordRepositoryMockRecorder) ResetFailedAttempts() *MockUserPasswordRepositoryResetFailedAttemptsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFailedAttempts", reflect.TypeOf((*MockUserPasswordRepository)(nil).ResetFailedAttempts))
	return &MockUserPasswordRepositoryResetFailedAttemptsCall{Call: call}
}

// MockUserPasswordRepositoryResetFailedAttemptsCall wrap *gomock.Call
type MockUserPasswordRepositoryResetFailedAttemptsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositoryResetFailedAttemptsCall) Return(arg0 database.Change) *MockUserPasswordRepositoryResetFailedAttemptsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositoryResetFailedAttemptsCall) Do(f func() database.Change) *MockUserPasswordRepositoryResetFailedAttemptsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositoryResetFailedAttemptsCall) DoAndReturn(f func() database.Change) *MockUserPasswordRepositoryResetFailedAttemptsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetChangeRequired mocks base method.
func (m *MockUserPasswordRepository) SetChangeRequired(arg0 bool) database.Change {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetChangeRequired", arg0)
	ret0, _ := ret[0].(database.Change)
	return ret0
}

// SetChangeRequired indicates an expected call of SetChangeRequired.
func (mr *MockUserPasswordRepositoryMockRecorder) SetChangeRequired(arg0 any) *MockUserPasswordRepositorySetChangeRequiredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetChangeRequired", reflect.TypeOf((*MockUserPasswordRepository)(nil).SetChangeRequired), arg0)
	return &MockUserPasswordRepositorySetChangeRequiredCall{Call: call}
}

// MockUserPasswordRepositorySetChangeRequiredCall wrap *gomock.Call
type MockUserPasswordRepositorySetChangeRequiredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositorySetChangeRequiredCall) Return(arg0 database.Change) *MockUserPasswordRepositorySetChangeRequiredCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositorySetChangeRequiredCall) Do(f func(bool) database.Change) *MockUserPasswordRepositorySetChangeRequiredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositorySetChangeRequiredCall) DoAndReturn(f func(bool) database.Change) *MockUserPasswordRepositorySetChangeRequiredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetChangedAt mocks base method.
func (m *MockUserPasswordRepository) SetChangedAt(arg0 time.Time) database.Change {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetChangedAt", arg0)
	ret0, _ := ret[0].(database.Change)
	return ret0
}

// SetChangedAt indicates an expected call of SetChangedAt.
func (mr *MockUserPasswordRepositoryMockRecorder) SetChangedAt(arg0 any) *MockUserPasswordRepositorySetChangedAtCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetChangedAt", reflect.TypeOf((*MockUserPasswordRepository)(nil).SetChangedAt), arg0)
	return &MockUserPasswordRepositorySetChangedAtCall{Call: call}
}

// MockUserPasswordRepositorySetChangedAtCall wrap *gomock.Call
type MockUserPasswordRepositorySetChangedAtCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositorySetChangedAtCall) Return(arg0 database.Change) *MockUserPasswordRepositorySetChangedAtCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositorySetChangedAtCall) Do(f func(time.Time) database.Change) *MockUserPasswordRepositorySetChangedAtCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositorySetChangedAtCall) DoAndReturn(f func(time.Time) database.Change) *MockUserPasswordRepositorySetChangedAtCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetEncodedHash mocks base method.
func (m *MockUserPasswordRepository) SetEncodedHash(hash string) database.Change {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEncodedHash", hash)
	ret0, _ := ret[0].(database.Change)
	return ret0
}

// SetEncodedHash indicates an expected call of SetEncodedHash.
func (mr *MockUserPasswordRepositoryMockRecorder) SetEncodedHash(hash any) *MockUserPasswordRepositorySetEncodedHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEncodedHash", reflect.TypeOf((*MockUserPasswordRepository)(nil).SetEncodedHash), hash)
	return &MockUserPasswordRepositorySetEncodedHashCall{Call: call}
}

// MockUserPasswordRepositorySetEncodedHashCall wrap *gomock.Call
type MockUserPasswordRepositorySetEncodedHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositorySetEncodedHashCall) Return(arg0 database.Change) *MockUserPasswordRepositorySetEncodedHashCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositorySetEncodedHashCall) Do(f func(string) database.Change) *MockUserPasswordRepositorySetEncodedHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositorySetEncodedHashCall) DoAndReturn(f func(string) database.Change) *MockUserPasswordRepositorySetEncodedHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetLastSuccessfulCheck mocks base method.
func (m *MockUserPasswordRepository) SetLastSuccessfulCheck(arg0 time.Time) database.Change {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastSuccessfulCheck", arg0)
	ret0, _ := ret[0].(database.Change)
	return ret0
}

// SetLastSuccessfulCheck indicates an expected call of SetLastSuccessfulCheck.
func (mr *MockUserPasswordRepositoryMockRecorder) SetLastSuccessfulCheck(arg0 any) *MockUserPasswordRepositorySetLastSuccessfulCheckCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastSuccessfulCheck", reflect.TypeOf((*MockUserPasswordRepository)(nil).SetLastSuccessfulCheck), arg0)
	return &MockUserPasswordRepositorySetLastSuccessfulCheckCall{Call: call}
}

// MockUserPasswordRepositorySetLastSuccessfulCheckCall wrap *gomock.Call
type MockUserPasswordRepositorySetLastSuccessfulCheckCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositorySetLastSuccessfulCheckCall) Return(arg0 database.Change) *MockUserPasswordRepositorySetLastSuccessfulCheckCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositorySetLastSuccessfulCheckCall) Do(f func(time.Time) database.Change) *MockUserPasswordRepositorySetLastSuccessfulCheckCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositorySetLastSuccessfulCheckCall) DoAndReturn(f func(time.Time) database.Change) *MockUserPasswordRepositorySetLastSuccessfulCheckCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetVerificationID mocks base method.
func (m *MockUserPasswordRepository) SetVerificationID(arg0 string) database.Change {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVerificationID", arg0)
	ret0, _ := ret[0].(database.Change)
	return ret0
}

// SetVerificationID indicates an expected call of SetVerificationID.
func (mr *MockUserPasswordRepositoryMockRecorder) SetVerificationID(arg0 any) *MockUserPasswordRepositorySetVerificationIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVerificationID", reflect.TypeOf((*MockUserPasswordRepository)(nil).SetVerificationID), arg0)
	return &MockUserPasswordRepositorySetVerificationIDCall{Call: call}
}

// MockUserPasswordRepositorySetVerificationIDCall wrap *gomock.Call
type MockUserPasswordRepositorySetVerificationIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositorySetVerificationIDCall) Return(arg0 database.Change) *MockUserPasswordRepositorySetVerificationIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositorySetVerificationIDCall) Do(f func(string) database.Change) *MockUserPasswordRepositorySetVerificationIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositorySetVerificationIDCall) DoAndReturn(f func(string) database.Change) *MockUserPasswordRepositorySetVerificationIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UniqueCondition mocks base method.
func (m *MockUserPasswordRepository) UniqueCondition(projectID, userID string) database.Condition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UniqueCondition", projectID, userID)
	ret0, _ := ret[0].(database.Condition)
	return ret0
}

// UniqueCondition indicates an expected call of UniqueCondition.
func (mr *MockUserPasswordRepositoryMockRecorder) UniqueCondition(projectID, userID any) *MockUserPasswordRepositoryUniqueConditionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UniqueCondition", reflect.TypeOf((*MockUserPasswordRepository)(nil).UniqueCondition), projectID, userID)
	return &MockUserPasswordRepositoryUniqueConditionCall{Call: call}
}

// MockUserPasswordRepositoryUniqueConditionCall wrap *gomock.Call
type MockUserPasswordRepositoryUniqueConditionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositoryUniqueConditionCall) Return(arg0 database.Condition) *MockUserPasswordRepositoryUniqueConditionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositoryUniqueConditionCall) Do(f func(string, string) database.Condition) *MockUserPasswordRepositoryUniqueConditionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositoryUniqueConditionCall) DoAndReturn(f func(string, string) database.Condition) *MockUserPasswordRepositoryUniqueConditionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UserIDCondition mocks base method.
func (m *MockUserPasswordRepository) UserIDCondition(userID string) database.Condition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserIDCondition", userID)
	ret0, _ := ret[0].(database.Condition)
	return ret0
}

// UserIDCondition indicates an expected call of UserIDCondition.
func (mr *MockUserPasswordRepositoryMockRecorder) UserIDCondition(userID any) *MockUserPasswordRepositoryUserIDConditionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserIDCondition", reflect.TypeOf((*MockUserPasswordRepository)(nil).UserIDCondition), userID)
	return &MockUserPasswordRepositoryUserIDConditionCall{Call: call}
}

// MockUserPasswordRepositoryUserIDConditionCall wrap *gomock.Call
type MockUserPasswordRepositoryUserIDConditionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserPasswordRepositoryUserIDConditionCall) Return(arg0 database.Condition) *MockUserPasswordRepositoryUserIDConditionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserPasswordRepositoryUserIDConditionCall) Do(f func(string) database.Condition) *MockUserPasswordRepositoryUserIDConditionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserPasswordRepositoryUserIDConditionCall) DoAndReturn(f func(string) database.Condition) *MockUserPasswordRepositoryUserIDConditionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
