// gen_openapi_errors generates OpenAPI default responses for each operation.
//
// The error set of a service method is inferred from the implementation by
// [erroranalysis], which follows the error value through the call graph. The
// "errors:" doc comments on the service interfaces are no longer the source of
// truth; where one disagrees with the code, the generator reports the drift and
// the code wins.
//
// Paths are calculated relative to this generator's location:
//   - Domain: ../../../internal/domain
//   - Service: ../../../internal/service
//   - OpenAPI: ../../openapi
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"slices"
	"sort"
	"strings"
	"text/template"
	"unicode"
	"unicode/utf8"

	"gopkg.in/yaml.v3"

	"github.com/zitadel/nextgen/api/internal/erroranalysis"
)

type ErrorCode struct {
	Code     string
	Filename string
	Message  string
}

type EndpointData struct {
	ErrorCodes []ErrorCode
	RefPrefix  string
}

type endpointOperation struct {
	operationID string
	yamlPath    string
}

const defaultResponseTemplate = `# generated by gen_openapi_errors; DO NOT EDIT
description: Error response
content:
  application/json:
    schema:
      oneOf:
{{- range .ErrorCodes }}
        - $ref: '{{ $.RefPrefix }}{{ .Filename }}.yaml'
{{- end }}
      discriminator:
        propertyName: code
        mapping:
{{- range .ErrorCodes }}
          {{ .Code }}: '{{ $.RefPrefix }}{{ .Filename }}.yaml'
{{- end }}
    examples:
{{- range .ErrorCodes }}
      {{ .Code }}:
        summary: {{ .Code }}
        value:
          code: {{ .Code }}
          message: {{ yamlScalar .Message }}
{{- end }}
`

// yamlScalar renders s as a single-quoted YAML scalar. Error messages are free
// text and several contain ": " ("flow definition: not found"), which YAML
// parses as a nested mapping when left bare.
func yamlScalar(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func main() {
	// Get the directory where this generator is located
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		_, _ = fmt.Fprintln(os.Stderr, "Failed to get current file path")
		os.Exit(1)
	}
	generatorDir := filepath.Dir(filename)

	// Calculate paths relative to generator location
	// Generator is at: api/cmd/gen_openapi_errors/main.go
	moduleRoot := filepath.Join(generatorDir, "../../..")
	domainPath := filepath.Join(generatorDir, "../../../internal/domain")
	servicePath := filepath.Join(generatorDir, "../../../internal/service")
	internalAPIPath := filepath.Join(generatorDir, "../../../internal/api")
	openapiBasePath := filepath.Join(generatorDir, "../../openapi")

	// Step 1: Parse domain package to build error function -> error info mapping
	errorMapping := buildErrorMapping(domainPath)
	fmt.Printf("📋 Discovered %d error codes from domain package\n", len(errorMapping))

	// Step 2: Infer each service method's error set from its implementation,
	// then hold the hand-written "errors:" comments up against it.
	analyzed, err := erroranalysis.Analyze(erroranalysis.Config{Dir: moduleRoot})
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "❌ Error analyzing service error paths: %v\n", err)
		os.Exit(1)
	}
	allMethods := methodErrorsFromAnalysis(analyzed)
	fmt.Printf("📋 Inferred error sets for %d service methods\n", len(allMethods))

	reportCommentDrift(parseAllServiceFiles(servicePath), allMethods)

	// Step 3: Define endpoint mappings
	endpoints, err := discoverEndpointsWithDefaultErrorResponse(openapiBasePath)
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "❌ Error discovering endpoint operations: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("📋 Discovered %d endpoint operations with default error responses\n", len(endpoints))

	serviceMethodByOperation, err := discoverServiceMethodByOperation(internalAPIPath, endpoints)
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "❌ Error reflecting API handler service calls: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("📋 Reflected %d operation-to-service mappings from API handlers\n", len(serviceMethodByOperation))

	tmpl := template.Must(template.New("default").
		Funcs(template.FuncMap{"yamlScalar": yamlScalar}).
		Parse(defaultResponseTemplate))

	// Step 4: Generate error response files for each endpoint
	for _, endpoint := range endpoints {
		serviceMethods, ok := serviceMethodByOperation[endpoint.operationID]
		if !ok {
			fmt.Printf("⚠️  No reflected service mapping for %s (%s), skipping\n", endpoint.operationID, endpoint.yamlPath)
			continue
		}

		// A handler may call several services — createSession mints a crypter
		// before creating the session — and can surface an error from any of
		// them, so the operation advertises the union.
		var errFuncs []string
		for _, serviceMethod := range serviceMethods {
			method, ok := allMethods[serviceMethod]
			if !ok {
				fmt.Printf("⚠️  Service method %s not found, skipping it for %s\n", serviceMethod, endpoint.operationID)
				continue
			}
			for _, errFunc := range method.errorFuncs {
				if !slices.Contains(errFuncs, errFunc) {
					errFuncs = append(errFuncs, errFunc)
				}
			}
		}
		sort.Strings(errFuncs)

		// Convert error functions to error codes using the auto-discovered mapping
		var errorCodes []ErrorCode
		for _, errFunc := range errFuncs {
			if errInfo, ok := errorMapping[errFunc]; ok {
				errorCodes = append(errorCodes, ErrorCode{
					Code:     errInfo.code,
					Filename: strings.ReplaceAll(errInfo.code, ".", "-"),
					Message:  errInfo.message,
				})
			} else {
				fmt.Printf("⚠️  Unknown error function %s in %s\n", errFunc, endpoint.operationID)
			}
		}

		if len(errorCodes) == 0 {
			fmt.Printf("⚠️  No errors found for %s\n", endpoint.operationID)
			continue
		}

		// Calculate relative path from endpoint directory to components/schemas/errors/
		endpointDir := filepath.Dir(endpoint.yamlPath)
		relPath := strings.TrimPrefix(endpointDir, openapiBasePath+string(os.PathSeparator))
		depth := strings.Count(relPath, string(os.PathSeparator)) + 1
		refPrefix := strings.Repeat("../", depth) + "components/schemas/errors/"

		// Generate the default response YAML
		var buf strings.Builder
		if err := tmpl.Execute(&buf, EndpointData{
			ErrorCodes: errorCodes,
			RefPrefix:  refPrefix,
		}); err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "❌ Error generating %s: %v\n", endpoint.operationID, err)
			continue
		}

		// Write to a unique error response file based on operation ID
		filename := fmt.Sprintf("%s-error-response.yaml", endpoint.operationID)
		outputPath := filepath.Join(filepath.Dir(endpoint.yamlPath), filename)
		if err := os.WriteFile(outputPath, []byte(buf.String()), 0o644); err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "❌ Error writing %s: %v\n", outputPath, err)
			continue
		}

		fmt.Printf("✅ Generated %s (%d errors)\n", filename, len(errorCodes))
	}

	fmt.Println("\n💡 Generated operation-specific error response files")
}

func discoverServiceMethodByOperation(internalAPIPath string, endpoints []endpointOperation) (map[string][]string, error) {
	handlerMethods, err := discoverHandlerServiceMethods(internalAPIPath)
	if err != nil {
		return nil, err
	}

	serviceMethodByOperation := make(map[string][]string, len(endpoints))
	for _, endpoint := range endpoints {
		handlerMethod := operationIDToHandlerMethod(endpoint.operationID)
		if serviceMethods, ok := handlerMethods[handlerMethod]; ok {
			serviceMethodByOperation[endpoint.operationID] = serviceMethods
		}
	}

	return serviceMethodByOperation, nil
}

// discoverHandlerServiceMethods maps each Handler method to every service
// method it calls. Only interface-typed fields are matched: a service held as a
// concrete pointer has no interface for the analysis to key on.
func discoverHandlerServiceMethods(internalAPIPath string) (map[string][]string, error) {
	files, err := filepath.Glob(filepath.Join(internalAPIPath, "*.go"))
	if err != nil {
		return nil, err
	}

	fset := token.NewFileSet()
	fieldServiceInterfaces := map[string]string{}
	handlerMethods := map[string][]string{}

	for _, filePath := range files {
		file, err := parser.ParseFile(fset, filePath, nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", filePath, err)
		}

		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok || typeSpec.Name.Name != "Handler" {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				for _, field := range structType.Fields.List {
					if len(field.Names) == 0 {
						continue
					}
					selector, ok := field.Type.(*ast.SelectorExpr)
					if !ok {
						continue
					}
					pkgIdent, ok := selector.X.(*ast.Ident)
					if !ok || pkgIdent.Name != "service" {
						continue
					}
					for _, name := range field.Names {
						fieldServiceInterfaces[name.Name] = selector.Sel.Name
					}
				}
			}
		}
	}

	for _, filePath := range files {
		file, err := parser.ParseFile(fset, filePath, nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", filePath, err)
		}

		for _, decl := range file.Decls {
			funcDecl, ok := decl.(*ast.FuncDecl)
			if !ok || funcDecl.Recv == nil || funcDecl.Body == nil {
				continue
			}
			if !isHandlerReceiver(funcDecl.Recv) {
				continue
			}

			serviceCalls := make(map[string]struct{})
			ast.Inspect(funcDecl.Body, func(n ast.Node) bool {
				callExpr, ok := n.(*ast.CallExpr)
				if !ok {
					return true
				}

				outerSel, ok := callExpr.Fun.(*ast.SelectorExpr)
				if !ok {
					return true
				}

				innerSel, ok := outerSel.X.(*ast.SelectorExpr)
				if !ok {
					return true
				}

				receiver, ok := innerSel.X.(*ast.Ident)
				if !ok || receiver.Name != "h" {
					return true
				}

				serviceInterface, ok := fieldServiceInterfaces[innerSel.Sel.Name]
				if !ok {
					return true
				}

				serviceCalls[serviceInterface+"."+outerSel.Sel.Name] = struct{}{}
				return true
			})

			if len(serviceCalls) == 0 {
				continue
			}
			methods := make([]string, 0, len(serviceCalls))
			for serviceMethod := range serviceCalls {
				methods = append(methods, serviceMethod)
			}
			sort.Strings(methods)
			handlerMethods[funcDecl.Name.Name] = methods
		}
	}

	return handlerMethods, nil
}

func isHandlerReceiver(recv *ast.FieldList) bool {
	if recv == nil || len(recv.List) == 0 {
		return false
	}

	typeExpr := recv.List[0].Type
	if starExpr, ok := typeExpr.(*ast.StarExpr); ok {
		typeExpr = starExpr.X
	}

	ident, ok := typeExpr.(*ast.Ident)
	return ok && ident.Name == "Handler"
}

func operationIDToHandlerMethod(operationID string) string {
	if operationID == "" {
		return ""
	}

	r, size := utf8.DecodeRuneInString(operationID)
	if r == utf8.RuneError {
		return operationID
	}
	return string(unicode.ToUpper(r)) + operationID[size:]
}

type methodsFileOperation struct {
	OperationID string                         `yaml:"operationId"`
	Responses   map[string]methodsFileResponse `yaml:"responses"`
}

type methodsFileResponse struct {
	Ref     string `yaml:"$ref"`
	Content map[string]struct {
		Schema struct {
			Ref string `yaml:"$ref"`
		} `yaml:"schema"`
	} `yaml:"content"`
}

func discoverEndpointsWithDefaultErrorResponse(openapiBasePath string) ([]endpointOperation, error) {
	endpointsRoot := filepath.Join(openapiBasePath, "endpoints")
	var endpoints []endpointOperation

	err := filepath.WalkDir(endpointsRoot, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() || filepath.Base(path) != "methods.yaml" {
			return nil
		}

		ops, err := parseMethodsFile(path)
		if err != nil {
			return err
		}

		for _, op := range ops {
			if op.OperationID == "" {
				continue
			}
			if !hasDefaultErrorDetailsRef(op) {
				continue
			}
			endpoints = append(endpoints, endpointOperation{
				operationID: op.OperationID,
				yamlPath:    path,
			})
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	sort.Slice(endpoints, func(i, j int) bool {
		if endpoints[i].yamlPath == endpoints[j].yamlPath {
			return endpoints[i].operationID < endpoints[j].operationID
		}
		return endpoints[i].yamlPath < endpoints[j].yamlPath
	})

	return endpoints, nil
}

func parseMethodsFile(path string) ([]methodsFileOperation, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var raw map[string]methodsFileOperation
	if err := yaml.Unmarshal(content, &raw); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}

	methods := map[string]struct{}{
		"get": {}, "put": {}, "post": {}, "delete": {},
		"options": {}, "head": {}, "patch": {}, "trace": {},
	}

	ops := make([]methodsFileOperation, 0, len(raw))
	for key, op := range raw {
		if _, ok := methods[strings.ToLower(key)]; !ok {
			continue
		}
		ops = append(ops, op)
	}

	return ops, nil
}

func hasDefaultErrorDetailsRef(op methodsFileOperation) bool {
	defaultResponse, ok := op.Responses["default"]
	if !ok {
		return false
	}

	if strings.HasSuffix(normalizePath(defaultResponse.Ref), "-error-response.yaml") {
		return true
	}

	for _, media := range defaultResponse.Content {
		ref := normalizePath(media.Schema.Ref)
		if strings.HasSuffix(ref, "components/error-details.yaml") {
			return true
		}
	}

	return false
}

func normalizePath(p string) string {
	return strings.ReplaceAll(p, "\\", "/")
}

type errorInfo struct {
	code    string
	message string
}

// buildErrorMapping parses the domain package and extracts error function -> error info mappings
func buildErrorMapping(domainPath string) map[string]errorInfo {
	mapping := make(map[string]errorInfo)

	fset := token.NewFileSet()
	domainFiles, err := filepath.Glob(filepath.Join(domainPath, "*.go"))

	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Error listing domain files: %v\n", err)
		os.Exit(1)
	}

	files := make([]*ast.File, 0, len(domainFiles))
	for _, filename := range domainFiles {
		if strings.HasSuffix(filename, "_test.go") {
			continue
		}

		file, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
		if err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "Error parsing %s: %v\n", filename, err)
			continue
		}
		files = append(files, file)
	}

	prefixes := extractResourcePrefixes(files)

	for _, file := range files {
		ast.Inspect(file, func(n ast.Node) bool {
			funcDecl, ok := n.(*ast.FuncDecl)
			if !ok || !strings.HasPrefix(funcDecl.Name.Name, "Err") || funcDecl.Body == nil {
				return true
			}

			for _, stmt := range funcDecl.Body.List {
				retStmt, ok := stmt.(*ast.ReturnStmt)
				if !ok {
					continue
				}

				for _, result := range retStmt.Results {
					if callExpr, ok := result.(*ast.CallExpr); ok {
						if ident, ok := callExpr.Fun.(*ast.Ident); ok && ident.Name == "newError" {
							if len(callExpr.Args) >= 2 {
								code := extractCodeArgument(callExpr.Args[0], prefixes)
								message := ""
								if msgLit, ok := callExpr.Args[1].(*ast.BasicLit); ok {
									message = strings.Trim(msgLit.Value, `"`)
								}
								if code != "" {
									mapping["domain."+funcDecl.Name.Name] = errorInfo{
										code:    code,
										message: message,
									}
								}
							}
						}
					}
				}
			}

			return true
		})
	}

	return mapping
}

func extractResourcePrefixes(files []*ast.File) map[string]string {
	prefixes := make(map[string]string)

	for _, file := range files {
		for _, decl := range file.Decls {
			// Resource prefixes are normally const, but TokenPrefix is a var —
			// accept both, or its error codes go missing entirely.
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || (genDecl.Tok != token.CONST && genDecl.Tok != token.VAR) {
				continue
			}

			for _, spec := range genDecl.Specs {
				valueSpec, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}

				for i, name := range valueSpec.Names {
					if valueSpec.Type != nil {
						if ident, ok := valueSpec.Type.(*ast.Ident); ok && ident.Name == "ResourcePrefix" {
							if i < len(valueSpec.Values) {
								if lit, ok := valueSpec.Values[i].(*ast.BasicLit); ok {
									value := strings.Trim(lit.Value, `"`)
									prefixes[name.Name] = value
								}
							}
						}
					}
				}
			}
		}
	}

	return prefixes
}

func extractCodeArgument(arg ast.Expr, prefixes map[string]string) string {
	if lit, ok := arg.(*ast.BasicLit); ok {
		return strings.Trim(lit.Value, `"`)
	}

	if callExpr, ok := arg.(*ast.CallExpr); ok {
		if selExpr, ok := callExpr.Fun.(*ast.SelectorExpr); ok {
			if selExpr.Sel.Name == "ErrorCodePrefix" {
				if ident, ok := selExpr.X.(*ast.Ident); ok {
					prefixValue, ok := prefixes[ident.Name]
					if !ok {
						return ""
					}

					if len(callExpr.Args) > 0 {
						if suffixLit, ok := callExpr.Args[0].(*ast.BasicLit); ok {
							suffix := strings.Trim(suffixLit.Value, `"`)
							return prefixValue + "." + suffix
						}
					}
				}
			}
		}
	}

	return ""
}

type serviceMethod struct {
	interfaceName string
	methodName    string
	errorFuncs    []string
}

// boundaryErrors are reachable on every operation no matter what the service
// raises: domainErrorDetails in internal/api falls back to domain.ErrInternal
// for anything that is not a domain.Error, so a storage or library failure
// surfaces as `internal` on any endpoint. The service-level analysis cannot see
// that — it is a property of the HTTP boundary — so it is added here.
var boundaryErrors = []string{"domain.ErrInternal"}

// methodErrorsFromAnalysis adapts the inferred error sets to the shape the
// generation loop consumes.
func methodErrorsFromAnalysis(analyzed map[string]erroranalysis.Method) map[string]serviceMethod {
	out := make(map[string]serviceMethod, len(analyzed))
	for key, m := range analyzed {
		if m.Unimplemented {
			fmt.Printf("⚠️  %s has no implementation to analyze\n", key)
			continue
		}

		codes := slices.Clone(m.Errors)
		for _, code := range boundaryErrors {
			if !slices.Contains(codes, code) {
				codes = append(codes, code)
			}
		}
		sort.Strings(codes)

		out[key] = serviceMethod{
			interfaceName: m.Interface,
			methodName:    m.Name,
			errorFuncs:    codes,
		}
	}
	return out
}

// reportCommentDrift prints where a hand-written "errors:" doc comment no
// longer matches what the implementation can actually return. The comments are
// advisory now, so this is a nudge to fix (or delete) them — not a failure.
func reportCommentDrift(declared, inferred map[string]serviceMethod) {
	keys := make([]string, 0, len(declared))
	for key := range declared {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	drifted := 0
	for _, key := range keys {
		want := declared[key].errorFuncs
		got := inferred[key].errorFuncs

		var missing, extra []string
		for _, code := range want {
			if !slices.Contains(got, code) {
				extra = append(extra, code)
			}
		}
		for _, code := range got {
			if !slices.Contains(want, code) {
				missing = append(missing, code)
			}
		}
		if len(missing) == 0 && len(extra) == 0 {
			continue
		}

		drifted++
		fmt.Printf("⚠️  %s: doc comment is out of date\n", key)
		if len(missing) > 0 {
			fmt.Printf("      code returns but comment omits: %s\n", strings.Join(missing, ", "))
		}
		if len(extra) > 0 {
			fmt.Printf("      comment claims but code cannot return: %s\n", strings.Join(extra, ", "))
		}
	}

	if drifted > 0 {
		fmt.Printf("💡 %d service method comment(s) drifted; the spec follows the code\n", drifted)
	}
}

// parseAllServiceFiles scans all .go files in the service directory and extracts
// service interface methods with error documentation.
func parseAllServiceFiles(servicePath string) map[string]serviceMethod {
	allMethods := make(map[string]serviceMethod)

	files, err := filepath.Glob(filepath.Join(servicePath, "*.go"))
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Error listing service files: %v\n", err)
		os.Exit(1)
	}

	errorPattern := regexp.MustCompile(`errors:\s*(.+)`)

	for _, filename := range files {
		if strings.HasSuffix(filename, "_test.go") {
			continue
		}

		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
		if err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "Error parsing %s: %v\n", filename, err)
			continue
		}

		ast.Inspect(file, func(n ast.Node) bool {
			typeSpec, ok := n.(*ast.TypeSpec)
			if !ok {
				return true
			}

			iface, ok := typeSpec.Type.(*ast.InterfaceType)
			if !ok || !strings.HasSuffix(typeSpec.Name.Name, "Service") {
				return true
			}

			interfaceName := typeSpec.Name.Name

			for _, method := range iface.Methods.List {
				if len(method.Names) == 0 || method.Doc == nil {
					continue
				}

				methodName := method.Names[0].Name

				for _, comment := range method.Doc.List {
					if matches := errorPattern.FindStringSubmatch(comment.Text); len(matches) > 1 {
						var errs []string
						for _, e := range strings.Split(matches[1], ",") {
							errs = append(errs, strings.TrimSpace(e))
						}

						key := interfaceName + "." + methodName
						allMethods[key] = serviceMethod{
							interfaceName: interfaceName,
							methodName:    methodName,
							errorFuncs:    errs,
						}
						break
					}
				}
			}

			return true
		})
	}

	return allMethods
}
