// gen_openapi_errors generates OpenAPI default responses for each operation.
//
// The error set of a service method is inferred from the implementation by
// [erroranalysis], which follows the error value through the call graph. The
// "errors:" doc comments on the service interfaces are no longer the source of
// truth; where one disagrees with the code, the generator reports the drift and
// the code wins.
//
// # Bootstrapping a pruned tree
//
// That inference type-loads the module, and the module does not type-check
// until ogen has written api/generated — which ogen produces from a spec whose
// endpoints $ref the very files written here. On a tree that still holds its
// generated output the cycle is invisible; on a pruned one no directive order
// resolves it, because it closes through this generator's own chain.
//
// So the generator breaks it itself, rather than leaving it to whoever invokes
// it. When api/generated is absent it runs two prerequisites before analyzing:
//
//   - the enumer directives, because the analysis also needs their output and
//     `go generate ./...` reaches internal/ only after api/;
//   - the ogen directive, over a placeholder spec written here that gives every
//     operation every known error code. That spec is wrong but complete, which
//     is all ogen needs, and it is deliberately a superset: whatever types the
//     honest pass makes ogen generate, the placeholder made it generate too.
//
// The analysis then runs against a module that compiles, the real sets
// overwrite the placeholders, and the ogen directive that follows this one in
// api/generate.go regenerates the client from them. Both prerequisites shell
// out to `go generate -run`, so their commands stay declared in one place
// instead of being copied here.
//
// This is why bare `go generate ./...` and `moon run server:generate` both work
// from a pruned tree: neither of them knows about the cycle.
//
// Paths are calculated relative to this generator's location:
//   - Domain: ../../../internal/domain
//   - Service: ../../../internal/service
//   - OpenAPI: ../../openapi
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"slices"
	"sort"
	"strings"
	"text/template"
	"unicode"
	"unicode/utf8"

	"gopkg.in/yaml.v3"

	"github.com/zitadel/nextgen/api/internal/erroranalysis"
)

// Regexps for `go generate -run`, matched against a directive's full source
// text. Keep them in step with the ogen directive in api/generate.go and the
// enumer ones next to the enum type declarations.
const (
	enumerDirective = "go tool enumer"
	ogenDirective   = "go tool ogen"
)

// bootstrapGuardEnv marks a `go generate` this generator spawned. The
// directives it selects cannot reach this generator, so recursion should be
// impossible; the guard turns a mis-typed filter into one clear failure rather
// than an unbounded fork bomb.
const bootstrapGuardEnv = "NEXTGEN_GENERATE_BOOTSTRAPPING"

type ErrorCode struct {
	Code     string
	Filename string
	Message  string
}

type EndpointData struct {
	ErrorCodes []ErrorCode
	RefPrefix  string
}

type endpointOperation struct {
	operationID  string
	yamlPath     string
	requiresAuth bool
}

const defaultResponseTemplate = `# generated by gen_openapi_errors; DO NOT EDIT
description: Error response
content:
  application/json:
    schema:
      oneOf:
{{- range .ErrorCodes }}
        - $ref: '{{ $.RefPrefix }}{{ .Filename }}.yaml'
{{- end }}
      discriminator:
        propertyName: code
        mapping:
{{- range .ErrorCodes }}
          {{ .Code }}: '{{ $.RefPrefix }}{{ .Filename }}.yaml'
{{- end }}
    examples:
{{- range .ErrorCodes }}
      {{ .Code }}:
        summary: {{ .Code }}
        value:
          code: {{ .Code }}
          message: {{ yamlScalar .Message }}
{{- end }}
`

// yamlScalar renders s as a single-quoted YAML scalar. Error messages are free
// text and several contain ": " ("flow definition: not found"), which YAML
// parses as a nested mapping when left bare.
func yamlScalar(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func main() {
	// Get the directory where this generator is located
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		_, _ = fmt.Fprintln(os.Stderr, "Failed to get current file path")
		os.Exit(1)
	}
	generatorDir := filepath.Dir(filename)

	// Calculate paths relative to generator location
	// Generator is at: api/cmd/gen_openapi_errors/main.go
	moduleRoot := filepath.Join(generatorDir, "../../..")
	// Where api/generate.go lives, and so where its ogen directive runs.
	apiDir := filepath.Join(generatorDir, "../..")
	domainPath := filepath.Join(generatorDir, "../../../internal/domain")
	servicePath := filepath.Join(generatorDir, "../../../internal/service")
	internalAPIPath := filepath.Join(generatorDir, "../../../internal/api")
	openapiBasePath := filepath.Join(generatorDir, "../../openapi")

	// Step 1: Parse domain package to build error function -> error info mapping
	errorMapping := buildErrorMapping(domainPath)
	fmt.Printf("📋 Discovered %d error codes from domain package\n", len(errorMapping))

	// Step 2: Define endpoint mappings
	endpoints, err := discoverEndpointsWithDefaultErrorResponse(openapiBasePath)
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "❌ Error discovering endpoint operations: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("📋 Discovered %d endpoint operations with default error responses\n", len(endpoints))

	tmpl := template.Must(template.New("default").
		Funcs(template.FuncMap{"yamlScalar": yamlScalar}).
		Parse(defaultResponseTemplate))

	// Step 3: On a pruned tree the analysis below has nothing to analyze — the
	// module does not type-check until ogen has run, and ogen cannot run until
	// this generator has written a spec. Break the cycle with a placeholder
	// pass; see the package comment.
	if !generatedClientExists(moduleRoot) {
		bootstrapGeneratedClient(moduleRoot, apiDir, func() {
			allErrorFuncs := slices.Sorted(maps.Keys(errorMapping))
			writeErrorResponses(endpoints, tmpl, errorMapping, openapiBasePath,
				func(endpointOperation) ([]string, bool) { return allErrorFuncs, true })
		})
	}

	// Step 4: Infer each service method's error set from its implementation,
	// then hold the hand-written "errors:" comments up against it.
	analyzed, err := erroranalysis.Analyze(erroranalysis.Config{Dir: moduleRoot})
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "❌ Error analyzing service error paths: %v\n", err)
		if !generatedClientExists(moduleRoot) {
			_, _ = fmt.Fprintf(os.Stderr,
				"\napi/generated is still missing, so the module cannot type-check and this\n"+
					"analysis cannot run. The bootstrap pass should have written it — check that\n"+
					"the ogen directive in api/generate.go still matches the %q filter.\n", ogenDirective)
		}
		os.Exit(1)
	}
	allMethods := methodErrorsFromAnalysis(analyzed)
	fmt.Printf("📋 Inferred error sets for %d service methods\n", len(allMethods))

	reportCommentDrift(parseAllServiceFiles(servicePath), allMethods)

	serviceMethodByOperation, err := discoverServiceMethodByOperation(internalAPIPath, endpoints)
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "❌ Error reflecting API handler service calls: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("📋 Reflected %d operation-to-service mappings from API handlers\n", len(serviceMethodByOperation))

	// Step 5: Generate error response files for each endpoint
	writeErrorResponses(endpoints, tmpl, errorMapping, openapiBasePath, func(endpoint endpointOperation) ([]string, bool) {
		// The handler method is the real entry point: it raises errors of its
		// own — the authorization guard answers a foreign project with the
		// resource's not-found before any service is reached — and the walk
		// follows it into whatever services it calls.
		//
		// The reflected service union below is kept as a floor rather than
		// replaced. It only sees interface-typed handler fields, so it is the
		// narrower of the two, but unioning guarantees no operation advertises
		// less than it did before the handler walk existed: a spec that lists
		// an error the server never sends is harmless, while one that omits an
		// error it does send makes the generated client fail to decode it.
		handlerKey := "Handler." + operationIDToHandlerMethod(endpoint.operationID)
		handlerMethod, hasHandler := allMethods[handlerKey]

		// Operations whose handler could not be analyzed still fall back to the
		// union of the services it was reflected as calling.
		serviceMethods, hasServices := serviceMethodByOperation[endpoint.operationID]
		if !hasHandler && !hasServices {
			fmt.Printf("⚠️  No reflected service mapping for %s (%s), skipping\n", endpoint.operationID, endpoint.yamlPath)
			return nil, false
		}

		var errFuncs []string
		if hasHandler {
			errFuncs = append(errFuncs, handlerMethod.errorFuncs...)
		}
		for _, serviceMethod := range serviceMethods {
			method, ok := allMethods[serviceMethod]
			if !ok {
				fmt.Printf("⚠️  Service method %s not found, skipping it for %s\n", serviceMethod, endpoint.operationID)
				continue
			}
			errFuncs = append(errFuncs, method.errorFuncs...)
		}
		return errFuncs, true
	})

	fmt.Println("\n💡 Generated operation-specific error response files")
}

// writeErrorResponses renders one <operationID>-error-response.yaml per
// operation. errorFuncsFor supplies the operation's error constructors, or
// false to leave the operation's file alone; the transport and security codes
// every operation can raise are added here rather than by each caller.
func writeErrorResponses(
	endpoints []endpointOperation,
	tmpl *template.Template,
	errorMapping map[string]errorInfo,
	openapiBasePath string,
	errorFuncsFor func(endpointOperation) ([]string, bool),
) {
	for _, endpoint := range endpoints {
		operationErrFuncs, ok := errorFuncsFor(endpoint)
		if !ok {
			continue
		}

		// Cloned: the bootstrap pass hands the same slice to every operation.
		errFuncs := slices.Clone(operationErrFuncs)
		errFuncs = append(errFuncs, transportErrors...)
		if endpoint.requiresAuth {
			errFuncs = append(errFuncs, securityErrors...)
		}
		sort.Strings(errFuncs)
		errFuncs = slices.Compact(errFuncs)

		// Convert error functions to error codes using the auto-discovered mapping
		var errorCodes []ErrorCode
		for _, errFunc := range errFuncs {
			if errInfo, ok := errorMapping[errFunc]; ok {
				errorCodes = append(errorCodes, ErrorCode{
					Code:     errInfo.code,
					Filename: strings.ReplaceAll(errInfo.code, ".", "-"),
					Message:  errInfo.message,
				})
			} else {
				fmt.Printf("⚠️  Unknown error function %s in %s\n", errFunc, endpoint.operationID)
			}
		}

		if len(errorCodes) == 0 {
			fmt.Printf("⚠️  No errors found for %s\n", endpoint.operationID)
			continue
		}

		// Calculate relative path from endpoint directory to components/schemas/errors/
		endpointDir := filepath.Dir(endpoint.yamlPath)
		relPath := strings.TrimPrefix(endpointDir, openapiBasePath+string(os.PathSeparator))
		depth := strings.Count(relPath, string(os.PathSeparator)) + 1
		refPrefix := strings.Repeat("../", depth) + "components/schemas/errors/"

		// Generate the default response YAML
		var buf strings.Builder
		if err := tmpl.Execute(&buf, EndpointData{
			ErrorCodes: errorCodes,
			RefPrefix:  refPrefix,
		}); err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "❌ Error generating %s: %v\n", endpoint.operationID, err)
			continue
		}

		// Write to a unique error response file based on operation ID
		filename := fmt.Sprintf("%s-error-response.yaml", endpoint.operationID)
		outputPath := filepath.Join(filepath.Dir(endpoint.yamlPath), filename)
		if err := os.WriteFile(outputPath, []byte(buf.String()), 0o644); err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "❌ Error writing %s: %v\n", outputPath, err)
			continue
		}

		fmt.Printf("✅ Generated %s (%d errors)\n", filename, len(errorCodes))
	}
}

// bootstrapGeneratedClient produces the api/generated the error analysis needs
// before that analysis is possible — the pruned-tree cycle described in the
// package comment. writePlaceholderSpec fills every operation's error response
// with every known code, which is wrong but complete, and is the only spec
// available to generate a client from at this point.
//
// Nothing here is conditional on what is already on disk: both prerequisites
// are idempotent, and keeping the path single means `moon run server:generate`
// walks exactly the one `go generate ./...` does, so the standing pruned-tree
// check (server:check-generate-pruned) covers both. The cost is one redundant
// enumer run under the Moon runner, on the rare pruned path only.
func bootstrapGeneratedClient(moduleRoot, apiDir string, writePlaceholderSpec func()) {
	if os.Getenv(bootstrapGuardEnv) != "" {
		_, _ = fmt.Fprintf(os.Stderr,
			"❌ Bootstrapping recursively: a nested `go generate` re-entered this generator.\n"+
				"   Check that the -run filters (%q, %q) still select only the directives they name.\n",
			enumerDirective, ogenDirective)
		os.Exit(1)
	}

	fmt.Println("🥾 api/generated is missing: bootstrapping it so the module type-checks.")

	// The analysis type-loads internal/domain, which does not compile without
	// its enumer output. `go generate ./...` walks api before internal, so that
	// output cannot be assumed present — pull it forward.
	runDirectives(moduleRoot, enumerDirective, "./internal/...")

	writePlaceholderSpec()

	runDirectives(apiDir, ogenDirective, ".")

	fmt.Println("🥾 Bootstrap client generated; inferring the real error sets.")
}

// runDirectives re-runs a subset of the module's own //go:generate directives.
// Selecting them by -run rather than spelling out the commands keeps each one
// declared in a single place: api/generate.go for ogen, the enum type
// declarations for enumer.
func runDirectives(dir, filter, pattern string) {
	fmt.Printf("🥾 go generate -run %q %s\n", filter, pattern)

	cmd := exec.Command("go", "generate", "-run", filter, pattern)
	cmd.Dir = dir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = append(os.Environ(), bootstrapGuardEnv+"=1")
	if err := cmd.Run(); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "❌ Bootstrap step `go generate -run %q %s` failed: %v\n", filter, pattern, err)
		os.Exit(1)
	}
}

// generatedClientExists reports whether ogen has written its output yet. It
// separates "the analysis failed" from "the analysis could not have run" — the
// second is the pruned-tree case the bootstrap pass exists for.
func generatedClientExists(moduleRoot string) bool {
	matches, err := filepath.Glob(filepath.Join(moduleRoot, "api", "generated", "*.go"))
	return err == nil && len(matches) > 0
}

func discoverServiceMethodByOperation(internalAPIPath string, endpoints []endpointOperation) (map[string][]string, error) {
	handlerMethods, err := discoverHandlerServiceMethods(internalAPIPath)
	if err != nil {
		return nil, err
	}

	serviceMethodByOperation := make(map[string][]string, len(endpoints))
	for _, endpoint := range endpoints {
		handlerMethod := operationIDToHandlerMethod(endpoint.operationID)
		if serviceMethods, ok := handlerMethods[handlerMethod]; ok {
			serviceMethodByOperation[endpoint.operationID] = serviceMethods
		}
	}

	return serviceMethodByOperation, nil
}

// discoverHandlerServiceMethods maps each Handler method to every service
// method it calls. Only interface-typed fields are matched: a service held as a
// concrete pointer has no interface for the analysis to key on.
func discoverHandlerServiceMethods(internalAPIPath string) (map[string][]string, error) {
	files, err := filepath.Glob(filepath.Join(internalAPIPath, "*.go"))
	if err != nil {
		return nil, err
	}

	fset := token.NewFileSet()
	fieldServiceInterfaces := map[string]string{}
	handlerMethods := map[string][]string{}

	for _, filePath := range files {
		file, err := parser.ParseFile(fset, filePath, nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", filePath, err)
		}

		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok || typeSpec.Name.Name != "Handler" {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				for _, field := range structType.Fields.List {
					if len(field.Names) == 0 {
						continue
					}
					selector, ok := field.Type.(*ast.SelectorExpr)
					if !ok {
						continue
					}
					pkgIdent, ok := selector.X.(*ast.Ident)
					if !ok || pkgIdent.Name != "service" {
						continue
					}
					for _, name := range field.Names {
						fieldServiceInterfaces[name.Name] = selector.Sel.Name
					}
				}
			}
		}
	}

	for _, filePath := range files {
		file, err := parser.ParseFile(fset, filePath, nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", filePath, err)
		}

		for _, decl := range file.Decls {
			funcDecl, ok := decl.(*ast.FuncDecl)
			if !ok || funcDecl.Recv == nil || funcDecl.Body == nil {
				continue
			}
			if !isHandlerReceiver(funcDecl.Recv) {
				continue
			}

			serviceCalls := make(map[string]struct{})
			ast.Inspect(funcDecl.Body, func(n ast.Node) bool {
				callExpr, ok := n.(*ast.CallExpr)
				if !ok {
					return true
				}

				outerSel, ok := callExpr.Fun.(*ast.SelectorExpr)
				if !ok {
					return true
				}

				innerSel, ok := outerSel.X.(*ast.SelectorExpr)
				if !ok {
					return true
				}

				receiver, ok := innerSel.X.(*ast.Ident)
				if !ok || receiver.Name != "h" {
					return true
				}

				serviceInterface, ok := fieldServiceInterfaces[innerSel.Sel.Name]
				if !ok {
					return true
				}

				serviceCalls[serviceInterface+"."+outerSel.Sel.Name] = struct{}{}
				return true
			})

			if len(serviceCalls) == 0 {
				continue
			}
			methods := make([]string, 0, len(serviceCalls))
			for serviceMethod := range serviceCalls {
				methods = append(methods, serviceMethod)
			}
			sort.Strings(methods)
			handlerMethods[funcDecl.Name.Name] = methods
		}
	}

	return handlerMethods, nil
}

func isHandlerReceiver(recv *ast.FieldList) bool {
	if recv == nil || len(recv.List) == 0 {
		return false
	}

	typeExpr := recv.List[0].Type
	if starExpr, ok := typeExpr.(*ast.StarExpr); ok {
		typeExpr = starExpr.X
	}

	ident, ok := typeExpr.(*ast.Ident)
	return ok && ident.Name == "Handler"
}

func operationIDToHandlerMethod(operationID string) string {
	if operationID == "" {
		return ""
	}

	r, size := utf8.DecodeRuneInString(operationID)
	if r == utf8.RuneError {
		return operationID
	}
	return string(unicode.ToUpper(r)) + operationID[size:]
}

type methodsFileOperation struct {
	OperationID string                         `yaml:"operationId"`
	Responses   map[string]methodsFileResponse `yaml:"responses"`
	// Security is a pointer so an absent key is distinguishable from
	// `security: []`: absent inherits the root spec's requirement, empty
	// overrides it to none.
	Security *[]map[string][]string `yaml:"security"`
}

type methodsFileResponse struct {
	Ref     string `yaml:"$ref"`
	Content map[string]struct {
		Schema struct {
			Ref string `yaml:"$ref"`
		} `yaml:"schema"`
	} `yaml:"content"`
}

// rootSecurityRequired reports whether the root spec declares a non-empty
// default security requirement, which operations inherit unless they override
// it with a `security:` key of their own.
func rootSecurityRequired(openapiBasePath string) (bool, error) {
	content, err := os.ReadFile(filepath.Join(openapiBasePath, "openapi-spec.yaml"))
	if err != nil {
		return false, err
	}

	var root struct {
		Security []map[string][]string `yaml:"security"`
	}
	if err := yaml.Unmarshal(content, &root); err != nil {
		return false, fmt.Errorf("parse openapi-spec.yaml: %w", err)
	}
	return len(root.Security) > 0, nil
}

func discoverEndpointsWithDefaultErrorResponse(openapiBasePath string) ([]endpointOperation, error) {
	endpointsRoot := filepath.Join(openapiBasePath, "endpoints")
	var endpoints []endpointOperation

	rootRequiresAuth, err := rootSecurityRequired(openapiBasePath)
	if err != nil {
		return nil, err
	}

	err = filepath.WalkDir(endpointsRoot, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() || filepath.Base(path) != "methods.yaml" {
			return nil
		}

		ops, err := parseMethodsFile(path)
		if err != nil {
			return err
		}

		for _, op := range ops {
			if op.OperationID == "" {
				continue
			}
			if !hasDefaultErrorDetailsRef(op) {
				continue
			}
			requiresAuth := rootRequiresAuth
			if op.Security != nil {
				requiresAuth = len(*op.Security) > 0
			}
			endpoints = append(endpoints, endpointOperation{
				operationID:  op.OperationID,
				yamlPath:     path,
				requiresAuth: requiresAuth,
			})
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	sort.Slice(endpoints, func(i, j int) bool {
		if endpoints[i].yamlPath == endpoints[j].yamlPath {
			return endpoints[i].operationID < endpoints[j].operationID
		}
		return endpoints[i].yamlPath < endpoints[j].yamlPath
	})

	return endpoints, nil
}

func parseMethodsFile(path string) ([]methodsFileOperation, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var raw map[string]methodsFileOperation
	if err := yaml.Unmarshal(content, &raw); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}

	methods := map[string]struct{}{
		"get": {}, "put": {}, "post": {}, "delete": {},
		"options": {}, "head": {}, "patch": {}, "trace": {},
	}

	ops := make([]methodsFileOperation, 0, len(raw))
	for key, op := range raw {
		if _, ok := methods[strings.ToLower(key)]; !ok {
			continue
		}
		ops = append(ops, op)
	}

	return ops, nil
}

func hasDefaultErrorDetailsRef(op methodsFileOperation) bool {
	defaultResponse, ok := op.Responses["default"]
	if !ok {
		return false
	}

	if strings.HasSuffix(normalizePath(defaultResponse.Ref), "-error-response.yaml") {
		return true
	}

	for _, media := range defaultResponse.Content {
		ref := normalizePath(media.Schema.Ref)
		if strings.HasSuffix(ref, "components/error-details.yaml") {
			return true
		}
	}

	return false
}

func normalizePath(p string) string {
	return strings.ReplaceAll(p, "\\", "/")
}

type errorInfo struct {
	code    string
	message string
}

// buildErrorMapping parses the domain package and extracts error function -> error info mappings
func buildErrorMapping(domainPath string) map[string]errorInfo {
	mapping := make(map[string]errorInfo)

	fset := token.NewFileSet()
	domainFiles, err := filepath.Glob(filepath.Join(domainPath, "*.go"))

	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Error listing domain files: %v\n", err)
		os.Exit(1)
	}

	files := make([]*ast.File, 0, len(domainFiles))
	for _, filename := range domainFiles {
		if strings.HasSuffix(filename, "_test.go") {
			continue
		}

		file, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
		if err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "Error parsing %s: %v\n", filename, err)
			continue
		}
		files = append(files, file)
	}

	prefixes := extractResourcePrefixes(files)

	for _, file := range files {
		ast.Inspect(file, func(n ast.Node) bool {
			funcDecl, ok := n.(*ast.FuncDecl)
			if !ok || !strings.HasPrefix(funcDecl.Name.Name, "Err") || funcDecl.Body == nil {
				return true
			}

			for _, stmt := range funcDecl.Body.List {
				retStmt, ok := stmt.(*ast.ReturnStmt)
				if !ok {
					continue
				}

				for _, result := range retStmt.Results {
					if callExpr, ok := result.(*ast.CallExpr); ok {
						if ident, ok := callExpr.Fun.(*ast.Ident); ok && ident.Name == "newError" {
							if len(callExpr.Args) >= 2 {
								code := extractCodeArgument(callExpr.Args[0], prefixes)
								message := ""
								if msgLit, ok := callExpr.Args[1].(*ast.BasicLit); ok {
									message = strings.Trim(msgLit.Value, `"`)
								}
								if code != "" {
									mapping["domain."+funcDecl.Name.Name] = errorInfo{
										code:    code,
										message: message,
									}
								}
							}
						}
					}
				}
			}

			return true
		})
	}

	return mapping
}

func extractResourcePrefixes(files []*ast.File) map[string]string {
	prefixes := make(map[string]string)

	for _, file := range files {
		for _, decl := range file.Decls {
			// Resource prefixes are normally const, but TokenPrefix is a var —
			// accept both, or its error codes go missing entirely.
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || (genDecl.Tok != token.CONST && genDecl.Tok != token.VAR) {
				continue
			}

			for _, spec := range genDecl.Specs {
				valueSpec, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}

				for i, name := range valueSpec.Names {
					if valueSpec.Type != nil {
						if ident, ok := valueSpec.Type.(*ast.Ident); ok && ident.Name == "ResourcePrefix" {
							if i < len(valueSpec.Values) {
								if lit, ok := valueSpec.Values[i].(*ast.BasicLit); ok {
									value := strings.Trim(lit.Value, `"`)
									prefixes[name.Name] = value
								}
							}
						}
					}
				}
			}
		}
	}

	return prefixes
}

func extractCodeArgument(arg ast.Expr, prefixes map[string]string) string {
	if lit, ok := arg.(*ast.BasicLit); ok {
		return strings.Trim(lit.Value, `"`)
	}

	if callExpr, ok := arg.(*ast.CallExpr); ok {
		if selExpr, ok := callExpr.Fun.(*ast.SelectorExpr); ok {
			if selExpr.Sel.Name == "ErrorCodePrefix" {
				if ident, ok := selExpr.X.(*ast.Ident); ok {
					prefixValue, ok := prefixes[ident.Name]
					if !ok {
						return ""
					}

					if len(callExpr.Args) > 0 {
						if suffixLit, ok := callExpr.Args[0].(*ast.BasicLit); ok {
							suffix := strings.Trim(suffixLit.Value, `"`)
							return prefixValue + "." + suffix
						}
					}
				}
			}
		}
	}

	return ""
}

type serviceMethod struct {
	interfaceName string
	methodName    string
	errorFuncs    []string
}

// boundaryErrors are reachable on every operation no matter what the service
// raises: domainErrorDetails in internal/api falls back to domain.ErrInternal
// for anything that is not a domain.Error, so a storage or library failure
// surfaces as `internal` on any endpoint. The service-level analysis cannot see
// that — it is a property of the HTTP boundary — so it is added here.
var boundaryErrors = []string{"domain.ErrInternal"}

// transportErrors are raised by OgenErrorHandler for a request that never
// reaches a handler at all, so no walk of the handler call graph can see them:
// a request whose params or body will not decode is rejected before dispatch,
// as req.invalid.
//
// Omitting one is not cosmetic: the generated client discriminates the error
// response on `code`, so a code missing from an operation's oneOf makes a real
// response fail to decode instead of surfacing as the error it is.
//
// Unlike boundaryErrors these are added per operation rather than per service
// method, because they are the transport's to raise, not the service's. Folding
// them into the service sets would report every hand-written "errors:" comment
// as drifted for omitting something no service can return.
var transportErrors = []string{
	"domain.ErrRequestInvalid",
}

// securityErrors join transportErrors for operations that declare a security
// requirement: the generated middleware rejects a failed one before dispatch,
// as auth.unauthorized. An operation with `security: []` — the health probes,
// the pre-authentication flow steps — has no requirement to fail, so listing
// the code there would advertise an answer it cannot give. Over-advertising is
// harmless to decode, but it costs the typed models the precision that makes
// them worth generating.
//
// A handler that authenticates by hand still contributes the code through the
// call-graph walk, so gating here only drops the transport's contribution.
var securityErrors = []string{
	"domain.ErrAuthUnauthorized",
}

// methodErrorsFromAnalysis adapts the inferred error sets to the shape the
// generation loop consumes.
func methodErrorsFromAnalysis(analyzed map[string]erroranalysis.Method) map[string]serviceMethod {
	out := make(map[string]serviceMethod, len(analyzed))
	for key, m := range analyzed {
		if m.Unimplemented {
			fmt.Printf("⚠️  %s has no implementation to analyze\n", key)
			continue
		}

		codes := slices.Clone(m.Errors)
		for _, code := range boundaryErrors {
			if !slices.Contains(codes, code) {
				codes = append(codes, code)
			}
		}
		sort.Strings(codes)

		out[key] = serviceMethod{
			interfaceName: m.Interface,
			methodName:    m.Name,
			errorFuncs:    codes,
		}
	}
	return out
}

// reportCommentDrift prints where a hand-written "errors:" doc comment no
// longer matches what the implementation can actually return. The comments are
// advisory now, so this is a nudge to fix (or delete) them — not a failure.
func reportCommentDrift(declared, inferred map[string]serviceMethod) {
	keys := make([]string, 0, len(declared))
	for key := range declared {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	drifted := 0
	for _, key := range keys {
		want := declared[key].errorFuncs
		analyzed, ok := inferred[key]
		if !ok {
			// Skipped as unimplemented, so there is no inferred set to compare
			// against — reporting every declared code as unreturnable here would
			// only teach the reader to distrust the report.
			fmt.Printf("ℹ️  %s: not analyzed, doc comment not checked\n", key)
			continue
		}
		got := analyzed.errorFuncs

		var missing, extra []string
		for _, code := range want {
			if !slices.Contains(got, code) {
				extra = append(extra, code)
			}
		}
		for _, code := range got {
			if !slices.Contains(want, code) {
				missing = append(missing, code)
			}
		}
		if len(missing) == 0 && len(extra) == 0 {
			continue
		}

		drifted++
		fmt.Printf("⚠️  %s: doc comment is out of date\n", key)
		if len(missing) > 0 {
			fmt.Printf("      code returns but comment omits: %s\n", strings.Join(missing, ", "))
		}
		if len(extra) > 0 {
			fmt.Printf("      comment claims but code cannot return: %s\n", strings.Join(extra, ", "))
		}
	}

	if drifted > 0 {
		fmt.Printf("💡 %d service method comment(s) drifted; the spec follows the code\n", drifted)
	}
}

// parseAllServiceFiles scans all .go files in the service directory and extracts
// service interface methods with error documentation.
func parseAllServiceFiles(servicePath string) map[string]serviceMethod {
	allMethods := make(map[string]serviceMethod)

	files, err := filepath.Glob(filepath.Join(servicePath, "*.go"))
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Error listing service files: %v\n", err)
		os.Exit(1)
	}

	errorPattern := regexp.MustCompile(`errors:\s*(.+)`)

	for _, filename := range files {
		if strings.HasSuffix(filename, "_test.go") {
			continue
		}

		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
		if err != nil {
			_, _ = fmt.Fprintf(os.Stderr, "Error parsing %s: %v\n", filename, err)
			continue
		}

		ast.Inspect(file, func(n ast.Node) bool {
			typeSpec, ok := n.(*ast.TypeSpec)
			if !ok {
				return true
			}

			iface, ok := typeSpec.Type.(*ast.InterfaceType)
			if !ok || !strings.HasSuffix(typeSpec.Name.Name, "Service") {
				return true
			}

			interfaceName := typeSpec.Name.Name

			for _, method := range iface.Methods.List {
				if len(method.Names) == 0 || method.Doc == nil {
					continue
				}

				methodName := method.Names[0].Name

				for _, comment := range method.Doc.List {
					if matches := errorPattern.FindStringSubmatch(comment.Text); len(matches) > 1 {
						var errs []string
						for _, e := range strings.Split(matches[1], ",") {
							errs = append(errs, strings.TrimSpace(e))
						}

						key := interfaceName + "." + methodName
						allMethods[key] = serviceMethod{
							interfaceName: interfaceName,
							methodName:    methodName,
							errorFuncs:    errs,
						}
						break
					}
				}
			}

			return true
		})
	}

	return allMethods
}
