import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

/** Absolute path to `apps/preview-registry/`. */
const APP_ROOT = resolve(import.meta.dirname, "..");

/** Absolute path to the workspace root that owns `packages/*`. */
const REPO_ROOT = resolve(APP_ROOT, "..", "..");

/** Directory the local server reads tarballs out of — same layout as the prod build. */
const SNAPSHOT_ROOT = join(APP_ROOT, ".snapshots");

interface WorkspaceManifest {
  readonly name: string;
  readonly version: string;
  readonly private?: boolean;
}

/**
 * Discover every publishable workspace package directory under
 * `packages/`.
 *
 * Mirrors `scripts/publish-on-deploy.ts` exactly — directories without
 * a `package.json` or flagged `private: true` are skipped — so the
 * local round-trip stages precisely the set the production build
 * publishes, and the list can never drift from what actually exists in
 * the repo.
 */
const listPublishablePackageDirectories = (): readonly string[] =>
  readdirSync(join(REPO_ROOT, "packages"))
    .map((entry) => `packages/${entry}`)
    .filter((packageDirectory) => {
      try {
        const packageJsonPath = join(REPO_ROOT, packageDirectory, "package.json");
        if (!readdirSync(join(REPO_ROOT, packageDirectory)).includes("package.json")) {
          return false;
        }
        const manifest = JSON.parse(readFileSync(packageJsonPath, "utf8")) as WorkspaceManifest;
        return manifest.private !== true;
      } catch {
        return false;
      }
    });

/**
 * Pack every workspace package into the local FS snapshot store so the
 * dev server has something to serve.
 *
 * Mirrors the shape of what
 * {@link ../api/registry.ts | the Vercel function bundle} ships in
 * production, but skips the snapshot version-stamping step — each
 * package keeps whatever version is currently in its package.json,
 * so iterating on schema or routing locally is fast.
 */
const stageLocal = async (): Promise<void> => {
  rmSync(SNAPSHOT_ROOT, { recursive: true, force: true });

  const packageDirectories = listPublishablePackageDirectories();

  const stagingDirectory = mkdtempSync(join(tmpdir(), "stage-local-"));
  try {
    for (const packageDirectory of packageDirectories) {
      console.log(`packing ${packageDirectory}`);
      execFileSync("corepack", ["pnpm", "pack", "--pack-destination", stagingDirectory], {
        cwd: join(REPO_ROOT, packageDirectory),
        stdio: "inherit",
      });
    }

    const manifests: readonly { path: string; manifest: WorkspaceManifest }[] =
      packageDirectories.map((packageDirectory) => {
        const packageJsonPath = join(REPO_ROOT, packageDirectory, "package.json");
        return {
          path: packageJsonPath,
          manifest: JSON.parse(readFileSync(packageJsonPath, "utf8")) as WorkspaceManifest,
        };
      });

    const bundled = readdirSync(stagingDirectory)
      .filter((file) => file.endsWith(".tgz"))
      .reduce<readonly { name: string; version: string; sizeBytes: number }[]>(
        (accumulator, tarballFile) => {
          const tarballBody = readFileSync(join(stagingDirectory, tarballFile));
          const matchedManifest = manifests.find(({ manifest }) =>
            tarballFile.startsWith(manifest.name.replace("@", "").replace("/", "-") + "-"),
          )?.manifest;
          if (!matchedManifest) {
            console.warn(`skip ${tarballFile} — no matching workspace package`);
            return accumulator;
          }
          const destination = join(SNAPSHOT_ROOT, matchedManifest.name, "-", tarballFile);
          mkdirSync(resolve(destination, ".."), { recursive: true });
          writeFileSync(destination, tarballBody);
          console.log(`  bundled ${matchedManifest.name} → ${destination}`);
          return [
            ...accumulator,
            {
              name: matchedManifest.name,
              version: matchedManifest.version,
              sizeBytes: tarballBody.length,
            },
          ];
        },
        [],
      );

    const manifestPath = join(APP_ROOT, "src", "snapshot-manifest.ts");
    const manifestSource =
      "// AUTO-GENERATED by scripts/stage-local.ts. Do not edit.\n" +
      "import type { PackageRow } from './landing.js'\n\n" +
      "export const SNAPSHOT_PACKAGES: readonly PackageRow[] = " +
      JSON.stringify(bundled, null, 2) +
      " as const\n";
    writeFileSync(manifestPath, manifestSource);

    console.log(`\nstaged into ${SNAPSHOT_ROOT}`);
    console.log("now run:  corepack pnpm dev");
  } finally {
    rmSync(stagingDirectory, { recursive: true, force: true });
  }
};

await stageLocal();
