/**
 * Builds the public token surfaces of `@zitadel/design-tokens`
 * from `src/generated/figma.tokens.json` (Figma-published primitives +
 * semantic tokens) and `src/overrides.ts` (typography, motion, focus,
 * breakpoints, container widths).
 *
 * Emits three files into `src/generated/`:
 *
 *   tokens.css      — :root + [data-theme="dark"] + reserved
 *                     [data-theme="light"] selectors with `--zl-*` variables.
 *   tokens.ts       — typed `tokens` const + named groups for JS consumers.
 *   tailwind.css    — Tailwind v4 `@theme` block aliasing `--color-zl-*`,
 *                     `--spacing-zl-*` etc. so React consumers can write
 *                     `text-zl-text-primary` and `bg-zl-surface-black`.
 *
 * Run: `moon run design-tokens:generate`
 *
 * The output is intentionally deterministic — same JSON in, byte-identical
 * files out — so the sync-from-figma snapshot test catches drift cleanly.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import figmaTokens from "../src/generated/figma.tokens.json" with { type: "json" };
import { overrides } from "../src/overrides.ts";

type Hex = string;
type Px = number;
type PrimitiveRef = { primitive: string };
type SemanticValue = Hex | PrimitiveRef;
/** A semantic colour that resolves differently per theme mode. */
type ModeValue = { dark: SemanticValue; light?: SemanticValue };
type ColorToken = SemanticValue | ModeValue;

interface FigmaTokensFile {
  $source: Record<string, unknown>;
  primitives: {
    color: Record<string, Hex | Record<string, Hex>>;
    spacing: Record<string, Px>;
    cornerRadius: Record<string, Px>;
  };
  /** Grid/layout primitives (columns, gutter, margin) owned by Figma's `layout/*` collection. */
  layout?: Record<string, number>;
  tokens: {
    color: Record<string, Record<string, ColorToken>>;
  };
}

const figma = figmaTokens as unknown as FigmaTokensFile;
const ROOT = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(ROOT, "../src/generated");

/** Resolve `{ "primitive": "color.gray.50" }` into the concrete hex. */
function resolvePrimitive(ref: PrimitiveRef): Hex {
  const parts = ref.primitive.split(".");
  let cursor: unknown = figma.primitives;
  for (const part of parts) {
    if (cursor === null || typeof cursor !== "object") {
      throw new Error(`Cannot descend into ${ref.primitive} at ${part}: parent is not an object`);
    }
    cursor = (cursor as Record<string, unknown>)[part];
    if (cursor === undefined) {
      throw new Error(`Primitive reference ${ref.primitive} not found (failed at ${part})`);
    }
  }
  if (typeof cursor !== "string") {
    throw new Error(`Primitive reference ${ref.primitive} did not resolve to a string`);
  }
  return cursor;
}

function resolveSemantic(value: SemanticValue): Hex {
  return typeof value === "string" ? value : resolvePrimitive(value);
}

function isModeValue(value: ColorToken): value is ModeValue {
  return typeof value === "object" && value !== null && "dark" in value;
}

/** Convert a Figma slash path into the `--zl-*` CSS variable name. */
function cssVarName(category: string, ...segments: string[]): string {
  const parts = [category, ...segments]
    .join("/")
    .toLowerCase()
    .replaceAll(" ", "-")
    .replaceAll("/", "-");
  return `--zl-${parts}`;
}

function pxToRem(px: number): string {
  return `${px / 16}rem`;
}

/** Generated banner so editors don't try to hand-edit the output. */
const BANNER = `/* AUTOGENERATED by packages/design-tokens/scripts/build.ts — do not edit by hand.\n   Source: src/generated/figma.tokens.json + src/overrides.ts.\n   Re-run: moon run design-tokens:generate */\n\n`;
const TS_BANNER = `// AUTOGENERATED by packages/design-tokens/scripts/build.ts — do not edit by hand.\n// Source: src/generated/figma.tokens.json + src/overrides.ts.\n// Re-run: moon run design-tokens:generate\n\n`;

interface BuildResult {
  css: string;
  ts: string;
  tailwind: string;
}

function build(): BuildResult {
  /** [zl-var-name, resolved CSS value] tuples for `:root` (dark), in emit order. */
  const cssVars: Array<[string, string]> = [];
  /** [zl-var-name, resolved CSS value] tuples that differ under `[data-theme="light"]`. */
  const lightVars: Array<[string, string]> = [];
  /** Mirror structure for the typed TS `tokens` export (resolved dark values). */
  const tsTree: Record<string, unknown> = { color: {}, spacing: {}, radius: {}, font: {}, motion: {}, focus: {}, breakpoint: {}, container: {}, layout: {} };
  /** Mirror structure for the `cssVars` export — `var(--zl-…)` strings consumers compose into styles. */
  const refTree: Record<string, unknown> = { color: {}, spacing: {}, radius: {}, font: {}, motion: {}, focus: {}, breakpoint: {}, container: {}, layout: {} };

  const push = (cssVar: string, value: string, valuePath: string[], light?: string): void => {
    cssVars.push([cssVar, value]);
    if (light !== undefined && light !== value) lightVars.push([cssVar, light]);
    setDeep(tsTree, valuePath, value);
    setDeep(refTree, valuePath, `var(${cssVar})`);
  };

  // ---- semantic colours (mode-aware: single value = mode-independent, {dark,light} = themed) ----
  for (const [group, members] of Object.entries(figma.tokens.color)) {
    for (const [name, raw] of Object.entries(members)) {
      const cssVar = cssVarName("color", group, name);
      const path = ["color", toCamel(group), toCamel(name)];
      if (isModeValue(raw)) {
        const light = raw.light !== undefined ? resolveSemantic(raw.light) : undefined;
        push(cssVar, resolveSemantic(raw.dark), path, light);
      } else {
        push(cssVar, resolveSemantic(raw), path);
      }
    }
  }

  // ---- primitive colours (re-exposed for atoms that need the raw shade) ----
  for (const [group, members] of Object.entries(overrides.colorPrimitive)) {
    for (const [name, value] of Object.entries(members)) {
      push(cssVarName("color", group, name), value, ["color", group, name]);
    }
  }

  // ---- spacing (in rem) — sorted by step number so 01..16 always emit in order ----
  for (const [step, px] of sortedNumeric(figma.primitives.spacing)) {
    push(cssVarName("spacing", step), pxToRem(px), ["spacing", step]);
  }

  // ---- corner radius (in rem) ----
  for (const [name, px] of Object.entries(figma.primitives.cornerRadius)) {
    push(cssVarName("radius", name), pxToRem(px), ["radius", name]);
  }

  // ---- overrides: font ----
  for (const [name, value] of Object.entries(overrides.font.family)) {
    push(cssVarName("font-family", name), value, ["font", "family", name]);
  }

  // ---- overrides: motion ----
  for (const [name, value] of Object.entries(overrides.motion.duration)) {
    push(cssVarName("duration", name), value, ["motion", "duration", name]);
  }
  for (const [name, value] of Object.entries(overrides.motion.easing)) {
    push(cssVarName("easing", name), value, ["motion", "easing", name]);
  }

  // ---- overrides: focus ----
  push(cssVarName("focus", "width"), overrides.focus.width, ["focus", "width"]);
  push(cssVarName("focus", "offset"), overrides.focus.offset, ["focus", "offset"]);
  push(cssVarName("focus", "color"), resolveFocusColor(), ["focus", "color"]);

  // ---- overrides: breakpoints ----
  for (const [name, value] of Object.entries(overrides.breakpoint)) {
    push(cssVarName("breakpoint", name), value, ["breakpoint", name]);
  }

  // ---- overrides: container max-widths ----
  for (const [name, value] of Object.entries(overrides.container)) {
    push(cssVarName("container", kebab(name)), value, ["container", name]);
  }

  // ---- layout: grid columns / gutter / margin (columns unitless, spacing in rem) ----
  for (const [name, value] of Object.entries(figma.layout ?? {})) {
    const cssValue = name === "columns" ? String(value) : pxToRem(value);
    push(cssVarName("layout", name), cssValue, ["layout", name]);
  }

  const css = emitCss(cssVars, lightVars);
  return {
    css,
    ts: emitTs(tsTree, refTree, css),
    tailwind: emitTailwind(cssVars),
  };
}

function setDeep(target: Record<string, unknown>, path: string[], value: string): void {
  let cursor: Record<string, unknown> = target;
  for (let i = 0; i < path.length - 1; i++) {
    const key = path[i] ?? "";
    if (typeof cursor[key] !== "object" || cursor[key] === null) {
      cursor[key] = {};
    }
    cursor = cursor[key] as Record<string, unknown>;
  }
  cursor[path[path.length - 1] ?? ""] = value;
}

function resolveFocusColor(): Hex {
  const parts = overrides.focus.colorToken.split("/").map((p) => p.trim().toLowerCase().replaceAll(" ", "-"));
  const [category, group, ...nameParts] = parts;
  if (category !== "color" || !group) {
    throw new Error(`overrides.focus.colorToken must look like "color/<group>/<name>", got ${overrides.focus.colorToken}`);
  }
  const groupTokens = figma.tokens.color[group];
  if (!groupTokens) {
    throw new Error(`overrides.focus.colorToken ${overrides.focus.colorToken} references unknown group ${group}`);
  }
  const name = nameParts.join("-");
  const raw = groupTokens[name];
  if (!raw) {
    throw new Error(`overrides.focus.colorToken ${overrides.focus.colorToken} not found in figma.tokens.json (group=${group}, name=${name})`);
  }
  return resolveSemantic(raw);
}

function emitCss(vars: Array<[string, string]>, lightVars: Array<[string, string]>): string {
  const body = vars.map(([k, v]) => `  ${k}: ${v};`).join("\n");
  const root = `:root,\n[data-theme="dark"] {\n${body}\n}\n`;
  // Light mode only overrides the tokens that actually differ; everything
  // else inherits the dark `:root` values through the cascade.
  const lightBody = lightVars.map(([k, v]) => `  ${k}: ${v};`).join("\n");
  const light = lightVars.length
    ? `\n[data-theme="light"] {\n${lightBody}\n}\n`
    : `\n[data-theme="light"] {\n}\n`;
  return `${BANNER}${root}${light}`;
}

function emitTs(values: Record<string, unknown>, refs: Record<string, unknown>, css: string): string {
  // We embed the full CSS as a string export so consumers that can't pull
  // the raw .css file (a Lit shadow root, a Node test harness, an inline
  // <style> in an SSR'd page) still get the canonical base token layer.
  // The orchestrator uses this to seed a constructable stylesheet on its
  // own shadow root so atoms work even when the host page didn't
  // `@import` tokens.css.
  const body =
    `export const tokens = ${JSON.stringify(values, null, 2)} as const;\n\n` +
    `export const cssVars = ${JSON.stringify(refs, null, 2)} as const;\n\n` +
    `export const tokensCss = ${JSON.stringify(css)};\n\n` +
    `export type Tokens = typeof tokens;\nexport type CssVars = typeof cssVars;\n`;
  return `${TS_BANNER}${body}`;
}

/**
 * Tailwind v4 lets us declare a `@theme` block that aliases utility classes
 * to CSS variables. We prefix every alias with `zl-` so consumers writing
 * Tailwind in apps/console never collide with their own tokens, and so a
 * code reviewer can tell which classes come from the design system at a
 * glance (`bg-zl-surface-black` vs `bg-slate-900`).
 */
function emitTailwind(vars: Array<[string, string]>): string {
  const lines: string[] = [];
  for (const [cssVar] of vars) {
    const utilityName = cssVar.replace(/^--zl-/, "");
    const mapped = mapToTailwindNamespace(utilityName);
    if (!mapped) continue;
    lines.push(`  --${mapped.prefix}-zl-${mapped.suffix}: var(${cssVar});`);
  }
  return `${BANNER}@import "./tokens.css";\n\n@theme {\n${lines.join("\n")}\n}\n`;
}

/**
 * Map a `{category}-{...}` name to its Tailwind v4 namespace prefix and
 * leftover suffix. Categories not listed here (focus, container) intentionally
 * fall through — consumers reach for the CSS variable directly.
 */
function mapToTailwindNamespace(utilityName: string): { prefix: string; suffix: string } | null {
  const knownCategories: Array<[string, string]> = [
    ["color-", "color"],
    ["spacing-", "spacing"],
    ["radius-", "radius"],
    ["font-family-", "font-family"],
    ["duration-", "duration"],
    ["easing-", "ease"],
    ["breakpoint-", "breakpoint"],
  ];
  for (const [match, prefix] of knownCategories) {
    if (utilityName.startsWith(match)) {
      return { prefix, suffix: utilityName.slice(match.length) };
    }
  }
  return null;
}

function toCamel(s: string): string {
  return s.replace(/[-_/](.)/g, (_, ch) => ch.toUpperCase());
}
function kebab(s: string): string {
  return s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
}
function sortedNumeric<V>(record: Record<string, V>): Array<[string, V]> {
  return Object.entries(record).sort(([a], [b]) => Number(a) - Number(b));
}

async function main(): Promise<void> {
  const result = build();
  await mkdir(OUT_DIR, { recursive: true });
  await Promise.all([
    writeFile(resolve(OUT_DIR, "tokens.css"), result.css),
    writeFile(resolve(OUT_DIR, "tokens.ts"), result.ts),
    writeFile(resolve(OUT_DIR, "tailwind.css"), result.tailwind),
  ]);
  // eslint-disable-next-line no-console
  console.log(`design-tokens: wrote tokens.css, tokens.ts, tailwind.css to ${OUT_DIR}`);
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
