// gen_event_schemas generates per-event-type OpenAPI schemas and the Event
// oneOf union with discriminator mapping from domain.EventType constants.
//
// Paths are relative to this generator:
//   - Domain: ../../../internal/domain/event.go
//   - Output: ../../openapi/endpoints/events/
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"unicode"
)

// payloadByEventType maps every domain EventType string constant to a payload
// schema file under endpoints/events/payloads/. Shared payloads are intentional.
var payloadByEventType = map[string]string{
	"request.api": "request-api-payload.yaml",

	"project.created": "project-created-payload.yaml",
	"project.updated": "project-updated-payload.yaml",
	"project.deleted": "empty-event-payload.yaml",

	"user.created":       "user-created-payload.yaml",
	"user.updated":       "user-updated-payload.yaml",
	"user.create.failed": "user-create-failed-payload.yaml",
	"user.deactivated":   "user-deactivated-payload.yaml",
	"user.deleted":       "empty-event-payload.yaml",

	"team.created":            "team-created-payload.yaml",
	"team.updated":            "team-updated-payload.yaml",
	"team.deactivated":        "empty-event-payload.yaml",
	"team.membership.updated": "team-membership-updated-payload.yaml",

	"auth.token.issued":  "auth-token-issued-payload.yaml",
	"auth.token.revoked": "empty-event-payload.yaml",

	"session.established": "session-established-payload.yaml",
	"session.deleted":     "session-deleted-payload.yaml",
	"session.expired":     "empty-event-payload.yaml",

	"auth.attempt.created":    "auth-attempt-created-payload.yaml",
	"auth.attempt.handed_off": "auth-attempt-handed-off-payload.yaml",
	"auth.check.failed":       "auth-check-payload.yaml",
	"auth.check.succeeded":    "auth-check-payload.yaml",

	"claim.challenge_created": "empty-event-payload.yaml",
	"claim.completed":         "claim-completed-payload.yaml",

	"flowdef.created": "flowdef-payload.yaml",
	"flowdef.updated": "flowdef-payload.yaml",
	"flowdef.deleted": "empty-event-payload.yaml",

	"schema.created": "schema-payload.yaml",
	"schema.deleted": "schema-payload.yaml",

	"branding.created": "branding-created-payload.yaml",

	"authz.granted": "authz-granted-payload.yaml",
	"authz.revoked": "authz-revoked-payload.yaml",

	"auth.factor.password.set":     "auth-factor-payload.yaml",
	"auth.factor.password.removed": "auth-factor-payload.yaml",
	"auth.factor.totp.enrolled":    "auth-factor-payload.yaml",
	"auth.factor.totp.removed":     "auth-factor-payload.yaml",
	"auth.factor.passkey.enrolled": "auth-factor-payload.yaml",
	"auth.factor.passkey.removed":  "auth-factor-payload.yaml",
	"auth.factor.recovery.created": "auth-factor-payload.yaml",
	"auth.factor.recovery.removed": "auth-factor-payload.yaml",
}

func main() {
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		fmt.Fprintln(os.Stderr, "Failed to get current file path")
		os.Exit(1)
	}
	generatorDir := filepath.Dir(filename)
	domainEventPath := filepath.Join(generatorDir, "../../../internal/domain/event.go")
	outDir := filepath.Join(generatorDir, "../../openapi/endpoints/events")
	typesDir := filepath.Join(outDir, "types")
	payloadsDir := filepath.Join(outDir, "payloads")

	eventTypes, err := extractEventTypes(domainEventPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "extract event types: %v\n", err)
		os.Exit(1)
	}
	if err := validateMappings(eventTypes, payloadsDir); err != nil {
		fmt.Fprintf(os.Stderr, "payload map: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(typesDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir types: %v\n", err)
		os.Exit(1)
	}

	// Remove previously generated type files so renames/deletes stay clean.
	entries, err := os.ReadDir(typesDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read types dir: %v\n", err)
		os.Exit(1)
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".yaml") {
			continue
		}
		_ = os.Remove(filepath.Join(typesDir, e.Name()))
	}

	sort.Strings(eventTypes)
	for _, et := range eventTypes {
		slug := eventTypeSlug(et)
		title := eventTypeTitle(et)
		payloadFile := payloadByEventType[et]
		content := fmt.Sprintf(`# Code generated by gen_event_schemas; DO NOT EDIT.
title: %s
description: |
  Wide event with event_type=%s.
allOf:
  - $ref: ../event-base.yaml
  - type: object
    required:
      - event_type
      - payload
    properties:
      event_type:
        type: string
        const: %s
      payload:
        $ref: ../payloads/%s
`, title, et, et, payloadFile)
		path := filepath.Join(typesDir, slug+".yaml")
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
			os.Exit(1)
		}
	}

	if err := writeEventUnion(outDir, eventTypes); err != nil {
		fmt.Fprintf(os.Stderr, "write event.yaml: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✅ Generated %d event type schemas in %s\n", len(eventTypes), typesDir)
}

func validateMappings(eventTypes []string, payloadsDir string) error {
	known := make(map[string]struct{}, len(eventTypes))
	for _, et := range eventTypes {
		known[et] = struct{}{}
		payloadFile, ok := payloadByEventType[et]
		if !ok {
			return fmt.Errorf("missing payload mapping for event type %q", et)
		}
		if _, err := os.Stat(filepath.Join(payloadsDir, payloadFile)); err != nil {
			return fmt.Errorf("payload file for %q: %w", et, err)
		}
	}
	for et := range payloadByEventType {
		if _, ok := known[et]; !ok {
			return fmt.Errorf("payload map has unknown event type %q (not in domain.EventType constants)", et)
		}
	}
	return nil
}

func writeEventUnion(outDir string, eventTypes []string) error {
	var buf bytes.Buffer
	buf.WriteString(`# Code generated by gen_event_schemas; DO NOT EDIT.
description: |
  Discriminated wide-event union (ADR 048 / ADR 049). Clients select the
  member via event_type; each member carries a typed payload.
oneOf:
`)
	for _, et := range eventTypes {
		fmt.Fprintf(&buf, "  - $ref: types/%s.yaml\n", eventTypeSlug(et))
	}
	buf.WriteString(`discriminator:
  propertyName: event_type
  mapping:
`)
	for _, et := range eventTypes {
		fmt.Fprintf(&buf, "    %s: types/%s.yaml\n", et, eventTypeSlug(et))
	}
	return os.WriteFile(filepath.Join(outDir, "event.yaml"), buf.Bytes(), 0o644)
}

func extractEventTypes(path string) ([]string, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, err
	}
	var out []string
	ast.Inspect(file, func(n ast.Node) bool {
		genDecl, ok := n.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			return true
		}
		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			// Typed as EventType, or untyped in an EventType iota/const block
			// where values are string literals assigned to EventType* names.
			for i, name := range valueSpec.Names {
				if !strings.HasPrefix(name.Name, "EventType") || name.Name == "EventType" {
					continue
				}
				if i >= len(valueSpec.Values) {
					continue
				}
				lit, ok := valueSpec.Values[i].(*ast.BasicLit)
				if !ok || lit.Kind != token.STRING {
					continue
				}
				out = append(out, strings.Trim(lit.Value, `"`))
			}
		}
		return true
	})
	if len(out) == 0 {
		return nil, fmt.Errorf("no EventType constants found in %s", path)
	}
	return out, nil
}

func eventTypeSlug(et string) string {
	return strings.ReplaceAll(et, ".", "-") + "-event"
}

func eventTypeTitle(et string) string {
	parts := strings.Split(et, ".")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		// Keep common acronyms uppercase when whole segment is short.
		switch p {
		case "api":
			b.WriteString("API")
		case "totp":
			b.WriteString("TOTP")
		default:
			runes := []rune(p)
			runes[0] = unicode.ToUpper(runes[0])
			for i := 1; i < len(runes); i++ {
				if runes[i-1] == '_' {
					runes[i] = unicode.ToUpper(runes[i])
				}
			}
			s := string(runes)
			s = strings.ReplaceAll(s, "_", "")
			b.WriteString(s)
		}
	}
	b.WriteString("Event")
	return b.String()
}
