// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/nextgen/internal/service (interfaces: Pool,Transactioner,Statementer)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination ./mocks/database.mock.go . Pool,Transactioner,Statementer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/zitadel/nextgen/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockPool is a mock of Pool interface.
type MockPool struct {
	ctrl     *gomock.Controller
	recorder *MockPoolMockRecorder
	isgomock struct{}
}

// MockPoolMockRecorder is the mock recorder for MockPool.
type MockPoolMockRecorder struct {
	mock *MockPool
}

// NewMockPool creates a new mock instance.
func NewMockPool(ctrl *gomock.Controller) *MockPool {
	mock := &MockPool{ctrl: ctrl}
	mock.recorder = &MockPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPool) EXPECT() *MockPoolMockRecorder {
	return m.recorder
}

// Statements mocks base method.
func (m *MockPool) Statements() service.AllStatements {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Statements")
	ret0, _ := ret[0].(service.AllStatements)
	return ret0
}

// Statements indicates an expected call of Statements.
func (mr *MockPoolMockRecorder) Statements() *MockPoolStatementsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statements", reflect.TypeOf((*MockPool)(nil).Statements))
	return &MockPoolStatementsCall{Call: call}
}

// MockPoolStatementsCall wrap *gomock.Call
type MockPoolStatementsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoolStatementsCall) Return(arg0 service.AllStatements) *MockPoolStatementsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPoolStatementsCall) Do(f func() service.AllStatements) *MockPoolStatementsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoolStatementsCall) DoAndReturn(f func() service.AllStatements) *MockPoolStatementsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Transaction mocks base method.
func (m *MockPool) Transaction(ctx context.Context, fn func(context.Context, service.Statementer[service.AllStatements]) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockPoolMockRecorder) Transaction(ctx, fn any) *MockPoolTransactionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockPool)(nil).Transaction), ctx, fn)
	return &MockPoolTransactionCall{Call: call}
}

// MockPoolTransactionCall wrap *gomock.Call
type MockPoolTransactionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPoolTransactionCall) Return(arg0 error) *MockPoolTransactionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPoolTransactionCall) Do(f func(context.Context, func(context.Context, service.Statementer[service.AllStatements]) error) error) *MockPoolTransactionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPoolTransactionCall) DoAndReturn(f func(context.Context, func(context.Context, service.Statementer[service.AllStatements]) error) error) *MockPoolTransactionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTransactioner is a mock of Transactioner interface.
type MockTransactioner[S any] struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionerMockRecorder[S]
	isgomock struct{}
}

// MockTransactionerMockRecorder is the mock recorder for MockTransactioner.
type MockTransactionerMockRecorder[S any] struct {
	mock *MockTransactioner[S]
}

// NewMockTransactioner creates a new mock instance.
func NewMockTransactioner[S any](ctrl *gomock.Controller) *MockTransactioner[S] {
	mock := &MockTransactioner[S]{ctrl: ctrl}
	mock.recorder = &MockTransactionerMockRecorder[S]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactioner[S]) EXPECT() *MockTransactionerMockRecorder[S] {
	return m.recorder
}

// Transaction mocks base method.
func (m *MockTransactioner[S]) Transaction(ctx context.Context, fn func(context.Context, service.Statementer[S]) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockTransactionerMockRecorder[S]) Transaction(ctx, fn any) *MockTransactionerTransactionCall[S] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockTransactioner[S])(nil).Transaction), ctx, fn)
	return &MockTransactionerTransactionCall[S]{Call: call}
}

// MockTransactionerTransactionCall wrap *gomock.Call
type MockTransactionerTransactionCall[S any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTransactionerTransactionCall[S]) Return(arg0 error) *MockTransactionerTransactionCall[S] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTransactionerTransactionCall[S]) Do(f func(context.Context, func(context.Context, service.Statementer[S]) error) error) *MockTransactionerTransactionCall[S] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTransactionerTransactionCall[S]) DoAndReturn(f func(context.Context, func(context.Context, service.Statementer[S]) error) error) *MockTransactionerTransactionCall[S] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockStatementer is a mock of Statementer interface.
type MockStatementer[S any] struct {
	ctrl     *gomock.Controller
	recorder *MockStatementerMockRecorder[S]
	isgomock struct{}
}

// MockStatementerMockRecorder is the mock recorder for MockStatementer.
type MockStatementerMockRecorder[S any] struct {
	mock *MockStatementer[S]
}

// NewMockStatementer creates a new mock instance.
func NewMockStatementer[S any](ctrl *gomock.Controller) *MockStatementer[S] {
	mock := &MockStatementer[S]{ctrl: ctrl}
	mock.recorder = &MockStatementerMockRecorder[S]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatementer[S]) EXPECT() *MockStatementerMockRecorder[S] {
	return m.recorder
}

// Statements mocks base method.
func (m *MockStatementer[S]) Statements() S {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Statements")
	ret0, _ := ret[0].(S)
	return ret0
}

// Statements indicates an expected call of Statements.
func (mr *MockStatementerMockRecorder[S]) Statements() *MockStatementerStatementsCall[S] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statements", reflect.TypeOf((*MockStatementer[S])(nil).Statements))
	return &MockStatementerStatementsCall[S]{Call: call}
}

// MockStatementerStatementsCall wrap *gomock.Call
type MockStatementerStatementsCall[S any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatementerStatementsCall[S]) Return(arg0 S) *MockStatementerStatementsCall[S] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatementerStatementsCall[S]) Do(f func() S) *MockStatementerStatementsCall[S] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatementerStatementsCall[S]) DoAndReturn(f func() S) *MockStatementerStatementsCall[S] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
