// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/nextgen/internal/service (interfaces: KeyService)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination ./mocks/keys.mock.go . KeyService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	crypto "github.com/zitadel/nextgen/internal/crypto"
	crypto0 "github.com/zitadel/nextgen/internal/domain/crypto"
	service "github.com/zitadel/nextgen/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockKeyService is a mock of KeyService interface.
type MockKeyService struct {
	ctrl     *gomock.Controller
	recorder *MockKeyServiceMockRecorder
	isgomock struct{}
}

// MockKeyServiceMockRecorder is the mock recorder for MockKeyService.
type MockKeyServiceMockRecorder struct {
	mock *MockKeyService
}

// NewMockKeyService creates a new mock instance.
func NewMockKeyService(ctrl *gomock.Controller) *MockKeyService {
	mock := &MockKeyService{ctrl: ctrl}
	mock.recorder = &MockKeyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyService) EXPECT() *MockKeyServiceMockRecorder {
	return m.recorder
}

// GetEncryptionKeyByID mocks base method.
func (m *MockKeyService) GetEncryptionKeyByID(ctx context.Context, input service.GetDEKByIDAndAlgorithmInput) (*crypto0.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncryptionKeyByID", ctx, input)
	ret0, _ := ret[0].(*crypto0.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncryptionKeyByID indicates an expected call of GetEncryptionKeyByID.
func (mr *MockKeyServiceMockRecorder) GetEncryptionKeyByID(ctx, input any) *MockKeyServiceGetEncryptionKeyByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncryptionKeyByID", reflect.TypeOf((*MockKeyService)(nil).GetEncryptionKeyByID), ctx, input)
	return &MockKeyServiceGetEncryptionKeyByIDCall{Call: call}
}

// MockKeyServiceGetEncryptionKeyByIDCall wrap *gomock.Call
type MockKeyServiceGetEncryptionKeyByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyServiceGetEncryptionKeyByIDCall) Return(arg0 *crypto0.EncryptionKey, arg1 error) *MockKeyServiceGetEncryptionKeyByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyServiceGetEncryptionKeyByIDCall) Do(f func(context.Context, service.GetDEKByIDAndAlgorithmInput) (*crypto0.EncryptionKey, error)) *MockKeyServiceGetEncryptionKeyByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyServiceGetEncryptionKeyByIDCall) DoAndReturn(f func(context.Context, service.GetDEKByIDAndAlgorithmInput) (*crypto0.EncryptionKey, error)) *MockKeyServiceGetEncryptionKeyByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProjectDEK mocks base method.
func (m *MockKeyService) GetProjectDEK(ctx context.Context, input service.GetProjectDEKInput) (*crypto0.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectDEK", ctx, input)
	ret0, _ := ret[0].(*crypto0.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectDEK indicates an expected call of GetProjectDEK.
func (mr *MockKeyServiceMockRecorder) GetProjectDEK(ctx, input any) *MockKeyServiceGetProjectDEKCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectDEK", reflect.TypeOf((*MockKeyService)(nil).GetProjectDEK), ctx, input)
	return &MockKeyServiceGetProjectDEKCall{Call: call}
}

// MockKeyServiceGetProjectDEKCall wrap *gomock.Call
type MockKeyServiceGetProjectDEKCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyServiceGetProjectDEKCall) Return(arg0 *crypto0.EncryptionKey, arg1 error) *MockKeyServiceGetProjectDEKCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyServiceGetProjectDEKCall) Do(f func(context.Context, service.GetProjectDEKInput) (*crypto0.EncryptionKey, error)) *MockKeyServiceGetProjectDEKCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyServiceGetProjectDEKCall) DoAndReturn(f func(context.Context, service.GetProjectDEKInput) (*crypto0.EncryptionKey, error)) *MockKeyServiceGetProjectDEKCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProjectDEKCrypter mocks base method.
func (m *MockKeyService) GetProjectDEKCrypter(ctx context.Context, input service.GetProjectDEKInput) (crypto.Crypter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectDEKCrypter", ctx, input)
	ret0, _ := ret[0].(crypto.Crypter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectDEKCrypter indicates an expected call of GetProjectDEKCrypter.
func (mr *MockKeyServiceMockRecorder) GetProjectDEKCrypter(ctx, input any) *MockKeyServiceGetProjectDEKCrypterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectDEKCrypter", reflect.TypeOf((*MockKeyService)(nil).GetProjectDEKCrypter), ctx, input)
	return &MockKeyServiceGetProjectDEKCrypterCall{Call: call}
}

// MockKeyServiceGetProjectDEKCrypterCall wrap *gomock.Call
type MockKeyServiceGetProjectDEKCrypterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyServiceGetProjectDEKCrypterCall) Return(arg0 crypto.Crypter, arg1 error) *MockKeyServiceGetProjectDEKCrypterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyServiceGetProjectDEKCrypterCall) Do(f func(context.Context, service.GetProjectDEKInput) (crypto.Crypter, error)) *MockKeyServiceGetProjectDEKCrypterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyServiceGetProjectDEKCrypterCall) DoAndReturn(f func(context.Context, service.GetProjectDEKInput) (crypto.Crypter, error)) *MockKeyServiceGetProjectDEKCrypterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RotateDEK mocks base method.
func (m *MockKeyService) RotateDEK(ctx context.Context, input service.RotateDEKInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateDEK", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateDEK indicates an expected call of RotateDEK.
func (mr *MockKeyServiceMockRecorder) RotateDEK(ctx, input any) *MockKeyServiceRotateDEKCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateDEK", reflect.TypeOf((*MockKeyService)(nil).RotateDEK), ctx, input)
	return &MockKeyServiceRotateDEKCall{Call: call}
}

// MockKeyServiceRotateDEKCall wrap *gomock.Call
type MockKeyServiceRotateDEKCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyServiceRotateDEKCall) Return(arg0 error) *MockKeyServiceRotateDEKCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyServiceRotateDEKCall) Do(f func(context.Context, service.RotateDEKInput) error) *MockKeyServiceRotateDEKCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyServiceRotateDEKCall) DoAndReturn(f func(context.Context, service.RotateDEKInput) error) *MockKeyServiceRotateDEKCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
