// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/nextgen/internal/service (interfaces: KeyService)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination ./mocks/keys.mock.go . KeyService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	jose "github.com/go-jose/go-jose/v4"
	domain "github.com/zitadel/nextgen/internal/domain"
	op "github.com/zitadel/oidc/v3/pkg/op"
	gomock "go.uber.org/mock/gomock"
)

// MockKeyService is a mock of KeyService interface.
type MockKeyService struct {
	ctrl     *gomock.Controller
	recorder *MockKeyServiceMockRecorder
	isgomock struct{}
}

// MockKeyServiceMockRecorder is the mock recorder for MockKeyService.
type MockKeyServiceMockRecorder struct {
	mock *MockKeyService
}

// NewMockKeyService creates a new mock instance.
func NewMockKeyService(ctrl *gomock.Controller) *MockKeyService {
	mock := &MockKeyService{ctrl: ctrl}
	mock.recorder = &MockKeyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyService) EXPECT() *MockKeyServiceMockRecorder {
	return m.recorder
}

// GetCrypter mocks base method.
func (m *MockKeyService) GetCrypter(ctx context.Context, keyID string, algorithm jose.ContentEncryption) (op.Crypto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCrypter", ctx, keyID, algorithm)
	ret0, _ := ret[0].(op.Crypto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCrypter indicates an expected call of GetCrypter.
func (mr *MockKeyServiceMockRecorder) GetCrypter(ctx, keyID, algorithm any) *MockKeyServiceGetCrypterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCrypter", reflect.TypeOf((*MockKeyService)(nil).GetCrypter), ctx, keyID, algorithm)
	return &MockKeyServiceGetCrypterCall{Call: call}
}

// MockKeyServiceGetCrypterCall wrap *gomock.Call
type MockKeyServiceGetCrypterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyServiceGetCrypterCall) Return(arg0 op.Crypto, arg1 error) *MockKeyServiceGetCrypterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyServiceGetCrypterCall) Do(f func(context.Context, string, jose.ContentEncryption) (op.Crypto, error)) *MockKeyServiceGetCrypterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyServiceGetCrypterCall) DoAndReturn(f func(context.Context, string, jose.ContentEncryption) (op.Crypto, error)) *MockKeyServiceGetCrypterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetEncryptionKey mocks base method.
func (m *MockKeyService) GetEncryptionKey(ctx context.Context, keyID string, algorithm jose.ContentEncryption) (*domain.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncryptionKey", ctx, keyID, algorithm)
	ret0, _ := ret[0].(*domain.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncryptionKey indicates an expected call of GetEncryptionKey.
func (mr *MockKeyServiceMockRecorder) GetEncryptionKey(ctx, keyID, algorithm any) *MockKeyServiceGetEncryptionKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncryptionKey", reflect.TypeOf((*MockKeyService)(nil).GetEncryptionKey), ctx, keyID, algorithm)
	return &MockKeyServiceGetEncryptionKeyCall{Call: call}
}

// MockKeyServiceGetEncryptionKeyCall wrap *gomock.Call
type MockKeyServiceGetEncryptionKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyServiceGetEncryptionKeyCall) Return(arg0 *domain.EncryptionKey, arg1 error) *MockKeyServiceGetEncryptionKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyServiceGetEncryptionKeyCall) Do(f func(context.Context, string, jose.ContentEncryption) (*domain.EncryptionKey, error)) *MockKeyServiceGetEncryptionKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyServiceGetEncryptionKeyCall) DoAndReturn(f func(context.Context, string, jose.ContentEncryption) (*domain.EncryptionKey, error)) *MockKeyServiceGetEncryptionKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetKekCrypter mocks base method.
func (m *MockKeyService) GetKekCrypter(ctx context.Context) (op.Crypto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKekCrypter", ctx)
	ret0, _ := ret[0].(op.Crypto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKekCrypter indicates an expected call of GetKekCrypter.
func (mr *MockKeyServiceMockRecorder) GetKekCrypter(ctx any) *MockKeyServiceGetKekCrypterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKekCrypter", reflect.TypeOf((*MockKeyService)(nil).GetKekCrypter), ctx)
	return &MockKeyServiceGetKekCrypterCall{Call: call}
}

// MockKeyServiceGetKekCrypterCall wrap *gomock.Call
type MockKeyServiceGetKekCrypterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyServiceGetKekCrypterCall) Return(arg0 op.Crypto, arg1 error) *MockKeyServiceGetKekCrypterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyServiceGetKekCrypterCall) Do(f func(context.Context) (op.Crypto, error)) *MockKeyServiceGetKekCrypterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyServiceGetKekCrypterCall) DoAndReturn(f func(context.Context) (op.Crypto, error)) *MockKeyServiceGetKekCrypterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProjectCrypter mocks base method.
func (m *MockKeyService) GetProjectCrypter(ctx context.Context, projectID string, purpose domain.EncryptionKeyPurpose) (op.Crypto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectCrypter", ctx, projectID, purpose)
	ret0, _ := ret[0].(op.Crypto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectCrypter indicates an expected call of GetProjectCrypter.
func (mr *MockKeyServiceMockRecorder) GetProjectCrypter(ctx, projectID, purpose any) *MockKeyServiceGetProjectCrypterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectCrypter", reflect.TypeOf((*MockKeyService)(nil).GetProjectCrypter), ctx, projectID, purpose)
	return &MockKeyServiceGetProjectCrypterCall{Call: call}
}

// MockKeyServiceGetProjectCrypterCall wrap *gomock.Call
type MockKeyServiceGetProjectCrypterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyServiceGetProjectCrypterCall) Return(arg0 op.Crypto, arg1 error) *MockKeyServiceGetProjectCrypterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyServiceGetProjectCrypterCall) Do(f func(context.Context, string, domain.EncryptionKeyPurpose) (op.Crypto, error)) *MockKeyServiceGetProjectCrypterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyServiceGetProjectCrypterCall) DoAndReturn(f func(context.Context, string, domain.EncryptionKeyPurpose) (op.Crypto, error)) *MockKeyServiceGetProjectCrypterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProjectEncryptionKey mocks base method.
func (m *MockKeyService) GetProjectEncryptionKey(ctx context.Context, projectID string, purpose domain.EncryptionKeyPurpose) (*domain.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectEncryptionKey", ctx, projectID, purpose)
	ret0, _ := ret[0].(*domain.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectEncryptionKey indicates an expected call of GetProjectEncryptionKey.
func (mr *MockKeyServiceMockRecorder) GetProjectEncryptionKey(ctx, projectID, purpose any) *MockKeyServiceGetProjectEncryptionKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectEncryptionKey", reflect.TypeOf((*MockKeyService)(nil).GetProjectEncryptionKey), ctx, projectID, purpose)
	return &MockKeyServiceGetProjectEncryptionKeyCall{Call: call}
}

// MockKeyServiceGetProjectEncryptionKeyCall wrap *gomock.Call
type MockKeyServiceGetProjectEncryptionKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyServiceGetProjectEncryptionKeyCall) Return(arg0 *domain.EncryptionKey, arg1 error) *MockKeyServiceGetProjectEncryptionKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyServiceGetProjectEncryptionKeyCall) Do(f func(context.Context, string, domain.EncryptionKeyPurpose) (*domain.EncryptionKey, error)) *MockKeyServiceGetProjectEncryptionKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyServiceGetProjectEncryptionKeyCall) DoAndReturn(f func(context.Context, string, domain.EncryptionKeyPurpose) (*domain.EncryptionKey, error)) *MockKeyServiceGetProjectEncryptionKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProjectSigner mocks base method.
func (m *MockKeyService) GetProjectSigner(ctx context.Context, projectID string, purpose domain.SigningKeyPurpose) (jose.Signer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectSigner", ctx, projectID, purpose)
	ret0, _ := ret[0].(jose.Signer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectSigner indicates an expected call of GetProjectSigner.
func (mr *MockKeyServiceMockRecorder) GetProjectSigner(ctx, projectID, purpose any) *MockKeyServiceGetProjectSignerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectSigner", reflect.TypeOf((*MockKeyService)(nil).GetProjectSigner), ctx, projectID, purpose)
	return &MockKeyServiceGetProjectSignerCall{Call: call}
}

// MockKeyServiceGetProjectSignerCall wrap *gomock.Call
type MockKeyServiceGetProjectSignerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyServiceGetProjectSignerCall) Return(arg0 jose.Signer, arg1 error) *MockKeyServiceGetProjectSignerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyServiceGetProjectSignerCall) Do(f func(context.Context, string, domain.SigningKeyPurpose) (jose.Signer, error)) *MockKeyServiceGetProjectSignerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyServiceGetProjectSignerCall) DoAndReturn(f func(context.Context, string, domain.SigningKeyPurpose) (jose.Signer, error)) *MockKeyServiceGetProjectSignerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProjectSigningKey mocks base method.
func (m *MockKeyService) GetProjectSigningKey(ctx context.Context, projectID string, purpose domain.SigningKeyPurpose) (*domain.SigningKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectSigningKey", ctx, projectID, purpose)
	ret0, _ := ret[0].(*domain.SigningKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectSigningKey indicates an expected call of GetProjectSigningKey.
func (mr *MockKeyServiceMockRecorder) GetProjectSigningKey(ctx, projectID, purpose any) *MockKeyServiceGetProjectSigningKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectSigningKey", reflect.TypeOf((*MockKeyService)(nil).GetProjectSigningKey), ctx, projectID, purpose)
	return &MockKeyServiceGetProjectSigningKeyCall{Call: call}
}

// MockKeyServiceGetProjectSigningKeyCall wrap *gomock.Call
type MockKeyServiceGetProjectSigningKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyServiceGetProjectSigningKeyCall) Return(arg0 *domain.SigningKey, arg1 error) *MockKeyServiceGetProjectSigningKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyServiceGetProjectSigningKeyCall) Do(f func(context.Context, string, domain.SigningKeyPurpose) (*domain.SigningKey, error)) *MockKeyServiceGetProjectSigningKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyServiceGetProjectSigningKeyCall) DoAndReturn(f func(context.Context, string, domain.SigningKeyPurpose) (*domain.SigningKey, error)) *MockKeyServiceGetProjectSigningKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
