// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/nextgen/internal/service (interfaces: StatementPool,Statements,AllStatements,ProjectStatements,FlowDefinitionStatements,CryptoKeyStatements,JSONSchemaStatements)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination ./mocks/statement.mock.go . StatementPool,Statements,AllStatements,ProjectStatements,FlowDefinitionStatements,CryptoKeyStatements,JSONSchemaStatements
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/zitadel/nextgen/internal/domain"
	service "github.com/zitadel/nextgen/internal/service"
	database "github.com/zitadel/nextgen/internal/storage/v2/database"
	gomock "go.uber.org/mock/gomock"
)

// MockStatementPool is a mock of StatementPool interface.
type MockStatementPool struct {
	ctrl     *gomock.Controller
	recorder *MockStatementPoolMockRecorder
	isgomock struct{}
}

// MockStatementPoolMockRecorder is the mock recorder for MockStatementPool.
type MockStatementPoolMockRecorder struct {
	mock *MockStatementPool
}

// NewMockStatementPool creates a new mock instance.
func NewMockStatementPool(ctrl *gomock.Controller) *MockStatementPool {
	mock := &MockStatementPool{ctrl: ctrl}
	mock.recorder = &MockStatementPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatementPool) EXPECT() *MockStatementPoolMockRecorder {
	return m.recorder
}

// Statements mocks base method.
func (m *MockStatementPool) Statements() service.AllStatements {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Statements")
	ret0, _ := ret[0].(service.AllStatements)
	return ret0
}

// Statements indicates an expected call of Statements.
func (mr *MockStatementPoolMockRecorder) Statements() *MockStatementPoolStatementsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statements", reflect.TypeOf((*MockStatementPool)(nil).Statements))
	return &MockStatementPoolStatementsCall{Call: call}
}

// MockStatementPoolStatementsCall wrap *gomock.Call
type MockStatementPoolStatementsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatementPoolStatementsCall) Return(arg0 service.AllStatements) *MockStatementPoolStatementsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatementPoolStatementsCall) Do(f func() service.AllStatements) *MockStatementPoolStatementsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatementPoolStatementsCall) DoAndReturn(f func() service.AllStatements) *MockStatementPoolStatementsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Transaction mocks base method.
func (m *MockStatementPool) Transaction(ctx context.Context, fn func(context.Context, service.Statementer[service.AllStatements]) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockStatementPoolMockRecorder) Transaction(ctx, fn any) *MockStatementPoolTransactionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockStatementPool)(nil).Transaction), ctx, fn)
	return &MockStatementPoolTransactionCall{Call: call}
}

// MockStatementPoolTransactionCall wrap *gomock.Call
type MockStatementPoolTransactionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatementPoolTransactionCall) Return(arg0 error) *MockStatementPoolTransactionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatementPoolTransactionCall) Do(f func(context.Context, func(context.Context, service.Statementer[service.AllStatements]) error) error) *MockStatementPoolTransactionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatementPoolTransactionCall) DoAndReturn(f func(context.Context, func(context.Context, service.Statementer[service.AllStatements]) error) error) *MockStatementPoolTransactionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockStatements is a mock of Statements interface.
type MockStatements struct {
	ctrl     *gomock.Controller
	recorder *MockStatementsMockRecorder
	isgomock struct{}
}

// MockStatementsMockRecorder is the mock recorder for MockStatements.
type MockStatementsMockRecorder struct {
	mock *MockStatements
}

// NewMockStatements creates a new mock instance.
func NewMockStatements(ctrl *gomock.Controller) *MockStatements {
	mock := &MockStatements{ctrl: ctrl}
	mock.recorder = &MockStatementsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatements) EXPECT() *MockStatementsMockRecorder {
	return m.recorder
}

// IsStatements mocks base method.
func (m *MockStatements) IsStatements() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IsStatements")
}

// IsStatements indicates an expected call of IsStatements.
func (mr *MockStatementsMockRecorder) IsStatements() *MockStatementsIsStatementsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStatements", reflect.TypeOf((*MockStatements)(nil).IsStatements))
	return &MockStatementsIsStatementsCall{Call: call}
}

// MockStatementsIsStatementsCall wrap *gomock.Call
type MockStatementsIsStatementsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStatementsIsStatementsCall) Return() *MockStatementsIsStatementsCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStatementsIsStatementsCall) Do(f func()) *MockStatementsIsStatementsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStatementsIsStatementsCall) DoAndReturn(f func()) *MockStatementsIsStatementsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockAllStatements is a mock of AllStatements interface.
type MockAllStatements struct {
	ctrl     *gomock.Controller
	recorder *MockAllStatementsMockRecorder
	isgomock struct{}
}

// MockAllStatementsMockRecorder is the mock recorder for MockAllStatements.
type MockAllStatementsMockRecorder struct {
	mock *MockAllStatements
}

// NewMockAllStatements creates a new mock instance.
func NewMockAllStatements(ctrl *gomock.Controller) *MockAllStatements {
	mock := &MockAllStatements{ctrl: ctrl}
	mock.recorder = &MockAllStatementsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllStatements) EXPECT() *MockAllStatementsMockRecorder {
	return m.recorder
}

// CreateEncryptionKey mocks base method.
func (m *MockAllStatements) CreateEncryptionKey(ctx context.Context, dek *domain.EncryptionKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEncryptionKey", ctx, dek)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEncryptionKey indicates an expected call of CreateEncryptionKey.
func (mr *MockAllStatementsMockRecorder) CreateEncryptionKey(ctx, dek any) *MockAllStatementsCreateEncryptionKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEncryptionKey", reflect.TypeOf((*MockAllStatements)(nil).CreateEncryptionKey), ctx, dek)
	return &MockAllStatementsCreateEncryptionKeyCall{Call: call}
}

// MockAllStatementsCreateEncryptionKeyCall wrap *gomock.Call
type MockAllStatementsCreateEncryptionKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsCreateEncryptionKeyCall) Return(arg0 error) *MockAllStatementsCreateEncryptionKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsCreateEncryptionKeyCall) Do(f func(context.Context, *domain.EncryptionKey) error) *MockAllStatementsCreateEncryptionKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsCreateEncryptionKeyCall) DoAndReturn(f func(context.Context, *domain.EncryptionKey) error) *MockAllStatementsCreateEncryptionKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateFlowDefinition mocks base method.
func (m *MockAllStatements) CreateFlowDefinition(ctx context.Context, entity *domain.FlowDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFlowDefinition", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFlowDefinition indicates an expected call of CreateFlowDefinition.
func (mr *MockAllStatementsMockRecorder) CreateFlowDefinition(ctx, entity any) *MockAllStatementsCreateFlowDefinitionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFlowDefinition", reflect.TypeOf((*MockAllStatements)(nil).CreateFlowDefinition), ctx, entity)
	return &MockAllStatementsCreateFlowDefinitionCall{Call: call}
}

// MockAllStatementsCreateFlowDefinitionCall wrap *gomock.Call
type MockAllStatementsCreateFlowDefinitionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsCreateFlowDefinitionCall) Return(arg0 error) *MockAllStatementsCreateFlowDefinitionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsCreateFlowDefinitionCall) Do(f func(context.Context, *domain.FlowDefinition) error) *MockAllStatementsCreateFlowDefinitionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsCreateFlowDefinitionCall) DoAndReturn(f func(context.Context, *domain.FlowDefinition) error) *MockAllStatementsCreateFlowDefinitionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateJSONSchema mocks base method.
func (m *MockAllStatements) CreateJSONSchema(ctx context.Context, entity *domain.JSONSchema) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJSONSchema", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateJSONSchema indicates an expected call of CreateJSONSchema.
func (mr *MockAllStatementsMockRecorder) CreateJSONSchema(ctx, entity any) *MockAllStatementsCreateJSONSchemaCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJSONSchema", reflect.TypeOf((*MockAllStatements)(nil).CreateJSONSchema), ctx, entity)
	return &MockAllStatementsCreateJSONSchemaCall{Call: call}
}

// MockAllStatementsCreateJSONSchemaCall wrap *gomock.Call
type MockAllStatementsCreateJSONSchemaCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsCreateJSONSchemaCall) Return(arg0 error) *MockAllStatementsCreateJSONSchemaCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsCreateJSONSchemaCall) Do(f func(context.Context, *domain.JSONSchema) error) *MockAllStatementsCreateJSONSchemaCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsCreateJSONSchemaCall) DoAndReturn(f func(context.Context, *domain.JSONSchema) error) *MockAllStatementsCreateJSONSchemaCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateProject mocks base method.
func (m *MockAllStatements) CreateProject(ctx context.Context, entity *domain.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockAllStatementsMockRecorder) CreateProject(ctx, entity any) *MockAllStatementsCreateProjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockAllStatements)(nil).CreateProject), ctx, entity)
	return &MockAllStatementsCreateProjectCall{Call: call}
}

// MockAllStatementsCreateProjectCall wrap *gomock.Call
type MockAllStatementsCreateProjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsCreateProjectCall) Return(arg0 error) *MockAllStatementsCreateProjectCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsCreateProjectCall) Do(f func(context.Context, *domain.Project) error) *MockAllStatementsCreateProjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsCreateProjectCall) DoAndReturn(f func(context.Context, *domain.Project) error) *MockAllStatementsCreateProjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteFlowDefinitionByID mocks base method.
func (m *MockAllStatements) DeleteFlowDefinitionByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFlowDefinitionByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFlowDefinitionByID indicates an expected call of DeleteFlowDefinitionByID.
func (mr *MockAllStatementsMockRecorder) DeleteFlowDefinitionByID(ctx, id any) *MockAllStatementsDeleteFlowDefinitionByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFlowDefinitionByID", reflect.TypeOf((*MockAllStatements)(nil).DeleteFlowDefinitionByID), ctx, id)
	return &MockAllStatementsDeleteFlowDefinitionByIDCall{Call: call}
}

// MockAllStatementsDeleteFlowDefinitionByIDCall wrap *gomock.Call
type MockAllStatementsDeleteFlowDefinitionByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsDeleteFlowDefinitionByIDCall) Return(arg0 error) *MockAllStatementsDeleteFlowDefinitionByIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsDeleteFlowDefinitionByIDCall) Do(f func(context.Context, string) error) *MockAllStatementsDeleteFlowDefinitionByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsDeleteFlowDefinitionByIDCall) DoAndReturn(f func(context.Context, string) error) *MockAllStatementsDeleteFlowDefinitionByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteJSONSchemaByID mocks base method.
func (m *MockAllStatements) DeleteJSONSchemaByID(ctx context.Context, projectID, schemaID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJSONSchemaByID", ctx, projectID, schemaID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJSONSchemaByID indicates an expected call of DeleteJSONSchemaByID.
func (mr *MockAllStatementsMockRecorder) DeleteJSONSchemaByID(ctx, projectID, schemaID any) *MockAllStatementsDeleteJSONSchemaByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJSONSchemaByID", reflect.TypeOf((*MockAllStatements)(nil).DeleteJSONSchemaByID), ctx, projectID, schemaID)
	return &MockAllStatementsDeleteJSONSchemaByIDCall{Call: call}
}

// MockAllStatementsDeleteJSONSchemaByIDCall wrap *gomock.Call
type MockAllStatementsDeleteJSONSchemaByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsDeleteJSONSchemaByIDCall) Return(arg0 error) *MockAllStatementsDeleteJSONSchemaByIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsDeleteJSONSchemaByIDCall) Do(f func(context.Context, string, string) error) *MockAllStatementsDeleteJSONSchemaByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsDeleteJSONSchemaByIDCall) DoAndReturn(f func(context.Context, string, string) error) *MockAllStatementsDeleteJSONSchemaByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteProjectByID mocks base method.
func (m *MockAllStatements) DeleteProjectByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectByID indicates an expected call of DeleteProjectByID.
func (mr *MockAllStatementsMockRecorder) DeleteProjectByID(ctx, id any) *MockAllStatementsDeleteProjectByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectByID", reflect.TypeOf((*MockAllStatements)(nil).DeleteProjectByID), ctx, id)
	return &MockAllStatementsDeleteProjectByIDCall{Call: call}
}

// MockAllStatementsDeleteProjectByIDCall wrap *gomock.Call
type MockAllStatementsDeleteProjectByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsDeleteProjectByIDCall) Return(arg0 error) *MockAllStatementsDeleteProjectByIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsDeleteProjectByIDCall) Do(f func(context.Context, string) error) *MockAllStatementsDeleteProjectByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsDeleteProjectByIDCall) DoAndReturn(f func(context.Context, string) error) *MockAllStatementsDeleteProjectByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetEncryptionKey mocks base method.
func (m *MockAllStatements) GetEncryptionKey(ctx context.Context, filter database.Filter[domain.EncryptionKeyField]) (*domain.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncryptionKey", ctx, filter)
	ret0, _ := ret[0].(*domain.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncryptionKey indicates an expected call of GetEncryptionKey.
func (mr *MockAllStatementsMockRecorder) GetEncryptionKey(ctx, filter any) *MockAllStatementsGetEncryptionKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncryptionKey", reflect.TypeOf((*MockAllStatements)(nil).GetEncryptionKey), ctx, filter)
	return &MockAllStatementsGetEncryptionKeyCall{Call: call}
}

// MockAllStatementsGetEncryptionKeyCall wrap *gomock.Call
type MockAllStatementsGetEncryptionKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsGetEncryptionKeyCall) Return(arg0 *domain.EncryptionKey, arg1 error) *MockAllStatementsGetEncryptionKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsGetEncryptionKeyCall) Do(f func(context.Context, database.Filter[domain.EncryptionKeyField]) (*domain.EncryptionKey, error)) *MockAllStatementsGetEncryptionKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsGetEncryptionKeyCall) DoAndReturn(f func(context.Context, database.Filter[domain.EncryptionKeyField]) (*domain.EncryptionKey, error)) *MockAllStatementsGetEncryptionKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetFlowDefinitionByID mocks base method.
func (m *MockAllStatements) GetFlowDefinitionByID(ctx context.Context, id string) (*domain.FlowDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlowDefinitionByID", ctx, id)
	ret0, _ := ret[0].(*domain.FlowDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlowDefinitionByID indicates an expected call of GetFlowDefinitionByID.
func (mr *MockAllStatementsMockRecorder) GetFlowDefinitionByID(ctx, id any) *MockAllStatementsGetFlowDefinitionByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlowDefinitionByID", reflect.TypeOf((*MockAllStatements)(nil).GetFlowDefinitionByID), ctx, id)
	return &MockAllStatementsGetFlowDefinitionByIDCall{Call: call}
}

// MockAllStatementsGetFlowDefinitionByIDCall wrap *gomock.Call
type MockAllStatementsGetFlowDefinitionByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsGetFlowDefinitionByIDCall) Return(arg0 *domain.FlowDefinition, arg1 error) *MockAllStatementsGetFlowDefinitionByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsGetFlowDefinitionByIDCall) Do(f func(context.Context, string) (*domain.FlowDefinition, error)) *MockAllStatementsGetFlowDefinitionByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsGetFlowDefinitionByIDCall) DoAndReturn(f func(context.Context, string) (*domain.FlowDefinition, error)) *MockAllStatementsGetFlowDefinitionByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetJSONSchemaByID mocks base method.
func (m *MockAllStatements) GetJSONSchemaByID(ctx context.Context, projectID, schemaID string) (*domain.JSONSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSONSchemaByID", ctx, projectID, schemaID)
	ret0, _ := ret[0].(*domain.JSONSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJSONSchemaByID indicates an expected call of GetJSONSchemaByID.
func (mr *MockAllStatementsMockRecorder) GetJSONSchemaByID(ctx, projectID, schemaID any) *MockAllStatementsGetJSONSchemaByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSONSchemaByID", reflect.TypeOf((*MockAllStatements)(nil).GetJSONSchemaByID), ctx, projectID, schemaID)
	return &MockAllStatementsGetJSONSchemaByIDCall{Call: call}
}

// MockAllStatementsGetJSONSchemaByIDCall wrap *gomock.Call
type MockAllStatementsGetJSONSchemaByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsGetJSONSchemaByIDCall) Return(arg0 *domain.JSONSchema, arg1 error) *MockAllStatementsGetJSONSchemaByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsGetJSONSchemaByIDCall) Do(f func(context.Context, string, string) (*domain.JSONSchema, error)) *MockAllStatementsGetJSONSchemaByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsGetJSONSchemaByIDCall) DoAndReturn(f func(context.Context, string, string) (*domain.JSONSchema, error)) *MockAllStatementsGetJSONSchemaByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProjectByID mocks base method.
func (m *MockAllStatements) GetProjectByID(ctx context.Context, id string) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByID", ctx, id)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByID indicates an expected call of GetProjectByID.
func (mr *MockAllStatementsMockRecorder) GetProjectByID(ctx, id any) *MockAllStatementsGetProjectByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByID", reflect.TypeOf((*MockAllStatements)(nil).GetProjectByID), ctx, id)
	return &MockAllStatementsGetProjectByIDCall{Call: call}
}

// MockAllStatementsGetProjectByIDCall wrap *gomock.Call
type MockAllStatementsGetProjectByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsGetProjectByIDCall) Return(arg0 *domain.Project, arg1 error) *MockAllStatementsGetProjectByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsGetProjectByIDCall) Do(f func(context.Context, string) (*domain.Project, error)) *MockAllStatementsGetProjectByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsGetProjectByIDCall) DoAndReturn(f func(context.Context, string) (*domain.Project, error)) *MockAllStatementsGetProjectByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsStatements mocks base method.
func (m *MockAllStatements) IsStatements() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IsStatements")
}

// IsStatements indicates an expected call of IsStatements.
func (mr *MockAllStatementsMockRecorder) IsStatements() *MockAllStatementsIsStatementsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStatements", reflect.TypeOf((*MockAllStatements)(nil).IsStatements))
	return &MockAllStatementsIsStatementsCall{Call: call}
}

// MockAllStatementsIsStatementsCall wrap *gomock.Call
type MockAllStatementsIsStatementsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsIsStatementsCall) Return() *MockAllStatementsIsStatementsCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsIsStatementsCall) Do(f func()) *MockAllStatementsIsStatementsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsIsStatementsCall) DoAndReturn(f func()) *MockAllStatementsIsStatementsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListFlowDefinitions mocks base method.
func (m *MockAllStatements) ListFlowDefinitions(ctx context.Context, filter *database.ListOptions[domain.FlowDefinitionField]) (*database.ListResult[*domain.FlowDefinition], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFlowDefinitions", ctx, filter)
	ret0, _ := ret[0].(*database.ListResult[*domain.FlowDefinition])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFlowDefinitions indicates an expected call of ListFlowDefinitions.
func (mr *MockAllStatementsMockRecorder) ListFlowDefinitions(ctx, filter any) *MockAllStatementsListFlowDefinitionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFlowDefinitions", reflect.TypeOf((*MockAllStatements)(nil).ListFlowDefinitions), ctx, filter)
	return &MockAllStatementsListFlowDefinitionsCall{Call: call}
}

// MockAllStatementsListFlowDefinitionsCall wrap *gomock.Call
type MockAllStatementsListFlowDefinitionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsListFlowDefinitionsCall) Return(arg0 *database.ListResult[*domain.FlowDefinition], arg1 error) *MockAllStatementsListFlowDefinitionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsListFlowDefinitionsCall) Do(f func(context.Context, *database.ListOptions[domain.FlowDefinitionField]) (*database.ListResult[*domain.FlowDefinition], error)) *MockAllStatementsListFlowDefinitionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsListFlowDefinitionsCall) DoAndReturn(f func(context.Context, *database.ListOptions[domain.FlowDefinitionField]) (*database.ListResult[*domain.FlowDefinition], error)) *MockAllStatementsListFlowDefinitionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListJSONSchemas mocks base method.
func (m *MockAllStatements) ListJSONSchemas(ctx context.Context, filter *database.ListOptions[domain.JSONSchemaField]) (*database.ListResult[*domain.JSONSchema], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJSONSchemas", ctx, filter)
	ret0, _ := ret[0].(*database.ListResult[*domain.JSONSchema])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJSONSchemas indicates an expected call of ListJSONSchemas.
func (mr *MockAllStatementsMockRecorder) ListJSONSchemas(ctx, filter any) *MockAllStatementsListJSONSchemasCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJSONSchemas", reflect.TypeOf((*MockAllStatements)(nil).ListJSONSchemas), ctx, filter)
	return &MockAllStatementsListJSONSchemasCall{Call: call}
}

// MockAllStatementsListJSONSchemasCall wrap *gomock.Call
type MockAllStatementsListJSONSchemasCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsListJSONSchemasCall) Return(arg0 *database.ListResult[*domain.JSONSchema], arg1 error) *MockAllStatementsListJSONSchemasCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsListJSONSchemasCall) Do(f func(context.Context, *database.ListOptions[domain.JSONSchemaField]) (*database.ListResult[*domain.JSONSchema], error)) *MockAllStatementsListJSONSchemasCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsListJSONSchemasCall) DoAndReturn(f func(context.Context, *database.ListOptions[domain.JSONSchemaField]) (*database.ListResult[*domain.JSONSchema], error)) *MockAllStatementsListJSONSchemasCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListProjects mocks base method.
func (m *MockAllStatements) ListProjects(ctx context.Context, filter *database.ListOptions[domain.ProjectField]) (*database.ListResult[*domain.Project], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx, filter)
	ret0, _ := ret[0].(*database.ListResult[*domain.Project])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockAllStatementsMockRecorder) ListProjects(ctx, filter any) *MockAllStatementsListProjectsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockAllStatements)(nil).ListProjects), ctx, filter)
	return &MockAllStatementsListProjectsCall{Call: call}
}

// MockAllStatementsListProjectsCall wrap *gomock.Call
type MockAllStatementsListProjectsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsListProjectsCall) Return(arg0 *database.ListResult[*domain.Project], arg1 error) *MockAllStatementsListProjectsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsListProjectsCall) Do(f func(context.Context, *database.ListOptions[domain.ProjectField]) (*database.ListResult[*domain.Project], error)) *MockAllStatementsListProjectsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsListProjectsCall) DoAndReturn(f func(context.Context, *database.ListOptions[domain.ProjectField]) (*database.ListResult[*domain.Project], error)) *MockAllStatementsListProjectsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProject mocks base method.
func (m *MockAllStatements) UpdateProject(ctx context.Context, entity *domain.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProject", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockAllStatementsMockRecorder) UpdateProject(ctx, entity any) *MockAllStatementsUpdateProjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockAllStatements)(nil).UpdateProject), ctx, entity)
	return &MockAllStatementsUpdateProjectCall{Call: call}
}

// MockAllStatementsUpdateProjectCall wrap *gomock.Call
type MockAllStatementsUpdateProjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAllStatementsUpdateProjectCall) Return(arg0 error) *MockAllStatementsUpdateProjectCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAllStatementsUpdateProjectCall) Do(f func(context.Context, *domain.Project) error) *MockAllStatementsUpdateProjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAllStatementsUpdateProjectCall) DoAndReturn(f func(context.Context, *domain.Project) error) *MockAllStatementsUpdateProjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockProjectStatements is a mock of ProjectStatements interface.
type MockProjectStatements struct {
	ctrl     *gomock.Controller
	recorder *MockProjectStatementsMockRecorder
	isgomock struct{}
}

// MockProjectStatementsMockRecorder is the mock recorder for MockProjectStatements.
type MockProjectStatementsMockRecorder struct {
	mock *MockProjectStatements
}

// NewMockProjectStatements creates a new mock instance.
func NewMockProjectStatements(ctrl *gomock.Controller) *MockProjectStatements {
	mock := &MockProjectStatements{ctrl: ctrl}
	mock.recorder = &MockProjectStatementsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectStatements) EXPECT() *MockProjectStatementsMockRecorder {
	return m.recorder
}

// CreateProject mocks base method.
func (m *MockProjectStatements) CreateProject(ctx context.Context, entity *domain.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockProjectStatementsMockRecorder) CreateProject(ctx, entity any) *MockProjectStatementsCreateProjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockProjectStatements)(nil).CreateProject), ctx, entity)
	return &MockProjectStatementsCreateProjectCall{Call: call}
}

// MockProjectStatementsCreateProjectCall wrap *gomock.Call
type MockProjectStatementsCreateProjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectStatementsCreateProjectCall) Return(arg0 error) *MockProjectStatementsCreateProjectCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectStatementsCreateProjectCall) Do(f func(context.Context, *domain.Project) error) *MockProjectStatementsCreateProjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectStatementsCreateProjectCall) DoAndReturn(f func(context.Context, *domain.Project) error) *MockProjectStatementsCreateProjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteProjectByID mocks base method.
func (m *MockProjectStatements) DeleteProjectByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectByID indicates an expected call of DeleteProjectByID.
func (mr *MockProjectStatementsMockRecorder) DeleteProjectByID(ctx, id any) *MockProjectStatementsDeleteProjectByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectByID", reflect.TypeOf((*MockProjectStatements)(nil).DeleteProjectByID), ctx, id)
	return &MockProjectStatementsDeleteProjectByIDCall{Call: call}
}

// MockProjectStatementsDeleteProjectByIDCall wrap *gomock.Call
type MockProjectStatementsDeleteProjectByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectStatementsDeleteProjectByIDCall) Return(arg0 error) *MockProjectStatementsDeleteProjectByIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectStatementsDeleteProjectByIDCall) Do(f func(context.Context, string) error) *MockProjectStatementsDeleteProjectByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectStatementsDeleteProjectByIDCall) DoAndReturn(f func(context.Context, string) error) *MockProjectStatementsDeleteProjectByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProjectByID mocks base method.
func (m *MockProjectStatements) GetProjectByID(ctx context.Context, id string) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByID", ctx, id)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByID indicates an expected call of GetProjectByID.
func (mr *MockProjectStatementsMockRecorder) GetProjectByID(ctx, id any) *MockProjectStatementsGetProjectByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByID", reflect.TypeOf((*MockProjectStatements)(nil).GetProjectByID), ctx, id)
	return &MockProjectStatementsGetProjectByIDCall{Call: call}
}

// MockProjectStatementsGetProjectByIDCall wrap *gomock.Call
type MockProjectStatementsGetProjectByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectStatementsGetProjectByIDCall) Return(arg0 *domain.Project, arg1 error) *MockProjectStatementsGetProjectByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectStatementsGetProjectByIDCall) Do(f func(context.Context, string) (*domain.Project, error)) *MockProjectStatementsGetProjectByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectStatementsGetProjectByIDCall) DoAndReturn(f func(context.Context, string) (*domain.Project, error)) *MockProjectStatementsGetProjectByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsStatements mocks base method.
func (m *MockProjectStatements) IsStatements() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IsStatements")
}

// IsStatements indicates an expected call of IsStatements.
func (mr *MockProjectStatementsMockRecorder) IsStatements() *MockProjectStatementsIsStatementsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStatements", reflect.TypeOf((*MockProjectStatements)(nil).IsStatements))
	return &MockProjectStatementsIsStatementsCall{Call: call}
}

// MockProjectStatementsIsStatementsCall wrap *gomock.Call
type MockProjectStatementsIsStatementsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectStatementsIsStatementsCall) Return() *MockProjectStatementsIsStatementsCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectStatementsIsStatementsCall) Do(f func()) *MockProjectStatementsIsStatementsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectStatementsIsStatementsCall) DoAndReturn(f func()) *MockProjectStatementsIsStatementsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListProjects mocks base method.
func (m *MockProjectStatements) ListProjects(ctx context.Context, filter *database.ListOptions[domain.ProjectField]) (*database.ListResult[*domain.Project], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx, filter)
	ret0, _ := ret[0].(*database.ListResult[*domain.Project])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockProjectStatementsMockRecorder) ListProjects(ctx, filter any) *MockProjectStatementsListProjectsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockProjectStatements)(nil).ListProjects), ctx, filter)
	return &MockProjectStatementsListProjectsCall{Call: call}
}

// MockProjectStatementsListProjectsCall wrap *gomock.Call
type MockProjectStatementsListProjectsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectStatementsListProjectsCall) Return(arg0 *database.ListResult[*domain.Project], arg1 error) *MockProjectStatementsListProjectsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectStatementsListProjectsCall) Do(f func(context.Context, *database.ListOptions[domain.ProjectField]) (*database.ListResult[*domain.Project], error)) *MockProjectStatementsListProjectsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectStatementsListProjectsCall) DoAndReturn(f func(context.Context, *database.ListOptions[domain.ProjectField]) (*database.ListResult[*domain.Project], error)) *MockProjectStatementsListProjectsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProject mocks base method.
func (m *MockProjectStatements) UpdateProject(ctx context.Context, entity *domain.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProject", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockProjectStatementsMockRecorder) UpdateProject(ctx, entity any) *MockProjectStatementsUpdateProjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockProjectStatements)(nil).UpdateProject), ctx, entity)
	return &MockProjectStatementsUpdateProjectCall{Call: call}
}

// MockProjectStatementsUpdateProjectCall wrap *gomock.Call
type MockProjectStatementsUpdateProjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectStatementsUpdateProjectCall) Return(arg0 error) *MockProjectStatementsUpdateProjectCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectStatementsUpdateProjectCall) Do(f func(context.Context, *domain.Project) error) *MockProjectStatementsUpdateProjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectStatementsUpdateProjectCall) DoAndReturn(f func(context.Context, *domain.Project) error) *MockProjectStatementsUpdateProjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockFlowDefinitionStatements is a mock of FlowDefinitionStatements interface.
type MockFlowDefinitionStatements struct {
	ctrl     *gomock.Controller
	recorder *MockFlowDefinitionStatementsMockRecorder
	isgomock struct{}
}

// MockFlowDefinitionStatementsMockRecorder is the mock recorder for MockFlowDefinitionStatements.
type MockFlowDefinitionStatementsMockRecorder struct {
	mock *MockFlowDefinitionStatements
}

// NewMockFlowDefinitionStatements creates a new mock instance.
func NewMockFlowDefinitionStatements(ctrl *gomock.Controller) *MockFlowDefinitionStatements {
	mock := &MockFlowDefinitionStatements{ctrl: ctrl}
	mock.recorder = &MockFlowDefinitionStatementsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowDefinitionStatements) EXPECT() *MockFlowDefinitionStatementsMockRecorder {
	return m.recorder
}

// CreateFlowDefinition mocks base method.
func (m *MockFlowDefinitionStatements) CreateFlowDefinition(ctx context.Context, entity *domain.FlowDefinition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFlowDefinition", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFlowDefinition indicates an expected call of CreateFlowDefinition.
func (mr *MockFlowDefinitionStatementsMockRecorder) CreateFlowDefinition(ctx, entity any) *MockFlowDefinitionStatementsCreateFlowDefinitionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFlowDefinition", reflect.TypeOf((*MockFlowDefinitionStatements)(nil).CreateFlowDefinition), ctx, entity)
	return &MockFlowDefinitionStatementsCreateFlowDefinitionCall{Call: call}
}

// MockFlowDefinitionStatementsCreateFlowDefinitionCall wrap *gomock.Call
type MockFlowDefinitionStatementsCreateFlowDefinitionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowDefinitionStatementsCreateFlowDefinitionCall) Return(arg0 error) *MockFlowDefinitionStatementsCreateFlowDefinitionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowDefinitionStatementsCreateFlowDefinitionCall) Do(f func(context.Context, *domain.FlowDefinition) error) *MockFlowDefinitionStatementsCreateFlowDefinitionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowDefinitionStatementsCreateFlowDefinitionCall) DoAndReturn(f func(context.Context, *domain.FlowDefinition) error) *MockFlowDefinitionStatementsCreateFlowDefinitionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteFlowDefinitionByID mocks base method.
func (m *MockFlowDefinitionStatements) DeleteFlowDefinitionByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFlowDefinitionByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFlowDefinitionByID indicates an expected call of DeleteFlowDefinitionByID.
func (mr *MockFlowDefinitionStatementsMockRecorder) DeleteFlowDefinitionByID(ctx, id any) *MockFlowDefinitionStatementsDeleteFlowDefinitionByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFlowDefinitionByID", reflect.TypeOf((*MockFlowDefinitionStatements)(nil).DeleteFlowDefinitionByID), ctx, id)
	return &MockFlowDefinitionStatementsDeleteFlowDefinitionByIDCall{Call: call}
}

// MockFlowDefinitionStatementsDeleteFlowDefinitionByIDCall wrap *gomock.Call
type MockFlowDefinitionStatementsDeleteFlowDefinitionByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowDefinitionStatementsDeleteFlowDefinitionByIDCall) Return(arg0 error) *MockFlowDefinitionStatementsDeleteFlowDefinitionByIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowDefinitionStatementsDeleteFlowDefinitionByIDCall) Do(f func(context.Context, string) error) *MockFlowDefinitionStatementsDeleteFlowDefinitionByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowDefinitionStatementsDeleteFlowDefinitionByIDCall) DoAndReturn(f func(context.Context, string) error) *MockFlowDefinitionStatementsDeleteFlowDefinitionByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetFlowDefinitionByID mocks base method.
func (m *MockFlowDefinitionStatements) GetFlowDefinitionByID(ctx context.Context, id string) (*domain.FlowDefinition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlowDefinitionByID", ctx, id)
	ret0, _ := ret[0].(*domain.FlowDefinition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlowDefinitionByID indicates an expected call of GetFlowDefinitionByID.
func (mr *MockFlowDefinitionStatementsMockRecorder) GetFlowDefinitionByID(ctx, id any) *MockFlowDefinitionStatementsGetFlowDefinitionByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlowDefinitionByID", reflect.TypeOf((*MockFlowDefinitionStatements)(nil).GetFlowDefinitionByID), ctx, id)
	return &MockFlowDefinitionStatementsGetFlowDefinitionByIDCall{Call: call}
}

// MockFlowDefinitionStatementsGetFlowDefinitionByIDCall wrap *gomock.Call
type MockFlowDefinitionStatementsGetFlowDefinitionByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowDefinitionStatementsGetFlowDefinitionByIDCall) Return(arg0 *domain.FlowDefinition, arg1 error) *MockFlowDefinitionStatementsGetFlowDefinitionByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowDefinitionStatementsGetFlowDefinitionByIDCall) Do(f func(context.Context, string) (*domain.FlowDefinition, error)) *MockFlowDefinitionStatementsGetFlowDefinitionByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowDefinitionStatementsGetFlowDefinitionByIDCall) DoAndReturn(f func(context.Context, string) (*domain.FlowDefinition, error)) *MockFlowDefinitionStatementsGetFlowDefinitionByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsStatements mocks base method.
func (m *MockFlowDefinitionStatements) IsStatements() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IsStatements")
}

// IsStatements indicates an expected call of IsStatements.
func (mr *MockFlowDefinitionStatementsMockRecorder) IsStatements() *MockFlowDefinitionStatementsIsStatementsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStatements", reflect.TypeOf((*MockFlowDefinitionStatements)(nil).IsStatements))
	return &MockFlowDefinitionStatementsIsStatementsCall{Call: call}
}

// MockFlowDefinitionStatementsIsStatementsCall wrap *gomock.Call
type MockFlowDefinitionStatementsIsStatementsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowDefinitionStatementsIsStatementsCall) Return() *MockFlowDefinitionStatementsIsStatementsCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowDefinitionStatementsIsStatementsCall) Do(f func()) *MockFlowDefinitionStatementsIsStatementsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowDefinitionStatementsIsStatementsCall) DoAndReturn(f func()) *MockFlowDefinitionStatementsIsStatementsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListFlowDefinitions mocks base method.
func (m *MockFlowDefinitionStatements) ListFlowDefinitions(ctx context.Context, filter *database.ListOptions[domain.FlowDefinitionField]) (*database.ListResult[*domain.FlowDefinition], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFlowDefinitions", ctx, filter)
	ret0, _ := ret[0].(*database.ListResult[*domain.FlowDefinition])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFlowDefinitions indicates an expected call of ListFlowDefinitions.
func (mr *MockFlowDefinitionStatementsMockRecorder) ListFlowDefinitions(ctx, filter any) *MockFlowDefinitionStatementsListFlowDefinitionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFlowDefinitions", reflect.TypeOf((*MockFlowDefinitionStatements)(nil).ListFlowDefinitions), ctx, filter)
	return &MockFlowDefinitionStatementsListFlowDefinitionsCall{Call: call}
}

// MockFlowDefinitionStatementsListFlowDefinitionsCall wrap *gomock.Call
type MockFlowDefinitionStatementsListFlowDefinitionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowDefinitionStatementsListFlowDefinitionsCall) Return(arg0 *database.ListResult[*domain.FlowDefinition], arg1 error) *MockFlowDefinitionStatementsListFlowDefinitionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowDefinitionStatementsListFlowDefinitionsCall) Do(f func(context.Context, *database.ListOptions[domain.FlowDefinitionField]) (*database.ListResult[*domain.FlowDefinition], error)) *MockFlowDefinitionStatementsListFlowDefinitionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowDefinitionStatementsListFlowDefinitionsCall) DoAndReturn(f func(context.Context, *database.ListOptions[domain.FlowDefinitionField]) (*database.ListResult[*domain.FlowDefinition], error)) *MockFlowDefinitionStatementsListFlowDefinitionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCryptoKeyStatements is a mock of CryptoKeyStatements interface.
type MockCryptoKeyStatements struct {
	ctrl     *gomock.Controller
	recorder *MockCryptoKeyStatementsMockRecorder
	isgomock struct{}
}

// MockCryptoKeyStatementsMockRecorder is the mock recorder for MockCryptoKeyStatements.
type MockCryptoKeyStatementsMockRecorder struct {
	mock *MockCryptoKeyStatements
}

// NewMockCryptoKeyStatements creates a new mock instance.
func NewMockCryptoKeyStatements(ctrl *gomock.Controller) *MockCryptoKeyStatements {
	mock := &MockCryptoKeyStatements{ctrl: ctrl}
	mock.recorder = &MockCryptoKeyStatementsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCryptoKeyStatements) EXPECT() *MockCryptoKeyStatementsMockRecorder {
	return m.recorder
}

// CreateEncryptionKey mocks base method.
func (m *MockCryptoKeyStatements) CreateEncryptionKey(ctx context.Context, dek *domain.EncryptionKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEncryptionKey", ctx, dek)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEncryptionKey indicates an expected call of CreateEncryptionKey.
func (mr *MockCryptoKeyStatementsMockRecorder) CreateEncryptionKey(ctx, dek any) *MockCryptoKeyStatementsCreateEncryptionKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEncryptionKey", reflect.TypeOf((*MockCryptoKeyStatements)(nil).CreateEncryptionKey), ctx, dek)
	return &MockCryptoKeyStatementsCreateEncryptionKeyCall{Call: call}
}

// MockCryptoKeyStatementsCreateEncryptionKeyCall wrap *gomock.Call
type MockCryptoKeyStatementsCreateEncryptionKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCryptoKeyStatementsCreateEncryptionKeyCall) Return(arg0 error) *MockCryptoKeyStatementsCreateEncryptionKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCryptoKeyStatementsCreateEncryptionKeyCall) Do(f func(context.Context, *domain.EncryptionKey) error) *MockCryptoKeyStatementsCreateEncryptionKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCryptoKeyStatementsCreateEncryptionKeyCall) DoAndReturn(f func(context.Context, *domain.EncryptionKey) error) *MockCryptoKeyStatementsCreateEncryptionKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetEncryptionKey mocks base method.
func (m *MockCryptoKeyStatements) GetEncryptionKey(ctx context.Context, filter database.Filter[domain.EncryptionKeyField]) (*domain.EncryptionKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncryptionKey", ctx, filter)
	ret0, _ := ret[0].(*domain.EncryptionKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncryptionKey indicates an expected call of GetEncryptionKey.
func (mr *MockCryptoKeyStatementsMockRecorder) GetEncryptionKey(ctx, filter any) *MockCryptoKeyStatementsGetEncryptionKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncryptionKey", reflect.TypeOf((*MockCryptoKeyStatements)(nil).GetEncryptionKey), ctx, filter)
	return &MockCryptoKeyStatementsGetEncryptionKeyCall{Call: call}
}

// MockCryptoKeyStatementsGetEncryptionKeyCall wrap *gomock.Call
type MockCryptoKeyStatementsGetEncryptionKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCryptoKeyStatementsGetEncryptionKeyCall) Return(arg0 *domain.EncryptionKey, arg1 error) *MockCryptoKeyStatementsGetEncryptionKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCryptoKeyStatementsGetEncryptionKeyCall) Do(f func(context.Context, database.Filter[domain.EncryptionKeyField]) (*domain.EncryptionKey, error)) *MockCryptoKeyStatementsGetEncryptionKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCryptoKeyStatementsGetEncryptionKeyCall) DoAndReturn(f func(context.Context, database.Filter[domain.EncryptionKeyField]) (*domain.EncryptionKey, error)) *MockCryptoKeyStatementsGetEncryptionKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsStatements mocks base method.
func (m *MockCryptoKeyStatements) IsStatements() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IsStatements")
}

// IsStatements indicates an expected call of IsStatements.
func (mr *MockCryptoKeyStatementsMockRecorder) IsStatements() *MockCryptoKeyStatementsIsStatementsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStatements", reflect.TypeOf((*MockCryptoKeyStatements)(nil).IsStatements))
	return &MockCryptoKeyStatementsIsStatementsCall{Call: call}
}

// MockCryptoKeyStatementsIsStatementsCall wrap *gomock.Call
type MockCryptoKeyStatementsIsStatementsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCryptoKeyStatementsIsStatementsCall) Return() *MockCryptoKeyStatementsIsStatementsCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCryptoKeyStatementsIsStatementsCall) Do(f func()) *MockCryptoKeyStatementsIsStatementsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCryptoKeyStatementsIsStatementsCall) DoAndReturn(f func()) *MockCryptoKeyStatementsIsStatementsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockJSONSchemaStatements is a mock of JSONSchemaStatements interface.
type MockJSONSchemaStatements struct {
	ctrl     *gomock.Controller
	recorder *MockJSONSchemaStatementsMockRecorder
	isgomock struct{}
}

// MockJSONSchemaStatementsMockRecorder is the mock recorder for MockJSONSchemaStatements.
type MockJSONSchemaStatementsMockRecorder struct {
	mock *MockJSONSchemaStatements
}

// NewMockJSONSchemaStatements creates a new mock instance.
func NewMockJSONSchemaStatements(ctrl *gomock.Controller) *MockJSONSchemaStatements {
	mock := &MockJSONSchemaStatements{ctrl: ctrl}
	mock.recorder = &MockJSONSchemaStatementsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJSONSchemaStatements) EXPECT() *MockJSONSchemaStatementsMockRecorder {
	return m.recorder
}

// CreateJSONSchema mocks base method.
func (m *MockJSONSchemaStatements) CreateJSONSchema(ctx context.Context, entity *domain.JSONSchema) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJSONSchema", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateJSONSchema indicates an expected call of CreateJSONSchema.
func (mr *MockJSONSchemaStatementsMockRecorder) CreateJSONSchema(ctx, entity any) *MockJSONSchemaStatementsCreateJSONSchemaCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJSONSchema", reflect.TypeOf((*MockJSONSchemaStatements)(nil).CreateJSONSchema), ctx, entity)
	return &MockJSONSchemaStatementsCreateJSONSchemaCall{Call: call}
}

// MockJSONSchemaStatementsCreateJSONSchemaCall wrap *gomock.Call
type MockJSONSchemaStatementsCreateJSONSchemaCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaStatementsCreateJSONSchemaCall) Return(arg0 error) *MockJSONSchemaStatementsCreateJSONSchemaCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaStatementsCreateJSONSchemaCall) Do(f func(context.Context, *domain.JSONSchema) error) *MockJSONSchemaStatementsCreateJSONSchemaCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaStatementsCreateJSONSchemaCall) DoAndReturn(f func(context.Context, *domain.JSONSchema) error) *MockJSONSchemaStatementsCreateJSONSchemaCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteJSONSchemaByID mocks base method.
func (m *MockJSONSchemaStatements) DeleteJSONSchemaByID(ctx context.Context, projectID, schemaID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJSONSchemaByID", ctx, projectID, schemaID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJSONSchemaByID indicates an expected call of DeleteJSONSchemaByID.
func (mr *MockJSONSchemaStatementsMockRecorder) DeleteJSONSchemaByID(ctx, projectID, schemaID any) *MockJSONSchemaStatementsDeleteJSONSchemaByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJSONSchemaByID", reflect.TypeOf((*MockJSONSchemaStatements)(nil).DeleteJSONSchemaByID), ctx, projectID, schemaID)
	return &MockJSONSchemaStatementsDeleteJSONSchemaByIDCall{Call: call}
}

// MockJSONSchemaStatementsDeleteJSONSchemaByIDCall wrap *gomock.Call
type MockJSONSchemaStatementsDeleteJSONSchemaByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaStatementsDeleteJSONSchemaByIDCall) Return(arg0 error) *MockJSONSchemaStatementsDeleteJSONSchemaByIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaStatementsDeleteJSONSchemaByIDCall) Do(f func(context.Context, string, string) error) *MockJSONSchemaStatementsDeleteJSONSchemaByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaStatementsDeleteJSONSchemaByIDCall) DoAndReturn(f func(context.Context, string, string) error) *MockJSONSchemaStatementsDeleteJSONSchemaByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetJSONSchemaByID mocks base method.
func (m *MockJSONSchemaStatements) GetJSONSchemaByID(ctx context.Context, projectID, schemaID string) (*domain.JSONSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSONSchemaByID", ctx, projectID, schemaID)
	ret0, _ := ret[0].(*domain.JSONSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJSONSchemaByID indicates an expected call of GetJSONSchemaByID.
func (mr *MockJSONSchemaStatementsMockRecorder) GetJSONSchemaByID(ctx, projectID, schemaID any) *MockJSONSchemaStatementsGetJSONSchemaByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSONSchemaByID", reflect.TypeOf((*MockJSONSchemaStatements)(nil).GetJSONSchemaByID), ctx, projectID, schemaID)
	return &MockJSONSchemaStatementsGetJSONSchemaByIDCall{Call: call}
}

// MockJSONSchemaStatementsGetJSONSchemaByIDCall wrap *gomock.Call
type MockJSONSchemaStatementsGetJSONSchemaByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaStatementsGetJSONSchemaByIDCall) Return(arg0 *domain.JSONSchema, arg1 error) *MockJSONSchemaStatementsGetJSONSchemaByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaStatementsGetJSONSchemaByIDCall) Do(f func(context.Context, string, string) (*domain.JSONSchema, error)) *MockJSONSchemaStatementsGetJSONSchemaByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaStatementsGetJSONSchemaByIDCall) DoAndReturn(f func(context.Context, string, string) (*domain.JSONSchema, error)) *MockJSONSchemaStatementsGetJSONSchemaByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsStatements mocks base method.
func (m *MockJSONSchemaStatements) IsStatements() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IsStatements")
}

// IsStatements indicates an expected call of IsStatements.
func (mr *MockJSONSchemaStatementsMockRecorder) IsStatements() *MockJSONSchemaStatementsIsStatementsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStatements", reflect.TypeOf((*MockJSONSchemaStatements)(nil).IsStatements))
	return &MockJSONSchemaStatementsIsStatementsCall{Call: call}
}

// MockJSONSchemaStatementsIsStatementsCall wrap *gomock.Call
type MockJSONSchemaStatementsIsStatementsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaStatementsIsStatementsCall) Return() *MockJSONSchemaStatementsIsStatementsCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaStatementsIsStatementsCall) Do(f func()) *MockJSONSchemaStatementsIsStatementsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaStatementsIsStatementsCall) DoAndReturn(f func()) *MockJSONSchemaStatementsIsStatementsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListJSONSchemas mocks base method.
func (m *MockJSONSchemaStatements) ListJSONSchemas(ctx context.Context, filter *database.ListOptions[domain.JSONSchemaField]) (*database.ListResult[*domain.JSONSchema], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJSONSchemas", ctx, filter)
	ret0, _ := ret[0].(*database.ListResult[*domain.JSONSchema])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJSONSchemas indicates an expected call of ListJSONSchemas.
func (mr *MockJSONSchemaStatementsMockRecorder) ListJSONSchemas(ctx, filter any) *MockJSONSchemaStatementsListJSONSchemasCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJSONSchemas", reflect.TypeOf((*MockJSONSchemaStatements)(nil).ListJSONSchemas), ctx, filter)
	return &MockJSONSchemaStatementsListJSONSchemasCall{Call: call}
}

// MockJSONSchemaStatementsListJSONSchemasCall wrap *gomock.Call
type MockJSONSchemaStatementsListJSONSchemasCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJSONSchemaStatementsListJSONSchemasCall) Return(arg0 *database.ListResult[*domain.JSONSchema], arg1 error) *MockJSONSchemaStatementsListJSONSchemasCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJSONSchemaStatementsListJSONSchemasCall) Do(f func(context.Context, *database.ListOptions[domain.JSONSchemaField]) (*database.ListResult[*domain.JSONSchema], error)) *MockJSONSchemaStatementsListJSONSchemasCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJSONSchemaStatementsListJSONSchemasCall) DoAndReturn(f func(context.Context, *database.ListOptions[domain.JSONSchemaField]) (*database.ListResult[*domain.JSONSchema], error)) *MockJSONSchemaStatementsListJSONSchemasCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
