// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/nextgen/internal/service (interfaces: TokenService)
//
// Generated by this command:
//
//	mockgen -typed -package mocks -destination ./mocks/token.mock.go . TokenService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/zitadel/nextgen/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenService is a mock of TokenService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
	isgomock struct{}
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// GenerateJWE mocks base method.
func (m *MockTokenService) GenerateJWE(ctx context.Context, data *domain.Token) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateJWE", ctx, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateJWE indicates an expected call of GenerateJWE.
func (mr *MockTokenServiceMockRecorder) GenerateJWE(ctx, data any) *MockTokenServiceGenerateJWECall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateJWE", reflect.TypeOf((*MockTokenService)(nil).GenerateJWE), ctx, data)
	return &MockTokenServiceGenerateJWECall{Call: call}
}

// MockTokenServiceGenerateJWECall wrap *gomock.Call
type MockTokenServiceGenerateJWECall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenServiceGenerateJWECall) Return(arg0 string, arg1 error) *MockTokenServiceGenerateJWECall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenServiceGenerateJWECall) Do(f func(context.Context, *domain.Token) (string, error)) *MockTokenServiceGenerateJWECall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenServiceGenerateJWECall) DoAndReturn(f func(context.Context, *domain.Token) (string, error)) *MockTokenServiceGenerateJWECall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetActivePreviewToken mocks base method.
func (m *MockTokenService) GetActivePreviewToken(ctx context.Context, projectID string) (*domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivePreviewToken", ctx, projectID)
	ret0, _ := ret[0].(*domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivePreviewToken indicates an expected call of GetActivePreviewToken.
func (mr *MockTokenServiceMockRecorder) GetActivePreviewToken(ctx, projectID any) *MockTokenServiceGetActivePreviewTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivePreviewToken", reflect.TypeOf((*MockTokenService)(nil).GetActivePreviewToken), ctx, projectID)
	return &MockTokenServiceGetActivePreviewTokenCall{Call: call}
}

// MockTokenServiceGetActivePreviewTokenCall wrap *gomock.Call
type MockTokenServiceGetActivePreviewTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenServiceGetActivePreviewTokenCall) Return(arg0 *domain.Token, arg1 error) *MockTokenServiceGetActivePreviewTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenServiceGetActivePreviewTokenCall) Do(f func(context.Context, string) (*domain.Token, error)) *MockTokenServiceGetActivePreviewTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenServiceGetActivePreviewTokenCall) DoAndReturn(f func(context.Context, string) (*domain.Token, error)) *MockTokenServiceGetActivePreviewTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IntrospectToken mocks base method.
func (m *MockTokenService) IntrospectToken(ctx context.Context, token string) (*domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntrospectToken", ctx, token)
	ret0, _ := ret[0].(*domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IntrospectToken indicates an expected call of IntrospectToken.
func (mr *MockTokenServiceMockRecorder) IntrospectToken(ctx, token any) *MockTokenServiceIntrospectTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntrospectToken", reflect.TypeOf((*MockTokenService)(nil).IntrospectToken), ctx, token)
	return &MockTokenServiceIntrospectTokenCall{Call: call}
}

// MockTokenServiceIntrospectTokenCall wrap *gomock.Call
type MockTokenServiceIntrospectTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenServiceIntrospectTokenCall) Return(arg0 *domain.Token, arg1 error) *MockTokenServiceIntrospectTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenServiceIntrospectTokenCall) Do(f func(context.Context, string) (*domain.Token, error)) *MockTokenServiceIntrospectTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenServiceIntrospectTokenCall) DoAndReturn(f func(context.Context, string) (*domain.Token, error)) *MockTokenServiceIntrospectTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RevokeToken mocks base method.
func (m *MockTokenService) RevokeToken(ctx context.Context, projectID, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx, projectID, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockTokenServiceMockRecorder) RevokeToken(ctx, projectID, tokenID any) *MockTokenServiceRevokeTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockTokenService)(nil).RevokeToken), ctx, projectID, tokenID)
	return &MockTokenServiceRevokeTokenCall{Call: call}
}

// MockTokenServiceRevokeTokenCall wrap *gomock.Call
type MockTokenServiceRevokeTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenServiceRevokeTokenCall) Return(arg0 error) *MockTokenServiceRevokeTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenServiceRevokeTokenCall) Do(f func(context.Context, string, string) error) *MockTokenServiceRevokeTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenServiceRevokeTokenCall) DoAndReturn(f func(context.Context, string, string) error) *MockTokenServiceRevokeTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
