import { describe, expect, it } from "vitest";

type CheckPrTitleModule = {
  parseSemanticConfig: (source: string) => { types: string[]; scopes: string[] };
  parseConventionalTitle: (title: string) => {
    ok: boolean;
    type?: string;
    scope?: string;
    breaking?: boolean;
    summary?: string;
  };
  isNonShippingFile: (file: string) => boolean;
  suggestType: (files: string[]) => string;
  checkPrTitle: (options: {
    title: string;
    files: string[];
    config?: { types: string[]; scopes: string[] };
  }) => {
    ok: boolean;
    shipping: string[];
    errors: Array<{ code: string; message: string }>;
    warnings: Array<{ code: string; message: string }>;
    nextAction: string;
  };
  renderStepSummary: (report: unknown) => string;
  parseArgs: (args: string[]) => { base: string; title?: string; summary: boolean; help: boolean };
};

const load = async (): Promise<CheckPrTitleModule> =>
  (await import("../../../../../scripts/check-pr-title.mjs")) as unknown as CheckPrTitleModule;

const config = {
  types: ["feat", "fix", "docs", "refactor", "perf", "test", "build", "ci", "chore", "revert"],
  scopes: ["api", "config", "console", "database", "login", "deps", "security"],
};

describe("parseSemanticConfig", () => {
  it("reads the flat type and scope lists and drops comments", () => {
    const source = [
      "# Always validate the PR title",
      "titleOnly: true",
      "",
      "types:",
      "  - feat # new capability",
      "  - fix # corrects shipped behavior",
      "",
      "scopes:",
      "  # Backend",
      "  - api",
      "  - console",
    ].join("\n");

    expect(parseSemanticConfigOf(source)).resolves.toEqual({
      types: ["feat", "fix"],
      scopes: ["api", "console"],
    });
  });

  const parseSemanticConfigOf = async (source: string) =>
    (await load()).parseSemanticConfig(source);
});

describe("parseConventionalTitle", () => {
  it.each([
    ["feat: delete user", { type: "feat", scope: undefined, summary: "delete user" }],
    ["fix(login): keep the prompt", { type: "fix", scope: "login", summary: "keep the prompt" }],
    [
      "feat!: drop the v1 endpoint",
      { type: "feat", scope: undefined, summary: "drop the v1 endpoint" },
    ],
  ])("parses %s", async (title, expected) => {
    const { parseConventionalTitle } = await load();
    expect(parseConventionalTitle(title)).toMatchObject({ ok: true, ...expected });
  });

  it.each(["no type here", "feat:", "feat :missing space", ""])("rejects %s", async (title) => {
    const { parseConventionalTitle } = await load();
    expect(parseConventionalTitle(title).ok).toBe(false);
  });
});

describe("isNonShippingFile", () => {
  it.each([
    "internal/domain/user.go",
    "cmd/server/server.go",
    "api/openapi/user.yaml",
    "apps/cli/src/commands/setup.ts",
    "packages/sdk-react/src/index.ts",
    "packages/sdk-react/README.md",
    // apps/cli/package.json lists SKILLS.md in `files`, so it installs with the CLI.
    "apps/cli/SKILLS.md",
    // Scaffolded into a customer's project, so it is product, not repo docs.
    "packages/config/defaults/README-schemas.md",
    "apps/cli/src/lib/orca/patchers/rule/next/README.md",
    // The console and login UI ship inside the server container.
    "apps/console/src/routes/users.tsx",
    "apps/login-ui/src/app.ts",
    // On the release train since #692 — customers install it from npm.
    "packages/testing/src/passkey.ts",
  ])("treats %s as shipping", async (file) => {
    const { isNonShippingFile } = await load();
    expect(isNonShippingFile(file)).toBe(false);
  });

  it.each([
    ".github/workflows/ci.yml",
    ".changeset/some-slug.md",
    "docs/adrs/030-errreport.md",
    "scripts/check-pr-title.mjs",
    "AGENTS.md",
    "README.md",
    "pnpm-lock.yaml",
    ".nvmrc",
    "apps/console/AGENTS.md",
    "apps/console/docs/styling.md",
    "apps/console-e2e/tests/users.spec.ts",
    "apps/demo-next/next-env.d.ts",
    "apps/storybook/main.ts",
    "packages/api-mock/src/handlers.ts",
    "packages/components/moon.yml",
    "internal/domain/user_test.go",
    "packages/sdk-react/src/index.test.ts",
    // Build tooling inside a package produces what ships without shipping.
    "packages/design-tokens/scripts/build.ts",
    // design-tokens is a build input, never published — its README reaches nobody.
    "packages/design-tokens/README.md",
    "packages/design-tokens/package.json",
    // SKILLS.md ships only from a published root; outside one it is repo-only.
    "packages/design-tokens/SKILLS.md",
    // Generated by `changeset version` — a version PR is not shipping work.
    "packages/sdk-react/CHANGELOG.md",
  ])("treats %s as non-shipping", async (file) => {
    const { isNonShippingFile } = await load();
    expect(isNonShippingFile(file)).toBe(true);
  });
});

describe("checkPrTitle", () => {
  it("fails feat when nothing in the diff reaches a user", async () => {
    const { checkPrTitle } = await load();
    const report = checkPrTitle({
      title: "feat: extend the api-mock flow fixtures",
      files: [
        "packages/api-mock/src/handlers.ts",
        "apps/console-e2e/playwright.real.config.mts",
        "apps/demo-next/next-env.d.ts",
      ],
      config,
    });

    expect(report.ok).toBe(false);
    expect(report.errors.map((error) => error.code)).toContain("non-shipping-customer-type");
    expect(report.errors[0]?.message).toContain('Use "test:"');
  });

  it("allows feat for kit API changes now that @zitadel/testing ships (#692)", async () => {
    const { checkPrTitle } = await load();
    const report = checkPrTitle({
      title: "feat: add a virtual-passkey helper to @zitadel/testing",
      files: [
        "packages/testing/src/passkey.ts",
        "packages/testing/tests/unit/passkey.test.ts",
        "apps/demo-next-e2e/src-real/passkey.spec.ts",
      ],
      config,
    });

    expect(report.ok).toBe(true);
  });

  it("fails feat on a build pipeline (#494)", async () => {
    const { checkPrTitle } = await load();
    const report = checkPrTitle({
      title: "feat: add Figma export sync pipeline for design tokens",
      files: [
        ".github/workflows/sync-design-tokens.yml",
        "packages/design-tokens/AGENTS.md",
        "packages/design-tokens/README.md",
        "packages/design-tokens/package.json",
        "packages/design-tokens/scripts/build.ts",
        "packages/design-tokens/scripts/sync-from-export.ts",
      ],
      config,
    });

    expect(report.ok).toBe(false);
    expect(report.shipping).toEqual([]);
    expect(report.errors[0]?.message).toContain('Use "build:"');
  });

  it("warns when chore changes a shipped default (#526)", async () => {
    const { checkPrTitle } = await load();
    const report = checkPrTitle({
      title: "chore: set argon2id as default password hashing algorithm",
      files: ["cmd/server/server.go", "internal/crypto/hash.go", ".changeset/argon2id.md"],
      config,
    });

    expect(report.ok).toBe(true);
    expect(report.warnings.map((warning) => warning.code)).toContain("shipping-non-customer-type");
  });

  it("warns when docs changes a template a customer receives (#482)", async () => {
    const { checkPrTitle } = await load();
    const report = checkPrTitle({
      title: "docs(config): improve schema README guidance",
      files: ["packages/config/defaults/README-schemas.md", ".changeset/clever-boxes-sort.md"],
      config,
    });

    expect(report.ok).toBe(true);
    expect(report.warnings).toHaveLength(1);
  });

  it("passes feat on a real server change (#637)", async () => {
    const { checkPrTitle } = await load();
    const report = checkPrTitle({
      title: "feat: delete user",
      files: [
        "internal/domain/user.go",
        "internal/api/user_service.go",
        ".changeset/delete-user.md",
      ],
      config,
    });

    expect(report.ok).toBe(true);
    expect(report.warnings).toEqual([]);
  });

  it("passes refactor that carries a changeset — a changeset does not force feat", async () => {
    const { checkPrTitle } = await load();
    const report = checkPrTitle({
      title: "refactor(database): migrate token repository to statements",
      files: ["internal/storage/v2/token.go", ".changeset/token-statements.md"],
      config,
    });

    expect(report.ok).toBe(true);
    expect(report.warnings).toEqual([]);
  });

  it("passes feat(console) — the console ships inside the server container", async () => {
    const { checkPrTitle } = await load();
    const report = checkPrTitle({
      title: "feat(console): shadcn Users shell with dual design-token pipeline",
      files: ["apps/console/src/routes/users.tsx", "apps/console/AGENTS.md"],
      config,
    });

    expect(report.ok).toBe(true);
  });

  it("passes feat when only part of the diff ships", async () => {
    const { checkPrTitle } = await load();
    const report = checkPrTitle({
      title: "feat: add use-case selection to zitadel setup",
      files: ["apps/cli/src/commands/setup.ts", ".github/workflows/ci.yml", "docs/adrs/031.md"],
      config,
    });

    expect(report.ok).toBe(true);
  });

  it("does not block a feat that only changes the shipped CLI agent contract", async () => {
    const { checkPrTitle } = await load();
    const report = checkPrTitle({
      title: "feat(cli): document the JSON envelope",
      files: ["apps/cli/SKILLS.md"],
      config: { ...config, scopes: [...config.scopes, "cli"] },
    });

    expect(report.ok).toBe(true);
    expect(report.shipping).toEqual(["apps/cli/SKILLS.md"]);
  });

  it("rejects an unknown type and an unknown scope", async () => {
    const { checkPrTitle } = await load();

    expect(
      checkPrTitle({ title: "feature: add a thing", files: ["internal/x.go"], config }).errors.map(
        (error) => error.code,
      ),
    ).toContain("unknown-type");

    expect(
      checkPrTitle({
        title: "feat(docs): add a thing",
        files: ["internal/x.go"],
        config,
      }).errors.map((error) => error.code),
    ).toContain("unknown-scope");
  });

  it("rejects a title that is not conventional at all", async () => {
    const { checkPrTitle } = await load();
    const report = checkPrTitle({ title: "Update release docs", files: ["docs/x.md"], config });

    expect(report.ok).toBe(false);
    expect(report.errors[0]?.code).toBe("unparseable-title");
  });

  it("does not judge the type when the diff is empty", async () => {
    const { checkPrTitle } = await load();
    expect(checkPrTitle({ title: "feat: add a thing", files: [], config }).ok).toBe(true);
  });

  it("leaves test, build, and refactor unwarned on shipping paths", async () => {
    const { checkPrTitle } = await load();
    for (const title of [
      "test: share statement contract suites across dialects",
      "build(deps): clear the open Dependabot security alerts",
      "refactor: route passkey creation through UserService",
    ]) {
      const report = checkPrTitle({ title, files: ["internal/domain/user.go"], config });
      expect(report.ok).toBe(true);
      expect(report.warnings).toEqual([]);
    }
  });
});

describe("suggestType", () => {
  it.each([
    [["packages/api-mock/src/x.ts", "apps/console-e2e/a.spec.ts"], "test"],
    [[".github/workflows/ci.yml"], "ci"],
    [["docs/adrs/030.md", "AGENTS.md"], "docs"],
    [["packages/design-tokens/scripts/build.ts", ".github/workflows/sync.yml"], "build"],
  ])("suggests %s -> %s", async (files, expected) => {
    const { suggestType } = await load();
    expect(suggestType(files)).toBe(expected);
  });
});

describe("parseArgs", () => {
  it("reads title, base, and summary", async () => {
    const { parseArgs } = await load();
    expect(parseArgs(["--title", "feat: x", "--base", "abc123", "--summary"])).toEqual({
      base: "abc123",
      title: "feat: x",
      summary: true,
      help: false,
    });
  });

  it("rejects an unknown argument and a valueless flag", async () => {
    const { parseArgs } = await load();
    expect(() => parseArgs(["--nope"])).toThrow(/unknown argument/);
    expect(() => parseArgs(["--title"])).toThrow(/requires a value/);
  });
});

describe("renderStepSummary", () => {
  it("names the failure and the next action", async () => {
    const { checkPrTitle, renderStepSummary } = await load();
    const summary = renderStepSummary(
      checkPrTitle({ title: "feat: add a harness", files: ["packages/api-mock/src/x.ts"], config }),
    );

    expect(summary).toContain("# PR title");
    expect(summary).toContain("Status: failed");
    expect(summary).toContain("## Next action");
  });
});
