#!/usr/bin/env node
import { copyFile, mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { forwardedArgs, isDirectRun, run, runCapture } from "./dev-process.mjs";
import {
  buildContainerImage,
  hostLinuxPlatform,
  readServerRelease,
  releaseDir,
} from "./release-artifacts.mjs";

const defaultRepoRoot = fileURLToPath(new URL("..", import.meta.url));
const COMPOSE_FILE = join("docs", "operations", "docker-compose.yaml");
const HEALTH_TIMEOUT_MS = 90_000;

// Smokes the release deployment surfaces users actually consume: today the
// maintained compose file, later a helm chart (add a target below). The
// server's health endpoints are unconditional stubs, so the Postgres signal
// comes from booting with the documented bootstrap-user mount - a failed
// database write kills the server before /healthz ever answers.
const TARGETS = {
  compose: runComposeSmoke,
};

export async function runDeploySmoke(options = {}) {
  const target = options.target ?? "compose";
  const handler = TARGETS[target];
  if (!handler) {
    throw new Error(
      `unknown deploy smoke target: ${target}; available: ${Object.keys(TARGETS).join(", ")}`,
    );
  }
  return await handler(options);
}

async function runComposeSmoke(options) {
  const repoRoot = options.repoRoot ?? defaultRepoRoot;
  const log = options.log ?? console.log;
  const runFn = options.run ?? run;
  const runCaptureFn = options.runCapture ?? runCapture;
  const fetchImpl = options.fetchImpl ?? globalThis.fetch;
  const image = options.image;
  if (!image) {
    throw new Error("compose smoke requires an image tag");
  }

  const workDir = options.workDir ?? (await mkdtemp(join(tmpdir(), "zitadel-deploy-smoke-")));
  const port = options.port ?? (await freePort());
  const projectName = options.projectName ?? `nextgen-smoke-${port}`;
  const diagnosticsDir =
    options.diagnosticsDir ?? process.env.ZITADEL_SMOKE_DIAGNOSTICS_DIR ?? "";

  // The compose file is copied verbatim: the smoke must validate the exact
  // file the docs ship. Compose requires .env to exist next to it; the
  // override wires the documented bootstrap-user mount.
  await copyFile(join(repoRoot, COMPOSE_FILE), join(workDir, "docker-compose.yaml"));
  await writeFile(
    join(workDir, ".env"),
    "# generated by deploy-smoke; compose requires this file to exist\n",
  );
  await writeFile(join(workDir, "smoke.override.yaml"), composeOverride(repoRoot));

  const composeArgs = [
    "compose",
    "-p",
    projectName,
    "-f",
    "docker-compose.yaml",
    "-f",
    "smoke.override.yaml",
  ];
  const composeEnv = {
    ...process.env,
    NEXTGEN_IMAGE: image,
    NEXTGEN_PORT: String(port),
  };
  const composeExec = { cwd: workDir, env: composeEnv };
  const baseUrl = `http://127.0.0.1:${port}`;

  log(`deploy smoke (compose): booting ${image} as project ${projectName} on port ${port}`);
  try {
    await runFn("docker", [...composeArgs, "up", "-d", "--wait"], composeExec);
    await probeDeployment({ baseUrl, fetchImpl, log, timeoutMs: options.timeoutMs });
    await assertServicesRunning({ composeArgs, composeExec, runCapture: runCaptureFn });
    log(`deploy smoke (compose): ${image} serves ${baseUrl} with Postgres-backed bootstrap`);
    return { target: "compose", image, baseUrl, projectName };
  } catch (error) {
    await collectDiagnostics({
      composeArgs,
      composeExec,
      diagnosticsDir,
      log,
      runCapture: runCaptureFn,
    });
    throw error;
  } finally {
    if (options.keep) {
      log(`deploy smoke: keeping project ${projectName} in ${workDir}`);
    } else {
      await runFn("docker", [...composeArgs, "down", "-v", "--remove-orphans"], composeExec).catch(
        (teardownError) => log(`deploy smoke: teardown failed: ${teardownError.message}`),
      );
      if (!options.workDir) {
        await rm(workDir, { recursive: true, force: true });
      }
    }
  }
}

export function composeOverride(repoRoot) {
  return `services:
  nextgen:
    volumes:
      - ${join(repoRoot, "examples", "bootstrap-users")}:/bootstrap:ro
    command:
      - server
      - --user-file
      - /bootstrap/demo-admin.json
`;
}

export async function probeDeployment(options) {
  const fetchImpl = options.fetchImpl ?? globalThis.fetch;
  const log = options.log ?? console.log;
  const baseUrl = options.baseUrl;
  const timeoutMs = options.timeoutMs ?? HEALTH_TIMEOUT_MS;
  const delayMs = options.delayMs ?? 1000;

  await waitForOk(`${baseUrl}/healthz`, { fetchImpl, timeoutMs, delayMs });
  log(`deploy smoke: ${baseUrl}/healthz is healthy`);

  for (const path of ["/livez", "/readyz"]) {
    const response = await fetchImpl(`${baseUrl}${path}`);
    if (!response.ok) {
      throw new Error(`deploy smoke: ${path} returned ${response.status}`);
    }
  }

  // The API surface must reject the request through the structured error
  // model, not a bare 404/500: this proves the generated router and error
  // handler are in the binary, which a stub health endpoint cannot. The
  // session cookie is a required parameter, so today's rejection is a 400
  // ("req.invalid") from the decode layer; 401/403 also count as rejections.
  const response = await fetchImpl(`${baseUrl}/sessions/me`);
  if (![400, 401, 403].includes(response.status)) {
    throw new Error(
      `deploy smoke: unauthenticated /sessions/me should be rejected with 400/401/403, got ${response.status}`,
    );
  }
  let body;
  try {
    body = await response.json();
  } catch {
    throw new Error("deploy smoke: unauthenticated /sessions/me must return a JSON error body");
  }
  if (!body || typeof body !== "object" || typeof body.code !== "string") {
    throw new Error(
      "deploy smoke: unauthenticated /sessions/me must return the structured error model " +
        `(object with a string code), got: ${JSON.stringify(body).slice(0, 200)}`,
    );
  }
  log(
    `deploy smoke: API surface rejects unauthenticated /sessions/me with ${response.status} (${body.code})`,
  );
}

async function waitForOk(url, { fetchImpl, timeoutMs, delayMs }) {
  const deadline = Date.now() + timeoutMs;
  let lastError = "";
  while (Date.now() < deadline) {
    try {
      const response = await fetchImpl(url);
      if (response.ok) {
        return;
      }
      lastError = `${url} returned ${response.status}`;
    } catch (error) {
      lastError = error instanceof Error ? error.message : String(error);
    }
    await delay(delayMs);
  }
  throw new Error(`deploy smoke: timed out waiting for ${url}: ${lastError}`);
}

async function assertServicesRunning({ composeArgs, composeExec, runCapture: runCaptureFn }) {
  const result = await runCaptureFn(
    "docker",
    [...composeArgs, "ps", "--services", "--filter", "status=running"],
    composeExec,
  );
  const running = new Set(result.stdout.split(/\r?\n/).filter(Boolean));
  const missing = ["nextgen", "postgres"].filter((service) => !running.has(service));
  if (missing.length > 0) {
    throw new Error(
      `deploy smoke: services not running after probes: ${missing.join(", ")} ` +
        "(the server likely crashed after startup; see diagnostics)",
    );
  }
}

async function collectDiagnostics({ composeArgs, composeExec, diagnosticsDir, log, runCapture: runCaptureFn }) {
  if (!diagnosticsDir) {
    return;
  }
  try {
    await mkdir(diagnosticsDir, { recursive: true });
    const logs = await runCaptureFn("docker", [...composeArgs, "logs", "--no-color"], composeExec)
      .then((result) => result.stdout)
      .catch((error) => `failed to collect compose logs: ${error.message}`);
    await writeFile(join(diagnosticsDir, "compose-logs.txt"), logs);
    const ps = await runCaptureFn("docker", [...composeArgs, "ps", "-a"], composeExec)
      .then((result) => result.stdout)
      .catch((error) => `failed to collect compose ps: ${error.message}`);
    await writeFile(join(diagnosticsDir, "compose-ps.txt"), ps);
    log(`deploy smoke: diagnostics written to ${diagnosticsDir}`);
  } catch (error) {
    log(`deploy smoke: failed to write diagnostics: ${error.message}`);
  }
}

// Builds a host-platform image from the docker context that release:build
// produced - shared by the standalone smoke task and the rehearsal.
export async function buildSmokeImage(options = {}) {
  const repoRoot = options.repoRoot ?? defaultRepoRoot;
  const release = options.release ?? (await readServerRelease(repoRoot));
  const outDir = releaseDir(repoRoot, release.version);
  const contextDir = join(outDir, "docker-context");
  const tag = options.tag ?? `ghcr.io/zitadel/nextgen:${release.version}-smoke`;
  await buildContainerImage({
    repoRoot,
    outDir,
    release,
    contextDir,
    load: true,
    platforms: [hostLinuxPlatform()],
    tags: [tag],
  });
  return tag;
}

export function parseArgs(args) {
  const parsed = { target: "compose", image: "", keep: false, help: false };
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    switch (arg) {
      case "--target":
        parsed.target = args[++index] ?? "";
        if (!parsed.target) throw new Error("--target requires a value");
        break;
      case "--image":
        parsed.image = args[++index] ?? "";
        if (!parsed.image) throw new Error("--image requires a value");
        break;
      case "--keep":
        parsed.keep = true;
        break;
      case "--help":
      case "-h":
        parsed.help = true;
        break;
      default:
        throw new Error(`unknown option: ${arg}`);
    }
  }
  return parsed;
}

async function freePort() {
  return await new Promise((resolvePort, rejectPort) => {
    const server = createServer();
    server.once("error", rejectPort);
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      server.close(() => resolvePort(address.port));
    });
  });
}

function delay(ms) {
  return new Promise((resolveDelay) => setTimeout(resolveDelay, ms));
}

export async function main(args = forwardedArgs()) {
  const parsed = parseArgs(args);
  if (parsed.help) {
    console.log(`usage: node scripts/deploy-smoke.mjs [--target compose] [--image <tag>] [--keep]

Deploys the built release image through the documented deployment surface
(docs/operations/docker-compose.yaml) and smoke-tests it: /healthz, /livez,
/readyz, bootstrap-user write path against Postgres, and a structured rejection
from the unauthenticated API. Without --image, builds a host-platform image
from the docker context that release:build produced.
`);
    return;
  }

  const image = parsed.image || (await buildSmokeImage({ repoRoot: defaultRepoRoot }));
  await runDeploySmoke({
    repoRoot: defaultRepoRoot,
    target: parsed.target,
    image,
    keep: parsed.keep,
  });
}

if (isDirectRun(import.meta.url)) {
  try {
    await main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(error?.code ?? 1);
  }
}
