/**
 * The Go code-generation outputs, as one list.
 *
 * These globs mirror the `outputs` of the `server:generate` Moon task — keep
 * the two in sync. They are deliberately file-precise rather than
 * directory-wide: `internal/domain` holds hand-written code alongside its
 * generated `*_enumer.go`, so a directory-level pattern here would be a
 * destructive mistake waiting to happen.
 */
import { globSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = fileURLToPath(new URL("..", import.meta.url));

export const GENERATED_GLOBS = [
  "api/generated/**/*.go",
  "api/openapi/components/schemas/errors/**/*.yaml",
  "api/openapi/endpoints/**/*-error-response.yaml",
  "internal/**/*_enumer.go",
  "internal/**/*.mock.go",
];

/**
 * Outputs that must survive a prune.
 *
 * ogen's output is the one generated tree the pipeline cannot regenerate from
 * nothing, because it sits in a cycle: `gen_openapi_errors` type-loads
 * `./internal/...` to infer each handler's error set, `internal/api` imports
 * `api/generated`, and ogen only produces `api/generated` from a spec whose
 * endpoints `$ref` the error-response files `gen_openapi_errors` writes. No
 * ordering breaks that — the client is generated from the spec the analysis of
 * the client's own consumers produces.
 *
 * Exempting it costs nothing, because the prune exists to surface output that
 * nothing generates any more and ogen already does that for its own target:
 * it runs with `--clean`, which drops files the spec no longer calls for. The
 * generators without that property are the ones the prune still covers.
 */
export const PRUNE_EXEMPT_GLOBS = ["api/generated/**/*.go"];

/**
 * Every generator here stamps a marker in the first few lines — ogen and
 * MockGen write "Code generated by …", gen_openapi_errors writes
 * "generated by …". Checking it is the safety net that makes deletion safe:
 * a glob that ever matches a hand-written file is caught here instead of
 * silently eating someone's work.
 */
const MARKER = /^(\/\/|#).*generated by .*DO NOT EDIT/im;

export function hasGeneratedMarker(absPath) {
  // The marker is always in the header; reading whole files to find it would
  // mean slurping all of api/generated for nothing.
  return MARKER.test(readFileSync(absPath, "utf8").slice(0, 512));
}

/**
 * Splits the prunable outputs into files carrying the marker and files that do
 * not. Callers decide what to do with the strays; nothing here deletes
 * anything. [PRUNE_EXEMPT_GLOBS] is held back — those files are generated, but
 * removing them breaks the regenerate that would restore them.
 */
export function collectGeneratedFiles() {
  const matched = GENERATED_GLOBS.flatMap((pattern) => globSync(pattern, { cwd: ROOT }));
  const exempt = new Set(PRUNE_EXEMPT_GLOBS.flatMap((pattern) => globSync(pattern, { cwd: ROOT })));
  const unique = [...new Set(matched)].filter((rel) => !exempt.has(rel)).sort();

  const generated = [];
  const unmarked = [];
  for (const rel of unique) {
    (hasGeneratedMarker(join(ROOT, rel)) ? generated : unmarked).push(rel);
  }
  return { generated, unmarked };
}
