/**
 * Generates the JSON meta-schemas under `api/openapi/endpoints/schemas/` from
 * the OpenAPI YAML that already describes the same shapes.
 *
 *   corepack pnpm exec tsx scripts/generate-meta-schemas.ts
 *
 * The YAML is the single source, and it declares what gets generated: a
 * schema file carrying `x-meta-schema` is emitted as `<same name>.json`. The
 * value is `true`, or `json-schema` when the instances it validates are JSON
 * Schema documents themselves; those gain `allOf: [{$ref: <draft-2020-12>}]`,
 * which the YAML cannot spell because orval resolves every `$ref` it finds,
 * even under an `x-` key, and the draft is not part of the spec. Its consumers
 * are the Go server, which compiles the user meta-schemas at runtime to
 * validate the JSON Schema documents customers upload, and the CLI, which
 * ships the flow and branding schemas into a project's `.zitadel/meta/` so
 * editors validate the files a developer edits.
 *
 * A file on disk has the same shape as the API, with one generic exception: a
 * field marked `x-local: file` may hold `{ "$file": "<path>" }` instead of its
 * value, so a long string such as a login template lives in its own file. The
 * generated schema accepts either form, as `anyOf` the field's own schema and
 * `#/$defs/LocalFileReference`, and keeps the annotation. OpenAPI tooling
 * ignores `x-` keys, so the API still takes only the value; the CLI replaces
 * every reference with the file's content before upload.
 *
 * A `$ref` to another emitted file stays a file reference, renamed to `.json`,
 * because both the Go loader and the editor resolve siblings. A `$ref` to a
 * file that is not emitted is inlined under `$defs`, so the output is
 * self-contained without shipping every component schema.
 *
 * The conversion rules are pinned by `generate-meta-schemas.test.ts`; the
 * generated-output check only proves the committed files match whatever this
 * script currently produces.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { parse } from "yaml";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "api/openapi/endpoints/schemas");
export const DRAFT = "https://json-schema.org/draft/2020-12/schema";
export const MARKER = "Code generated by scripts/generate-meta-schemas.ts; DO NOT EDIT.";
const EMIT_KEY = "x-meta-schema";
const LOCAL_KEY = "x-local";
const LOCAL_FILE = "file";
const LOCAL_FILE_DEF = "LocalFileReference";

export type Schema = { [key: string]: unknown };

/** Keywords that describe a field rather than constrain it; they stay outside the `anyOf`. */
const ANNOTATION_KEYWORDS = new Set([
  "title",
  "description",
  "examples",
  "default",
  "deprecated",
  "readOnly",
  "writeOnly",
]);

const LOCAL_FILE_REFERENCE: Schema = {
  type: "object",
  additionalProperties: false,
  required: ["$file"],
  properties: {
    $file: {
      type: "string",
      minLength: 1,
      description:
        "Path to the file whose content is this value, relative to the file holding the reference. The CLI inlines it before upload.",
    },
  },
};

const isSchema = (value: unknown): value is Schema =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const loadYaml = (path: string): Schema => parse(readFileSync(path, "utf8")) as Schema;

/** `flow-definition-step.yaml` → `FlowDefinitionStep`; also the default `title`. */
export const defName = (file: string): string =>
  basename(file, ".yaml")
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

/**
 * Converts one YAML node to its JSON Schema form: OpenAPI's `example` becomes
 * `examples`, the emit marker is dropped, file `$ref`s resolve per the rule in
 * the header, and an `x-local: file` field also accepts a `$file` reference.
 * Inlined files go through the same conversion.
 */
function convert(
  node: unknown,
  dir: string,
  emitted: ReadonlySet<string>,
  defs: Map<string, Schema>,
): unknown {
  if (Array.isArray(node)) {
    return node.map((item) => convert(item, dir, emitted, defs));
  }
  if (!isSchema(node)) {
    return node;
  }

  const { example, [EMIT_KEY]: _emit, [LOCAL_KEY]: local, ...rest } = node;
  const out: Schema = {};
  for (const [key, value] of Object.entries(rest)) {
    out[key] = convert(value, dir, emitted, defs);
  }
  if (example !== undefined && out.examples === undefined) {
    out.examples = [example];
  }

  const ref = out.$ref;
  if (typeof ref === "string" && ref.endsWith(".yaml")) {
    const target = join(dir, ref);
    if (emitted.has(target)) {
      out.$ref = `${basename(ref, ".yaml")}.json`;
    } else {
      const name = defName(ref);
      if (!defs.has(name)) {
        defs.set(name, {}); // reserve before recursing so a self-reference terminates
        defs.set(name, convert(loadYaml(target), dirname(target), emitted, defs) as Schema);
      }
      out.$ref = `#/$defs/${name}`;
    }
  }

  if (local === undefined) {
    return out;
  }
  if (local !== LOCAL_FILE) {
    throw new Error(
      `unsupported ${LOCAL_KEY} value ${JSON.stringify(local)}; the only kind is "${LOCAL_FILE}"`,
    );
  }
  defs.set(LOCAL_FILE_DEF, LOCAL_FILE_REFERENCE);
  const annotations: Schema = {};
  const value: Schema = {};
  for (const [key, keyword] of Object.entries(out)) {
    (ANNOTATION_KEYWORDS.has(key) ? annotations : value)[key] = keyword;
  }
  return {
    ...annotations,
    [LOCAL_KEY]: LOCAL_FILE,
    anyOf: [value, { $ref: `#/$defs/${LOCAL_FILE_DEF}` }],
  };
}

/** Every YAML file under `dir` that declares `x-meta-schema`, as absolute paths. */
export function findSources(dir: string): string[] {
  return readdirSync(dir, { recursive: true, encoding: "utf8" })
    .filter((file) => file.endsWith(".yaml"))
    .map((file) => join(dir, file))
    .filter((file) => EMIT_KEY in loadYaml(file))
    .sort();
}

/** The JSON Schema one source file generates, given the full set of emitted sources. */
export function generateSchema(source: string, emitted: ReadonlySet<string>): Schema {
  const defs = new Map<string, Schema>();
  const yaml = loadYaml(source);
  const body = convert(yaml, dirname(source), emitted, defs) as Schema;
  return {
    $comment: MARKER,
    $schema: DRAFT,
    title: defName(source),
    ...body,
    ...(yaml[EMIT_KEY] === "json-schema" ? { allOf: [{ $ref: DRAFT }] } : {}),
    ...(defs.size > 0 ? { $defs: Object.fromEntries(defs) } : {}),
  };
}

const isDirectRun =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href;

if (isDirectRun) {
  const sources = findSources(join(ROOT, "api/openapi"));
  const emitted = new Set(sources);
  for (const source of sources) {
    const outPath = join(OUT_DIR, `${basename(source, ".yaml")}.json`);
    writeFileSync(outPath, `${JSON.stringify(generateSchema(source, emitted), null, 2)}\n`);
    console.log(`${relative(ROOT, source)} → ${relative(ROOT, outPath)}`);
  }
}
