/**
 * The Go code-generation outputs, as one list.
 *
 * These globs mirror the `outputs` of the `server:generate` Moon task — keep
 * the two in sync. They are deliberately file-precise rather than
 * directory-wide: `internal/domain` holds hand-written code alongside its
 * generated `*_enumer.go`, so a directory-level pattern here would be a
 * destructive mistake waiting to happen.
 */
import { closeSync, existsSync, openSync, readdirSync, readSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = fileURLToPath(new URL("..", import.meta.url));

export const GENERATED_GLOBS = [
  "api/generated/**/*.go",
  "api/openapi/components/schemas/errors/**/*.yaml",
  "api/openapi/endpoints/**/*-error-response.yaml",
  "internal/**/*_enumer.go",
  "internal/**/*.mock.go",
];

/**
 * Every generator here stamps a marker in the first few lines — ogen and
 * MockGen write "Code generated by …", gen_openapi_errors writes
 * "generated by …". Checking it is the safety net that makes deletion safe:
 * a glob that ever matches a hand-written file is caught here instead of
 * silently eating someone's work.
 */
const MARKER = /^(\/\/|#).*generated by .*DO NOT EDIT/im;

// Enough for the header every generator stamps in its first line or two.
const HEADER_BYTES = 512;

export function hasGeneratedMarker(absPath) {
  // Read from a descriptor rather than whole-file: the marker is always in the
  // header, and api/generated alone is megabytes of ogen output to slurp for a
  // line that cannot be below the first few. A multi-byte rune split at the
  // boundary decodes to a replacement char, which the marker never contains.
  const fd = openSync(absPath, "r");
  try {
    const header = Buffer.alloc(HEADER_BYTES);
    const read = readSync(fd, header, 0, HEADER_BYTES, 0);
    return MARKER.test(header.toString("utf8", 0, read));
  } finally {
    closeSync(fd);
  }
}

/**
 * Matches a glob the way git's `:(glob)` pathspecs do, which is what
 * check-go-generate compares the worktree with — `**` spans directories, `*`
 * stays inside one segment, and a leading dot is not special.
 *
 * That last part is why this is not `fs.globSync`: Node's glob silently skips
 * dot-directories, and `api/openapi/endpoints/.well-known/` holds real
 * generated output. Anything orphaned under one was invisible to both the
 * prune and the check that depends on it.
 */
function globToRegExp(pattern) {
  // Split on `**` first: the segments around it are escaped and expanded on
  // their own, so a `*` this function emits is never mistaken for one the
  // pattern wrote.
  const source = pattern
    .split("/**/")
    .map((segment) => segment.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*/g, "[^/]*"))
    .join("/(?:.*/)?");
  return new RegExp(`^${source}$`);
}

/** Every file under a repo-relative directory, itself repo-relative. */
function filesUnder(dir) {
  const absolute = join(ROOT, dir);
  // api/generated is gone on a pruned tree, and internal/** always exists.
  if (!existsSync(absolute)) {
    return [];
  }
  return readdirSync(absolute, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) => relative(ROOT, join(entry.parentPath, entry.name)));
}

/**
 * Splits everything the globs match into files carrying the marker and files
 * that do not. Callers decide what to do with the strays; nothing here
 * deletes anything.
 */
export function collectGeneratedFiles() {
  const matched = GENERATED_GLOBS.flatMap((pattern) => {
    // Every glob is rooted at a literal directory before its first `**`, so the
    // walk stays inside the trees that hold generated output.
    const root = pattern.slice(0, pattern.indexOf("/**/"));
    const matches = globToRegExp(pattern);
    return filesUnder(root).filter((rel) => matches.test(rel));
  });
  const unique = [...new Set(matched)].sort();

  const generated = [];
  const unmarked = [];
  for (const rel of unique) {
    (hasGeneratedMarker(join(ROOT, rel)) ? generated : unmarked).push(rel);
  }
  return { generated, unmarked };
}
