// AUTO-GENERATED by scripts/stage-local.ts. Do not edit.
import type { PackageRow } from './landing.js'

export const SNAPSHOT_PACKAGES: readonly PackageRow[] = [
  {
    "name": "@mridang/bar",
    "version": "0.0.0",
    "sizeBytes": 931
  },
  {
    "name": "@mridang/baz",
    "version": "0.0.0",
    "sizeBytes": 755
  },
  {
    "name": "@mridang/foo",
    "version": "0.0.0",
    "sizeBytes": 844
  }
] as const
