DROP INDEX IF EXISTS zitadel_nextgen.idx_flow_definitions_instance_purpose;
DROP INDEX IF EXISTS zitadel_nextgen.idx_flow_definitions_jsonb_instance_status;
DROP TABLE IF EXISTS zitadel_nextgen.flow_definitions_jsonb;
