// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/nextgen/internal/storage/v2/dialect/idgen (interfaces: Generator)
//
// Generated by this command:
//
//	mockgen -typed -package idgenmock -destination ./idgenmock/idgen.mock.go github.com/zitadel/nextgen/internal/storage/v2/dialect/idgen Generator
//

// Package idgenmock is a generated GoMock package.
package idgenmock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGenerator is a mock of Generator interface.
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorMockRecorder
	isgomock struct{}
}

// MockGeneratorMockRecorder is the mock recorder for MockGenerator.
type MockGeneratorMockRecorder struct {
	mock *MockGenerator
}

// NewMockGenerator creates a new mock instance.
func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &MockGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerator) EXPECT() *MockGeneratorMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockGenerator) New(prefix string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", prefix)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockGeneratorMockRecorder) New(prefix any) *MockGeneratorNewCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockGenerator)(nil).New), prefix)
	return &MockGeneratorNewCall{Call: call}
}

// MockGeneratorNewCall wrap *gomock.Call
type MockGeneratorNewCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGeneratorNewCall) Return(arg0 string, arg1 error) *MockGeneratorNewCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGeneratorNewCall) Do(f func(string) (string, error)) *MockGeneratorNewCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGeneratorNewCall) DoAndReturn(f func(string) (string, error)) *MockGeneratorNewCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
