// Code generated by "enumer -type AuthCheckType -transform snake -trimprefix AuthCheckType"; DO NOT EDIT.

package domain

import (
	"fmt"
	"strings"
)

const _AuthCheckTypeName = "unspecifieduserpasswordpasskeyidentity_provider"

var _AuthCheckTypeIndex = [...]uint8{0, 11, 15, 23, 30, 47}

const _AuthCheckTypeLowerName = "unspecifieduserpasswordpasskeyidentity_provider"

func (i AuthCheckType) String() string {
	if i >= AuthCheckType(len(_AuthCheckTypeIndex)-1) {
		return fmt.Sprintf("AuthCheckType(%d)", i)
	}
	return _AuthCheckTypeName[_AuthCheckTypeIndex[i]:_AuthCheckTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AuthCheckTypeNoOp() {
	var x [1]struct{}
	_ = x[AuthCheckTypeUnspecified-(0)]
	_ = x[AuthCheckTypeUser-(1)]
	_ = x[AuthCheckTypePassword-(2)]
	_ = x[AuthCheckTypePasskey-(3)]
	_ = x[AuthCheckTypeIdentityProvider-(4)]
}

var _AuthCheckTypeValues = []AuthCheckType{AuthCheckTypeUnspecified, AuthCheckTypeUser, AuthCheckTypePassword, AuthCheckTypePasskey, AuthCheckTypeIdentityProvider}

var _AuthCheckTypeNameToValueMap = map[string]AuthCheckType{
	_AuthCheckTypeName[0:11]:       AuthCheckTypeUnspecified,
	_AuthCheckTypeLowerName[0:11]:  AuthCheckTypeUnspecified,
	_AuthCheckTypeName[11:15]:      AuthCheckTypeUser,
	_AuthCheckTypeLowerName[11:15]: AuthCheckTypeUser,
	_AuthCheckTypeName[15:23]:      AuthCheckTypePassword,
	_AuthCheckTypeLowerName[15:23]: AuthCheckTypePassword,
	_AuthCheckTypeName[23:30]:      AuthCheckTypePasskey,
	_AuthCheckTypeLowerName[23:30]: AuthCheckTypePasskey,
	_AuthCheckTypeName[30:47]:      AuthCheckTypeIdentityProvider,
	_AuthCheckTypeLowerName[30:47]: AuthCheckTypeIdentityProvider,
}

var _AuthCheckTypeNames = []string{
	_AuthCheckTypeName[0:11],
	_AuthCheckTypeName[11:15],
	_AuthCheckTypeName[15:23],
	_AuthCheckTypeName[23:30],
	_AuthCheckTypeName[30:47],
}

// AuthCheckTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AuthCheckTypeString(s string) (AuthCheckType, error) {
	if val, ok := _AuthCheckTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AuthCheckTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AuthCheckType values", s)
}

// AuthCheckTypeValues returns all values of the enum
func AuthCheckTypeValues() []AuthCheckType {
	return _AuthCheckTypeValues
}

// AuthCheckTypeStrings returns a slice of all String values of the enum
func AuthCheckTypeStrings() []string {
	strs := make([]string, len(_AuthCheckTypeNames))
	copy(strs, _AuthCheckTypeNames)
	return strs
}

// IsAAuthCheckType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AuthCheckType) IsAAuthCheckType() bool {
	for _, v := range _AuthCheckTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
