// Code generated by "enumer -type EnvironmentClass -transform snake -trimprefix EnvironmentClass -sql"; DO NOT EDIT.

package domain

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _EnvironmentClassName = "livepreview"

var _EnvironmentClassIndex = [...]uint8{0, 4, 11}

const _EnvironmentClassLowerName = "livepreview"

func (i EnvironmentClass) String() string {
	if i >= EnvironmentClass(len(_EnvironmentClassIndex)-1) {
		return fmt.Sprintf("EnvironmentClass(%d)", i)
	}
	return _EnvironmentClassName[_EnvironmentClassIndex[i]:_EnvironmentClassIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EnvironmentClassNoOp() {
	var x [1]struct{}
	_ = x[EnvironmentClassLive-(0)]
	_ = x[EnvironmentClassPreview-(1)]
}

var _EnvironmentClassValues = []EnvironmentClass{EnvironmentClassLive, EnvironmentClassPreview}

var _EnvironmentClassNameToValueMap = map[string]EnvironmentClass{
	_EnvironmentClassName[0:4]:       EnvironmentClassLive,
	_EnvironmentClassLowerName[0:4]:  EnvironmentClassLive,
	_EnvironmentClassName[4:11]:      EnvironmentClassPreview,
	_EnvironmentClassLowerName[4:11]: EnvironmentClassPreview,
}

var _EnvironmentClassNames = []string{
	_EnvironmentClassName[0:4],
	_EnvironmentClassName[4:11],
}

// EnvironmentClassString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EnvironmentClassString(s string) (EnvironmentClass, error) {
	if val, ok := _EnvironmentClassNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EnvironmentClassNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EnvironmentClass values", s)
}

// EnvironmentClassValues returns all values of the enum
func EnvironmentClassValues() []EnvironmentClass {
	return _EnvironmentClassValues
}

// EnvironmentClassStrings returns a slice of all String values of the enum
func EnvironmentClassStrings() []string {
	strs := make([]string, len(_EnvironmentClassNames))
	copy(strs, _EnvironmentClassNames)
	return strs
}

// IsAEnvironmentClass returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EnvironmentClass) IsAEnvironmentClass() bool {
	for _, v := range _EnvironmentClassValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i EnvironmentClass) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *EnvironmentClass) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of EnvironmentClass: %[1]T(%[1]v)", value)
	}

	val, err := EnvironmentClassString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
