// Code generated by "enumer -type FlowDefinitionTransitionAction -transform snake -trimprefix FlowDefinitionTransitionAction -sql"; DO NOT EDIT.

package domain

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _FlowDefinitionTransitionActionName = "switchpivot"

var _FlowDefinitionTransitionActionIndex = [...]uint8{0, 6, 11}

const _FlowDefinitionTransitionActionLowerName = "switchpivot"

func (i FlowDefinitionTransitionAction) String() string {
	if i >= FlowDefinitionTransitionAction(len(_FlowDefinitionTransitionActionIndex)-1) {
		return fmt.Sprintf("FlowDefinitionTransitionAction(%d)", i)
	}
	return _FlowDefinitionTransitionActionName[_FlowDefinitionTransitionActionIndex[i]:_FlowDefinitionTransitionActionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FlowDefinitionTransitionActionNoOp() {
	var x [1]struct{}
	_ = x[Switch-(0)]
	_ = x[Pivot-(1)]
}

var _FlowDefinitionTransitionActionValues = []FlowDefinitionTransitionAction{Switch, Pivot}

var _FlowDefinitionTransitionActionNameToValueMap = map[string]FlowDefinitionTransitionAction{
	_FlowDefinitionTransitionActionName[0:6]:       Switch,
	_FlowDefinitionTransitionActionLowerName[0:6]:  Switch,
	_FlowDefinitionTransitionActionName[6:11]:      Pivot,
	_FlowDefinitionTransitionActionLowerName[6:11]: Pivot,
}

var _FlowDefinitionTransitionActionNames = []string{
	_FlowDefinitionTransitionActionName[0:6],
	_FlowDefinitionTransitionActionName[6:11],
}

// FlowDefinitionTransitionActionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FlowDefinitionTransitionActionString(s string) (FlowDefinitionTransitionAction, error) {
	if val, ok := _FlowDefinitionTransitionActionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FlowDefinitionTransitionActionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FlowDefinitionTransitionAction values", s)
}

// FlowDefinitionTransitionActionValues returns all values of the enum
func FlowDefinitionTransitionActionValues() []FlowDefinitionTransitionAction {
	return _FlowDefinitionTransitionActionValues
}

// FlowDefinitionTransitionActionStrings returns a slice of all String values of the enum
func FlowDefinitionTransitionActionStrings() []string {
	strs := make([]string, len(_FlowDefinitionTransitionActionNames))
	copy(strs, _FlowDefinitionTransitionActionNames)
	return strs
}

// IsAFlowDefinitionTransitionAction returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FlowDefinitionTransitionAction) IsAFlowDefinitionTransitionAction() bool {
	for _, v := range _FlowDefinitionTransitionActionValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i FlowDefinitionTransitionAction) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *FlowDefinitionTransitionAction) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of FlowDefinitionTransitionAction: %[1]T(%[1]v)", value)
	}

	val, err := FlowDefinitionTransitionActionString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
