// Code generated by "enumer -type JSONSchemaKind -trimprefix JSONSchemaKind -linecomment -sql"; DO NOT EDIT.

package domain

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _JSONSchemaKindName = "unknownuser-schema"

var _JSONSchemaKindIndex = [...]uint8{0, 7, 18}

const _JSONSchemaKindLowerName = "unknownuser-schema"

func (i JSONSchemaKind) String() string {
	if i >= JSONSchemaKind(len(_JSONSchemaKindIndex)-1) {
		return fmt.Sprintf("JSONSchemaKind(%d)", i)
	}
	return _JSONSchemaKindName[_JSONSchemaKindIndex[i]:_JSONSchemaKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _JSONSchemaKindNoOp() {
	var x [1]struct{}
	_ = x[JSONSchemaKindUnknown-(0)]
	_ = x[JSONSchemaKindUserSchema-(1)]
}

var _JSONSchemaKindValues = []JSONSchemaKind{JSONSchemaKindUnknown, JSONSchemaKindUserSchema}

var _JSONSchemaKindNameToValueMap = map[string]JSONSchemaKind{
	_JSONSchemaKindName[0:7]:       JSONSchemaKindUnknown,
	_JSONSchemaKindLowerName[0:7]:  JSONSchemaKindUnknown,
	_JSONSchemaKindName[7:18]:      JSONSchemaKindUserSchema,
	_JSONSchemaKindLowerName[7:18]: JSONSchemaKindUserSchema,
}

var _JSONSchemaKindNames = []string{
	_JSONSchemaKindName[0:7],
	_JSONSchemaKindName[7:18],
}

// JSONSchemaKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func JSONSchemaKindString(s string) (JSONSchemaKind, error) {
	if val, ok := _JSONSchemaKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _JSONSchemaKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to JSONSchemaKind values", s)
}

// JSONSchemaKindValues returns all values of the enum
func JSONSchemaKindValues() []JSONSchemaKind {
	return _JSONSchemaKindValues
}

// JSONSchemaKindStrings returns a slice of all String values of the enum
func JSONSchemaKindStrings() []string {
	strs := make([]string, len(_JSONSchemaKindNames))
	copy(strs, _JSONSchemaKindNames)
	return strs
}

// IsAJSONSchemaKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i JSONSchemaKind) IsAJSONSchemaKind() bool {
	for _, v := range _JSONSchemaKindValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i JSONSchemaKind) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *JSONSchemaKind) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of JSONSchemaKind: %[1]T(%[1]v)", value)
	}

	val, err := JSONSchemaKindString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
