// Code generated by "enumer -type ProjectMode -transform snake -trimprefix ProjectMode -sql"; DO NOT EDIT.

package domain

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _ProjectModeName = "sandboxproduction"

var _ProjectModeIndex = [...]uint8{0, 7, 17}

const _ProjectModeLowerName = "sandboxproduction"

func (i ProjectMode) String() string {
	if i >= ProjectMode(len(_ProjectModeIndex)-1) {
		return fmt.Sprintf("ProjectMode(%d)", i)
	}
	return _ProjectModeName[_ProjectModeIndex[i]:_ProjectModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ProjectModeNoOp() {
	var x [1]struct{}
	_ = x[ProjectModeSandbox-(0)]
	_ = x[ProjectModeProduction-(1)]
}

var _ProjectModeValues = []ProjectMode{ProjectModeSandbox, ProjectModeProduction}

var _ProjectModeNameToValueMap = map[string]ProjectMode{
	_ProjectModeName[0:7]:       ProjectModeSandbox,
	_ProjectModeLowerName[0:7]:  ProjectModeSandbox,
	_ProjectModeName[7:17]:      ProjectModeProduction,
	_ProjectModeLowerName[7:17]: ProjectModeProduction,
}

var _ProjectModeNames = []string{
	_ProjectModeName[0:7],
	_ProjectModeName[7:17],
}

// ProjectModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ProjectModeString(s string) (ProjectMode, error) {
	if val, ok := _ProjectModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ProjectModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ProjectMode values", s)
}

// ProjectModeValues returns all values of the enum
func ProjectModeValues() []ProjectMode {
	return _ProjectModeValues
}

// ProjectModeStrings returns a slice of all String values of the enum
func ProjectModeStrings() []string {
	strs := make([]string, len(_ProjectModeNames))
	copy(strs, _ProjectModeNames)
	return strs
}

// IsAProjectMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ProjectMode) IsAProjectMode() bool {
	for _, v := range _ProjectModeValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i ProjectMode) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *ProjectMode) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of ProjectMode: %[1]T(%[1]v)", value)
	}

	val, err := ProjectModeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
