package domain

import (
	"context"
	"encoding/json"
	"time"

	"github.com/zitadel/nextgen/internal/crypto"
	"github.com/zitadel/nextgen/internal/storage/database"
)

const (
	PrefixSession       ResourcePrefix = "sess"
	SessionAnonymousTTL                = 10 * time.Minute
)

func ErrSessionNotFound() Error {
	return newError("sess.not_found", "The session was not found", nil, nil)
}

func ErrSessionInvalidHandoffToken() Error {
	return newError("sess.invalid_handoff_token", "The handoff token is invalid. Either the token does not exists, was already consumed or has expired", nil, nil)
}

func ErrSessionExchangeConflict() Error {
	return newError("sess.exchange_conflict", "The exchange resulted in a conflict. Either the target session was revoked or verified factors could not be promoted consistently.", nil, nil)
}

func ErrSessionTokenCreationFailed() Error {
	return newError("sess.token_creation_failed", "The session token could not be created", nil, nil)
}

func ErrSessionTokenInvalid() Error {
	return newError("sess.token_invalid", "The session token is invalid (either malformed or expired).", nil, nil)
}

func ErrSessionInvalidTTL() Error {
	return newError("sess.invalid_ttl", "The session TTL is invalid. It must be positive and not exceed the configured maximum.", nil, nil)
}

type SessionInvalidTTLDetails struct {
	TTL    time.Duration `json:"ttl"`
	MaxTTL time.Duration `json:"max_ttl"`
}

func sessionInvalidTTLErr(requested, maxTTL time.Duration) Error {
	return ErrSessionInvalidTTL().WithDetails(SessionInvalidTTLDetails{
		TTL:    requested,
		MaxTTL: maxTTL,
	})
}

// ResolveSessionTTL picks the effective session TTL for exchange.
// When requested is nil, defaultTTL is used. Otherwise requested must be positive and <= maxTTL.
func ResolveSessionTTL(requested *time.Duration, defaultTTL, maxTTL time.Duration) (time.Duration, error) {
	if requested == nil {
		return defaultTTL, nil
	}
	if *requested <= 0 {
		return 0, sessionInvalidTTLErr(*requested, maxTTL)
	}
	if *requested > maxTTL {
		return 0, sessionInvalidTTLErr(*requested, maxTTL)
	}
	return *requested, nil
}

// Session represents the object defined [here](https://github.com/zitadel/nextgen/blob/main/docs/design/api/resource-map.md#sessions-durable-post-auth-only)
type Session struct {
	// ProjectID links to [Project].
	ProjectID string
	// ID is the unique identifier for the session within the project and user.
	ID string

	// CreatedAt is the time when the session was created, it must be set by the storage and is read only.
	CreatedAt time.Time
	// UpdatedAt is the time when the session was last updated, it must be set by the storage and is read only.
	UpdatedAt time.Time
	// ExpiresAt is the time when the session expires. Is used for garbage collection.
	ExpiresAt time.Time
	// TimeToLive is the duration after which the session expires.
	TimeToLive time.Duration

	// TokenID is the id of the token that was generated for the session. The token must be generated by the storage and its id must be set to the session.
	TokenID string

	// UserID links to the [User] the session belongs to once associated.
	// A user may have multiple sessions (e.g. from different devices or browsers), and UserID may be nil during some lifecycle stages.
	UserID *string

	// UserAgent contains information about the user's device and browser.
	UserAgent *UserAgent

	// AssuranceLevels are computed at runtime and therefore not stored in the database.
	AssuranceLevels []string
	// Factors contain the authentication factors that were used to verify the session.
	// There is one factor per [AuthCheckType].
	// The factors must be verified using [AuthAttempt]s before being added to the session, and the VerifiedAt field must be set to the time of verification.
	// The factors are stored in the database.
	Factors []AuthFactor
}

func NewSession(projectID string, agent *UserAgent) (*Session, error) {
	return &Session{
		ProjectID:  projectID,
		UserAgent:  agent,
		TimeToLive: SessionAnonymousTTL,
	}, nil
}

func (s *Session) State() SessionState {
	if len(s.Factors) == 0 {
		return SessionStateBuilding
	}
	if time.Now().After(s.ExpiresAt) {
		return SessionStateExpired
	}
	return SessionStateActive
}

func (s *Session) Token(encrypter crypto.Encrypter) (string, error) {
	payload, err := json.Marshal(&SessionToken{
		ProjectID: s.ProjectID,
		SessionID: s.ID,
		TokenID:   s.TokenID,
		UserID:    s.UserID,
		CreatedAt: s.UpdatedAt,
		ExpiresAt: s.ExpiresAt,
	})
	if err != nil {
		return "", ErrSessionTokenCreationFailed()
	}
	token, err := encrypter.Encrypt(string(payload))
	if err != nil {
		return "", ErrSessionTokenCreationFailed()
	}
	return token, nil
}

func DecryptSessionTokenString(tokenString string, decrypter crypto.Decrypter) (*SessionToken, error) {
	if tokenString == "" {
		return nil, ErrSessionTokenInvalid()
	}
	payload, err := decrypter.Decrypt(tokenString)
	if err != nil {
		return nil, ErrSessionTokenInvalid()
	}
	var sessionToken SessionToken
	err = json.Unmarshal([]byte(payload), &sessionToken)
	if err != nil {
		return nil, ErrSessionTokenInvalid()
	}
	return &sessionToken, err
}

type SessionState uint8

const (
	SessionStateUnspecified SessionState = iota
	SessionStateBuilding
	SessionStateActive
	SessionStateExpired
)

// UserAgent contains information about the user's device and browser.
type UserAgent struct {
	ID   string
	IP   string
	Info map[string]any
}

type SessionToken struct {
	ProjectID string
	SessionID string
	TokenID   string
	UserID    *string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type SessionRepository interface {
	// Create creates a new (anonymous) session.
	// The storage must set the ID and the read-only fields (CreatedAt, UpdatedAt), create a token, and set its id to the session.
	Create(ctx context.Context, q database.QueryExecutor, session *Session) error

	// Exchange is used to exchange a handoff token issued on an auth attempt for a session.
	// In case the handoff token is valid, either the session associated with the auth attempt is updated or a new session is created if no session was linked.
	// All the auth attempts (verified) factors are merged into the session.
	// The auth attempt, including handoff token and unverified challenges, are deleted.
	// And the newly created or updated session is returned.
	//
	// In case the handoff token is invalid in any way (e.g. the token does not exist, was already consumed, or has expired), ErrSessionInvalidHandoffToken is returned.
	// In case of a conflict during the exchange (e.g. the session was revoked or verified factors could not be promoted consistently), the session is not upgraded and ErrSessionExchangeConflict is returned.
	Exchange(ctx context.Context, q database.QueryExecutor, projectID, handoffToken string, idempotencyKey *string, ttl time.Duration) (*Session, error)

	// Get retrieves a session by its ID. It returns ErrSessionNotFound if no session with the given ID exists within the project.
	Get(ctx context.Context, q database.QueryExecutor, projectID, sessionID string) (*Session, error)

	// List returns all sessions within the project and
	List(ctx context.Context, q database.QueryExecutor, projectID string) ([]*Session, error)

	// Delete removes a session by its ID.
	Delete(ctx context.Context, q database.QueryExecutor, projectID, sessionID string) error
}
