package domain

import (
	"maps"
	"time"

	"github.com/muhlemmer/gu"
	"github.com/zitadel/oidc/v3/pkg/op"
)

const (
	PrefixSession       ResourcePrefix = "sess"
	PrefixUserAgent     ResourcePrefix = "ua"
	SessionAnonymousTTL                = 10 * time.Minute
)

func ErrSessionNotFound() Error {
	return newError("sess.not_found", "The session was not found", nil, nil)
}

func ErrSessionInvalidHandoffToken() Error {
	return newError("sess.invalid_handoff_token", "The handoff token is invalid. Either the token does not exists, was already consumed or has expired", nil, nil)
}

func ErrSessionExchangeConflict() Error {
	return newError("sess.exchange_conflict", "The exchange resulted in a conflict. Either the target session was revoked or verified factors could not be promoted consistently.", nil, nil)
}

func ErrSessionTokenCreationFailed() Error {
	return newError("sess.token_creation_failed", "The session token could not be created", nil, nil)
}

func ErrSessionTokenInvalid() Error {
	return newError("sess.token_invalid", "The session token is invalid (either malformed or expired).", nil, nil)
}

func ErrSessionPermissionDenied() Error {
	return newError(PrefixSession.ErrorCodePrefix("permission_denied"), "session: requires a session scope bound to the project", nil, nil)
}

func ErrSessionInvalidTTL() Error {
	return newError("sess.invalid_ttl", "The session TTL is invalid. It must be positive and not exceed the configured maximum.", nil, nil)
}

type SessionInvalidTTLDetails struct {
	TTL    time.Duration `json:"ttl"`
	MaxTTL time.Duration `json:"max_ttl"`
}

func sessionInvalidTTLErr(requested, maxTTL time.Duration) Error {
	return ErrSessionInvalidTTL().WithDetails(SessionInvalidTTLDetails{
		TTL:    requested,
		MaxTTL: maxTTL,
	})
}

// ResolveSessionTTL picks the effective session TTL for exchange.
// When requested is nil, defaultTTL is used. Otherwise requested must be positive and <= maxTTL.
func ResolveSessionTTL(requested *time.Duration, defaultTTL, maxTTL time.Duration) (time.Duration, error) {
	if requested == nil {
		return defaultTTL, nil
	}
	if *requested <= 0 {
		return 0, sessionInvalidTTLErr(*requested, maxTTL)
	}
	if *requested > maxTTL {
		return 0, sessionInvalidTTLErr(*requested, maxTTL)
	}
	return *requested, nil
}

// Session represents the object defined [here](https://github.com/zitadel/nextgen/blob/main/docs/design/api/resource-map.md#sessions-durable-post-auth-only)
type Session struct {
	// ProjectID links to [Project].
	ProjectID string
	// ID is the unique identifier for the session within the project and user.
	ID string

	// CreatedAt is the time when the session was created, it must be set by the storage and is read only.
	CreatedAt time.Time
	// UpdatedAt is the time when the session was last updated, it must be set by the storage and is read only.
	UpdatedAt time.Time
	// ExpiresAt is the time when the session expires. Is used for garbage collection.
	ExpiresAt time.Time
	// TimeToLive is the duration after which the session expires.
	TimeToLive time.Duration

	// TokenID is the id of the token that was generated for the session. The token must be generated by the storage and its id must be set to the session.
	TokenID string

	// UserID links to the [User] the session belongs to once associated.
	// A user may have multiple sessions (e.g. from different devices or browsers), and UserID may be nil during some lifecycle stages.
	UserID *string

	// User is the hydrated identity of the linked user, carrying the
	// [IdentityAttributeKeys] attributes. Only populated when the read
	// requests it (see service.GetSessionInput.WithUserIdentity); nil for
	// anonymous sessions and plain reads.
	User *User

	// UserAgent contains information about the user's device and browser.
	UserAgent *UserAgent

	// AssuranceLevels are computed at runtime and therefore not stored in the database.
	AssuranceLevels []string
	// Factors contain the authentication factors that were used to verify the session.
	// There is one factor per [AuthCheckType].
	// The factors must be verified using [AuthAttempt]s before being added to the session, and the VerifiedAt field must be set to the time of verification.
	// The factors are stored in the database.
	Factors []AuthFactor
}

func NewSession(projectID string, agent *UserAgent) (*Session, error) {
	return &Session{
		ProjectID:  projectID,
		UserAgent:  agent.Clone(), // own our copy; storage mutates Info in place
		TimeToLive: SessionAnonymousTTL,
	}, nil
}

func (s *Session) State() SessionState {
	if !s.ExpiresAt.IsZero() && time.Now().After(s.ExpiresAt) {
		return SessionStateExpired
	}
	if len(s.Factors) == 0 {
		return SessionStateBuilding
	}
	return SessionStateActive
}

func (s *Session) Token(encrypter op.Encrypter) (string, error) {
	token, err := (&Token{
		ProjectID: s.ProjectID,
		TokenID:   s.TokenID,
		UserID:    gu.Value(s.UserID),
		Type:      TokenTypeSessionToken,
		SessionID: new(s.ID),
		CreatedAt: s.CreatedAt,
		ExpiresAt: new(s.ExpiresAt),
	}).JWE(encrypter)
	if err != nil {
		return "", ErrSessionTokenCreationFailed()
	}
	return token, nil
}

func ValidateSessionToken(token *Token) error {
	if token.Type != TokenTypeSessionToken {
		return ErrSessionTokenInvalid()
	}
	if token.SessionID == nil {
		return ErrSessionTokenInvalid()
	}
	return nil
}

type SessionState uint8

const (
	SessionStateUnspecified SessionState = iota
	SessionStateBuilding
	SessionStateActive
	SessionStateExpired
)

// UserAgent contains information about the user's device and browser.
type UserAgent struct {
	ID   string
	IP   string
	Info map[string]any
}

// Clone returns a deep copy safe to mutate independently of the original: its
// Info map is separate, so persistence side-effects (storage adds ip/fingerprint
// keys before marshalling) never leak back to a caller's request-scoped value.
// The copy is shallow over Info's values, which are always strings.
func (ua *UserAgent) Clone() *UserAgent {
	if ua == nil {
		return nil
	}
	return &UserAgent{ID: ua.ID, IP: ua.IP, Info: maps.Clone(ua.Info)}
}

// SessionField enumerates the fields of Session which can be used for filtering and
// ordering in list operations.
type SessionField uint8

const (
	SessionFieldUnspecified SessionField = iota
	SessionFieldProjectID
	SessionFieldID
	SessionFieldCreatedAt
	SessionFieldUpdatedAt
	SessionFieldExpiresAt
	SessionFieldTimeToLive
	SessionFieldTokenID
	SessionFieldUserID
)
