// Code generated by "enumer -type VariableAppliesTo -transform snake -trimprefix VariableAppliesTo -sql"; DO NOT EDIT.

package domain

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _VariableAppliesToName = "allpreview"

var _VariableAppliesToIndex = [...]uint8{0, 3, 10}

const _VariableAppliesToLowerName = "allpreview"

func (i VariableAppliesTo) String() string {
	if i >= VariableAppliesTo(len(_VariableAppliesToIndex)-1) {
		return fmt.Sprintf("VariableAppliesTo(%d)", i)
	}
	return _VariableAppliesToName[_VariableAppliesToIndex[i]:_VariableAppliesToIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _VariableAppliesToNoOp() {
	var x [1]struct{}
	_ = x[VariableAppliesToAll-(0)]
	_ = x[VariableAppliesToPreview-(1)]
}

var _VariableAppliesToValues = []VariableAppliesTo{VariableAppliesToAll, VariableAppliesToPreview}

var _VariableAppliesToNameToValueMap = map[string]VariableAppliesTo{
	_VariableAppliesToName[0:3]:       VariableAppliesToAll,
	_VariableAppliesToLowerName[0:3]:  VariableAppliesToAll,
	_VariableAppliesToName[3:10]:      VariableAppliesToPreview,
	_VariableAppliesToLowerName[3:10]: VariableAppliesToPreview,
}

var _VariableAppliesToNames = []string{
	_VariableAppliesToName[0:3],
	_VariableAppliesToName[3:10],
}

// VariableAppliesToString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func VariableAppliesToString(s string) (VariableAppliesTo, error) {
	if val, ok := _VariableAppliesToNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _VariableAppliesToNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to VariableAppliesTo values", s)
}

// VariableAppliesToValues returns all values of the enum
func VariableAppliesToValues() []VariableAppliesTo {
	return _VariableAppliesToValues
}

// VariableAppliesToStrings returns a slice of all String values of the enum
func VariableAppliesToStrings() []string {
	strs := make([]string, len(_VariableAppliesToNames))
	copy(strs, _VariableAppliesToNames)
	return strs
}

// IsAVariableAppliesTo returns "true" if the value is listed in the enum definition. "false" otherwise
func (i VariableAppliesTo) IsAVariableAppliesTo() bool {
	for _, v := range _VariableAppliesToValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i VariableAppliesTo) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *VariableAppliesTo) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of VariableAppliesTo: %[1]T(%[1]v)", value)
	}

	val, err := VariableAppliesToString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
