// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/nextgen/internal/crypto (interfaces: Encrypter,Decrypter,Crypter)
//
// Generated by this command:
//
//	mockgen -typed -package cryptomock -destination ./mock/encryption.mock.go . Encrypter,Decrypter,Crypter
//

// Package cryptomock is a generated GoMock package.
package cryptomock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEncrypter is a mock of Encrypter interface.
type MockEncrypter struct {
	ctrl     *gomock.Controller
	recorder *MockEncrypterMockRecorder
	isgomock struct{}
}

// MockEncrypterMockRecorder is the mock recorder for MockEncrypter.
type MockEncrypterMockRecorder struct {
	mock *MockEncrypter
}

// NewMockEncrypter creates a new mock instance.
func NewMockEncrypter(ctrl *gomock.Controller) *MockEncrypter {
	mock := &MockEncrypter{ctrl: ctrl}
	mock.recorder = &MockEncrypterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncrypter) EXPECT() *MockEncrypterMockRecorder {
	return m.recorder
}

// Encrypt mocks base method.
func (m *MockEncrypter) Encrypt(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncrypterMockRecorder) Encrypt(arg0 any) *MockEncrypterEncryptCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncrypter)(nil).Encrypt), arg0)
	return &MockEncrypterEncryptCall{Call: call}
}

// MockEncrypterEncryptCall wrap *gomock.Call
type MockEncrypterEncryptCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEncrypterEncryptCall) Return(arg0 string, arg1 error) *MockEncrypterEncryptCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEncrypterEncryptCall) Do(f func(string) (string, error)) *MockEncrypterEncryptCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEncrypterEncryptCall) DoAndReturn(f func(string) (string, error)) *MockEncrypterEncryptCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockDecrypter is a mock of Decrypter interface.
type MockDecrypter struct {
	ctrl     *gomock.Controller
	recorder *MockDecrypterMockRecorder
	isgomock struct{}
}

// MockDecrypterMockRecorder is the mock recorder for MockDecrypter.
type MockDecrypterMockRecorder struct {
	mock *MockDecrypter
}

// NewMockDecrypter creates a new mock instance.
func NewMockDecrypter(ctrl *gomock.Controller) *MockDecrypter {
	mock := &MockDecrypter{ctrl: ctrl}
	mock.recorder = &MockDecrypterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecrypter) EXPECT() *MockDecrypterMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockDecrypter) Decrypt(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockDecrypterMockRecorder) Decrypt(arg0 any) *MockDecrypterDecryptCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockDecrypter)(nil).Decrypt), arg0)
	return &MockDecrypterDecryptCall{Call: call}
}

// MockDecrypterDecryptCall wrap *gomock.Call
type MockDecrypterDecryptCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDecrypterDecryptCall) Return(arg0 string, arg1 error) *MockDecrypterDecryptCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDecrypterDecryptCall) Do(f func(string) (string, error)) *MockDecrypterDecryptCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDecrypterDecryptCall) DoAndReturn(f func(string) (string, error)) *MockDecrypterDecryptCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCrypter is a mock of Crypter interface.
type MockCrypter struct {
	ctrl     *gomock.Controller
	recorder *MockCrypterMockRecorder
	isgomock struct{}
}

// MockCrypterMockRecorder is the mock recorder for MockCrypter.
type MockCrypterMockRecorder struct {
	mock *MockCrypter
}

// NewMockCrypter creates a new mock instance.
func NewMockCrypter(ctrl *gomock.Controller) *MockCrypter {
	mock := &MockCrypter{ctrl: ctrl}
	mock.recorder = &MockCrypterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCrypter) EXPECT() *MockCrypterMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockCrypter) Decrypt(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockCrypterMockRecorder) Decrypt(arg0 any) *MockCrypterDecryptCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockCrypter)(nil).Decrypt), arg0)
	return &MockCrypterDecryptCall{Call: call}
}

// MockCrypterDecryptCall wrap *gomock.Call
type MockCrypterDecryptCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCrypterDecryptCall) Return(arg0 string, arg1 error) *MockCrypterDecryptCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCrypterDecryptCall) Do(f func(string) (string, error)) *MockCrypterDecryptCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCrypterDecryptCall) DoAndReturn(f func(string) (string, error)) *MockCrypterDecryptCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Encrypt mocks base method.
func (m *MockCrypter) Encrypt(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockCrypterMockRecorder) Encrypt(arg0 any) *MockCrypterEncryptCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockCrypter)(nil).Encrypt), arg0)
	return &MockCrypterEncryptCall{Call: call}
}

// MockCrypterEncryptCall wrap *gomock.Call
type MockCrypterEncryptCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCrypterEncryptCall) Return(arg0 string, arg1 error) *MockCrypterEncryptCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCrypterEncryptCall) Do(f func(string) (string, error)) *MockCrypterEncryptCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCrypterEncryptCall) DoAndReturn(f func(string) (string, error)) *MockCrypterEncryptCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
